// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "MotorsData.h"
MotorsData::MotorsData()
{
    InitializeData();
}
MotorsData::~MotorsData()
{
}
void MotorsData::InitializeData(void)
{
    ResetItem();
}
