// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "DiodeModel.h"
DiodeModel::DiodeModel()
{
}
DiodeModel::~DiodeModel()
{
}
void DiodeModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void DiodeModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
