// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "FuseModel.h"
FuseModel::FuseModel()
{
}
FuseModel::~FuseModel()
{
}
void FuseModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&ModelData);
}
void FuseModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
