// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchModel.h"
SwitchModel::SwitchModel()
{
}
SwitchModel::~SwitchModel()
{
}
void SwitchModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void SwitchModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
