// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerProgControl.h"
#include "Programs/ioSystemGraphics.h"
SteerProgControl::SteerProgControl()
{
}
SteerProgControl::~SteerProgControl()
{
}
void SteerProgControl::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
void SteerProgControl::ReceiveData(ioDataCollection* listData, ioData* data)
{
    ioVarFloat in1_Float;
    ioVarInt32 out1_Int32;
    if (listData == NULL) {}
    if (data == NULL) {}
    else if (data == &DataAp.OnRequestSteerData)
    {
        in1_Float.SetValueVar(&DataAp.FrontThrustMeas);
        OnRequestData(&in1_Float, &out1_Int32);
        DataAp.RateOfTurnMeas.SetValueVar(&out1_Int32);
    }
    else if (data == &DataControlCp1.TakeCommand)
    {
        OnCommandTakeCp1();
    }
    else if (data == &DataControlCp1.Release)
    {
        OnCommandReleaseCp1();
    }
}
void SteerProgControl::OnRequestData(ioVarFloat* inputInt32, ioVarInt32* outInt32)
{
    if (inputInt32 == NULL) {};
    if (outInt32 == NULL) {};
}
void SteerProgControl::OnCommandTakeCp1(void)
{
}
void SteerProgControl::OnCommandReleaseCp1(void)
{
}
