// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERPROGOPERATE1_H)
#define __STEERPROGOPERATE1_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Steer/Cp/SteerCpDataCp1.h"
#include "Programs/Steer/Ap/SteerApDataAp1.h"
#include "Programs/Steer/Ap/SteerApPanelAp1.h"
#include "Programs/Steer/Cp/CommandPanelCp1.h"
#include "Programs/Steer/Cp/ModePanelCp1.h"
#include "Programs/Steer/Cp/SetRefPanelCp1.h"
#include "ioModbus/ioPortProgramModbus.h"
#include "ioSystem/Ports/System/ioPortProgramSystem.h"
class SteerProgOperate1 : public ioProgram
{
public:
    SteerProgOperate1();
    virtual ~SteerProgOperate1();
    virtual void Run(Int32 activeSlot);
    virtual void ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    virtual void OnRequestData(ioVarFloat* inputInt32, ioVarInt32* outInt32);
    SteerCpDataCp1 DataCp1;
    SteerApDataAp1 DataAp1;
    SteerApPanelAp1 AutopilotAp1;
    CommandPanelCp1 CommandCp1;
    ModePanelCp1 ModeCp1;
    SetRefPanelCp1 ReferenceCp1;
    ioPortProgramModbus PortModbus;
    ioPortProgramSystem PortSystem;
};
#endif // __STEERPROGOPERATE1_H
