// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerProgOperate2.h"
#include "Programs/ioSystemGraphics.h"
SteerProgOperate2::SteerProgOperate2()
{
}
SteerProgOperate2::~SteerProgOperate2()
{
}
void SteerProgOperate2::Run(Int32 activeSlot)
{
    ioVarFloat in1_Float;
    ioVarInt32 out1_Int32;
    if (activeSlot == 0) {}
    SendData(&DataAp2.OnRequestSteerData);
    in1_Float.SetValueVar(&DataAp2.FrontThrustMeas);
    OnRequestData(&in1_Float, &out1_Int32);
    DataCp2.SteerMode.SetValueVar(&out1_Int32);
}
void SteerProgOperate2::ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent)
{
    ioSystemGraphicsType puid = ioSystemGraphics::GetGraphicsType(puidValue);
    if (puidValue == 0) {}
    if (typeEvent == ioProgramGraphicsEvent_NotDefined) {}
    switch (puid)
    {
    case Puid_Steer_Cp2_ButtTakeRequest:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCp2.TakeCommand);
        break;
    case Puid_Steer_Cp2_ButtRelease:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCp2.Release);
        break;
    case Puid_Steer_Cp2_ButtStandby:
        break;
    case Puid_Steer_Cp2_ButtCourse:
        break;
    case Puid_Steer_Cp2_ButtWork:
        break;
    } // switch
}
void SteerProgOperate2::ReceiveData(ioDataCollection* listData, ioData* data)
{
    if (listData == NULL) {}
    if (data == NULL) {}
    else if (data == &DataCp2.OnChangeCommand)
    {
        CommandCp2.TextCommandStatus.SetValueVar(&DataCp2.SteerMode);
    }
    else if (data == &DataCp2.OnChangeSteerMode)
    {
        CommandCp2.LabelCommandStatus.SetValueVar(&DataCp2.SteerMode);
    }
    else if (data == &DataAp2.OnChangeRef)
    {
        AutopilotAp2.InstrHeadingRef.SetValueVar(&DataAp2.HeadingRef);
    }
    else if (data == &DataAp2.OnChangeCompass)
    {
        SendData(&DataCp2.ModeWork);
    }
    else if (data == &DataAp2.OnChangeRudder)
    {
    }
    else if (data == &DataAp2.OnChangeThrust)
    {
    }
    else if (data == &DataAp2.OnChangeEngine)
    {
    }
}
void SteerProgOperate2::OnRequestData(ioVarFloat* inputInt32, ioVarInt32* outInt32)
{
    if (inputInt32 == NULL) {};
    if (outInt32 == NULL) {};
}
