// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerProgOperateA.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
SteerProgOperateA::SteerProgOperateA()
{
}
SteerProgOperateA::~SteerProgOperateA()
{
}
void SteerProgOperateA::InitializeTask(void)
{
    ioProgram::InitializeTask();
    AddPanel((ioPanel*)&CommandCpA);
    AddPanel((ioPanel*)&ModeCpA);
    AddPanel((ioPanel*)&ReferenceCpA);
    AddPanel((ioPanel*)&AutopilotApA);
}
void SteerProgOperateA::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
void SteerProgOperateA::ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent)
{
    ioSystemGraphicsType puid = ioSystemGraphics::GetGraphicsType(puidValue);
    if (puidValue == 0) {}
    if (typeEvent == ioProgramGraphicsEvent_NotDefined) {}
    switch (puid)
    {
    case Puid_Steer_CpA_ButtTakeRequestSteer:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCpA.TakeCommandSteer, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
        break;
    case Puid_Steer_CpA_ButtStandby:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCpA.ModeStandby, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
        break;
    case Puid_Steer_CpA_ButtCourse:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCpA.ModeAuto, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
        break;
    } // switch
}
void SteerProgOperateA::ReceiveData(ioDataCollection* listData, ioData* data)
{
    if (listData == NULL) {}
    if (data == NULL) {}
    else if (data == &DataCpA.OnChangeCommandSteer)
    {
        CommandCpA.TextCommandStatusSteer.SetValueVar(&DataCpA.ActiveStationSteer);
    }
    else if (data == &DataCpA.OnChangeSteerMode)
    {
        CommandCpA.LabelSteerMode.SetValueVar(&DataCpA.SteerMode);
    }
    else if (data == &DataApA.OnChangeRef)
    {
        AutopilotApA.InstrHeadingRef.SetValueVar(&DataApA.HeadingRef);
    }
    else if (data == &DataApA.OnChangeCompass)
    {
        SendData(&DataCpA.ModeWork, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
    }
    else if (data == &DataApA.OnChangeRudder)
    {
    }
    else if (data == &DataApA.OnChangeThrust)
    {
    }
    else if (data == &DataApA.OnChangeEngine)
    {
    }
}
