// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERPROGOPERATEA_H)
#define __STEERPROGOPERATEA_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Steer/Cp/SteerCpDataCpA.h"
#include "Programs/Steer/Ap/SteerApDataApA.h"
#include "Programs/Steer/Ap/SteerApPanelApA.h"
#include "Programs/Steer/Cp/CommandPanelCpA.h"
#include "Programs/Steer/Cp/ModePanelCpA.h"
#include "Programs/Steer/Cp/SetRefPanelCpA.h"
class SteerProgOperateA : public ioProgram
{
public:
    SteerProgOperateA();
    virtual ~SteerProgOperateA();
    virtual void Run(Int32 activeSlot);
    virtual void ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    SteerCpDataCpA DataCpA;
    SteerApDataApA DataApA;
    SteerApPanelApA AutopilotApA;
    CommandPanelCpA CommandCpA;
    ModePanelCpA ModeCpA;
    SetRefPanelCpA ReferenceCpA;
};
#endif // __STEERPROGOPERATEA_H
