// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerProgOperateM.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
SteerProgOperateM::SteerProgOperateM()
{
}
SteerProgOperateM::~SteerProgOperateM()
{
}
void SteerProgOperateM::InitializeTask(void)
{
    ioProgram::InitializeTask();
    AddPanel((ioPanel*)&CommandCpM);
    AddPanel((ioPanel*)&AutopilotApM);
    AddPanel((ioPanel*)&ModeCpM);
    AddPanel((ioPanel*)&ReferenceCpM);
}
void SteerProgOperateM::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
void SteerProgOperateM::ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent)
{
    ioSystemGraphicsType puid = ioSystemGraphics::GetGraphicsType(puidValue);
    if (puidValue == 0) {}
    if (typeEvent == ioProgramGraphicsEvent_NotDefined) {}
    switch (puid)
    {
    case Puid_Steer_CpM_ButtTakeRequestSteer:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCpM.TakeCommandSteer, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
        break;
    case Puid_Steer_CpM_ButtStandby:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCpM.ModeStandby, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
        break;
    case Puid_Steer_CpM_ButtCourse:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCpM.ModeAuto, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
        break;
    } // switch
}
void SteerProgOperateM::ReceiveData(ioDataCollection* listData, ioData* data)
{
    if (listData == NULL) {}
    if (data == NULL) {}
    else
    {
        ioSystemDataType duid = ioSystemData::GetDataType(data->GetDataID());
        switch (duid)
        {
        case Duid_Steer_CpM_OnChangeCommandSteer:
            CommandCpM.TextCommandStatusSteer.SetValueVar(&DataCpM.ActiveStationSteer);
            break;
        case Duid_Steer_ApM_OnChangeRef:
            AutopilotApM.LabelApSteer.SetValueVar(&DataApM.HeadingRef);
            break;
        case Duid_Steer_ApM_OnChangeCompass:
            SendData(&DataCpM.ModeWork, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
            break;
        case Duid_Steer_ApM_OnChangeRudder:
            break;
        case Duid_Steer_ApM_OnChangeThrust:
            break;
        case Duid_Steer_ApM_OnChangeEngine:
            break;
        case Duid_Steer_CpM_OnChangeSteerMode:
            CommandCpM.LabelSteerMode.SetValueVar(&DataCpM.SteerMode);
            break;
        } // switch
    } // else
}
