// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERPROGOPERATE2_H)
#define __STEERPROGOPERATE2_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Steer/Cp/SteerCpDataCp2.h"
#include "Programs/Steer/Ap/SteerApDataAp2.h"
#include "Programs/Steer/Ap/SteerApPanelAp2.h"
#include "Programs/Steer/Cp/CommandPanelCp2.h"
#include "Programs/Steer/Cp/ModePanelCp2.h"
#include "Programs/Steer/Cp/SetRefPanelCp2.h"
#include "ioModbus/ioPortProgramModbus.h"
#include "ioSystem/Ports/System/ioPortProgramSystem.h"
class SteerProgOperate2 : public ioProgram
{
public:
    SteerProgOperate2();
    virtual ~SteerProgOperate2();
    virtual void Run(Int32 activeSlot);
    virtual void ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    virtual void OnRequestData(ioVarFloat* inputInt32, ioVarInt32* outInt32);
    SteerCpDataCp2 DataCp2;
    SteerApDataAp2 DataAp2;
    SteerApPanelAp2 AutopilotAp2;
    CommandPanelCp2 CommandCp2;
    ModePanelCp2 ModeCp2;
    SetRefPanelCp2 ReferenceCp2;
    ioPortProgramModbus PortModbus;
    ioPortProgramSystem PortSystem;
};
#endif // __STEERPROGOPERATE2_H
