///////////////////////////////////////////////////////////
//  ObIconButton.cs
//  Implementation of the Class ObIconButton
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:47:02
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Button 
{
	public class ObIconButton 
    {
		public bool Activated;
		public bool ActiveColor;
		public bool Checked;
		public bool CornerLeft;
		public bool CornerRight;
		public string Icon;
		public string Label;
		public ObButtonSize Size;

		public ObIconButton()
        {
            Activated = false;
            ActiveColor = false;
            Checked = false;
            CornerLeft = false;
            CornerRight = false;
            Icon = string.Empty;
            Label = string.Empty;
            Size = ObButtonSize.Regular;
		}

		~ObIconButton()
        {
		}

	}//end ObIconButton

}//end namespace Button
