///////////////////////////////////////////////////////////
//  ObNotificationButton.cs
//  Implementation of the Class ObNotificationButton
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:47:14
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeApp.Components.Button 
{
	public class ObNotificationButton 
    {
		public bool Disabled;
		public bool Icon;
		public bool Indent;
		public bool OpenLeft;
		public bool OpenRight;

		public ObNotificationButton()
        {
		}

		~ObNotificationButton()
        {
		}

	}//end ObNotificationButton
}//end namespace Button
