///////////////////////////////////////////////////////////
//  ObToggleButtonGroup.cs
//  Implementation of the Class ObToggleButtonGroup
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:47:26
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeApp.Components.Button 
{
	public class ObToggleButtonGroup 
    {
		public ObToggleButtonGroup()
        {
		}

		~ObToggleButtonGroup()
        {
		}

	}//end ObToggleButtonGroup

}//end namespace Button
