// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerApPanel.h"
SteerApPanel::SteerApPanel()
{
}
SteerApPanel::~SteerApPanel()
{
}
void SteerApPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SteerApPanelGraphics, 19);
}
