// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERAPPANELAPA_H)
#define __STEERAPPANELAPA_H
#include "SteerApPanel.h"
class SteerApPanelApA : public SteerApPanel
{
public:
    SteerApPanelApA();
    virtual ~SteerApPanelApA();
    virtual void InitializeData(void);
};
#endif // __STEERAPPANELAPA_H
