// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerApDataApA.h"
SteerApDataApA::SteerApDataApA()
{
    InitializeData();
}
SteerApDataApA::~SteerApDataApA()
{
}
void SteerApDataApA::InitializeData(void)
{
    SteerApData::InitializeData();
    RudderAngleMeas.SetValue((Float)0.0);
    AddData((ioData*)&RudderAngleMeas, Duid_Steer_ApA_RudderAngleMeas);
    FrontThrustMeas.SetValue((Float)0.0);
    AddData((ioData*)&FrontThrustMeas, Duid_Steer_ApA_FrontThrustMeas);
    RateOfTurnMeas.SetValue((Float)0.0);
    AddData((ioData*)&RateOfTurnMeas, Duid_Steer_ApA_RateOfTurnMeas);
    HeadingMeas.SetValue((Float)0.00);
    AddData((ioData*)&HeadingMeas, Duid_Steer_ApA_HeadingMeas);
    FrontThrustRef.SetValue((Float)0.000);
    AddData((ioData*)&FrontThrustRef, Duid_Steer_ApA_FrontThrustRef);
    AddData((ioData*)&OnChangeRef, Duid_Steer_ApA_OnChangeRef);
    HeadingRef.SetValue((Float)0.0);
    AddData((ioData*)&HeadingRef, Duid_Steer_ApA_HeadingRef);
    RateOfTurnRef.SetValue((Float)0.0);
    AddData((ioData*)&RateOfTurnRef, Duid_Steer_ApA_RateOfTurnRef);
    RudderAngleRef.SetValue((Float)0.0);
    AddData((ioData*)&RudderAngleRef, Duid_Steer_ApA_RudderAngleRef);
    AddData((ioData*)&OnRequestSteerData, Duid_Steer_ApA_OnRequestSteerData);
    AddData((ioData*)&OnChangeCompass, Duid_Steer_ApA_OnChangeCompass);
    AddData((ioData*)&OnChangeRudder, Duid_Steer_ApA_OnChangeRudder);
    AddData((ioData*)&OnChangeThrust, Duid_Steer_ApA_OnChangeThrust);
    EngineRpmMeas.SetValue((Float)0);
    AddData((ioData*)&EngineRpmMeas, Duid_Steer_ApA_EngineRpmMeas);
    EngineRpmRef.SetValue((Float)0);
    AddData((ioData*)&EngineRpmRef, Duid_Steer_ApA_EngineRpmRef);
    AddData((ioData*)&OnChangeEngine, Duid_Steer_ApA_OnChangeEngine);
}
