// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERAPDATAAPM_H)
#define __STEERAPDATAAPM_H
#include "SteerApData.h"
class SteerApDataApM : public SteerApData
{
public:
    SteerApDataApM();
    virtual ~SteerApDataApM();
    virtual void InitializeData(void);
};
#endif // __STEERAPDATAAPM_H
