// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERAPPANELAP1_H)
#define __STEERAPPANELAP1_H
#include "SteerApPanel.h"
class SteerApPanelAp1 : public SteerApPanel
{
public:
    SteerApPanelAp1();
    virtual ~SteerApPanelAp1();
    virtual void InitializeData(void);
};
#endif // __STEERAPPANELAP1_H
