// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERAPDATA_H)
#define __STEERAPDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioEvent.h"
#include "ioSystem/Data/ioMethod.h"
class SteerApData : public ioDataCollection
{
public:
    SteerApData();
    virtual ~SteerApData();
    virtual void InitializeData(void);
    ioVarFloat RudderAngleMeas;
    ioVarFloat FrontThrustMeas;
    ioVarFloat RateOfTurnMeas;
    ioVarFloat HeadingMeas;
    ioVarFloat FrontThrustRef;
    ioEvent OnChangeRef;
    ioVarFloat HeadingRef;
    ioVarFloat RateOfTurnRef;
    ioVarFloat RudderAngleRef;
    ioMethod OnRequestSteerData;
    ioEvent OnChangeCompass;
    ioEvent OnChangeRudder;
    ioEvent OnChangeThrust;
    ioVarFloat EngineRpmMeas;
    ioVarFloat EngineRpmRef;
    ioEvent OnChangeEngine;
protected:
    ioData* m_ListData[16];
    ioVar* m_OnChangeRefVars[5];
    ioVar* m_OnChangeCompassVars[1];
    ioVar* m_OnChangeRudderVars[1];
    ioVar* m_OnChangeThrustVars[1];
    ioVar* m_OnChangeEngineVars[1];
};
#endif // __STEERAPDATA_H
