// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerApPanelAp1.h"
SteerApPanelAp1::SteerApPanelAp1()
{
    InitializeData();
}
SteerApPanelAp1::~SteerApPanelAp1()
{
}
void SteerApPanelAp1::InitializeData(void)
{
    SteerApPanel::InitializeData();
    InstrHeadingRef.SetDecimals(1);
    InstrHeading.SetDecimals(1);
    TextRotValue.SetDecimals(0);
    TextEngineValue.SetDecimals(0);
    TextThrustValue.SetDecimals(0);
}
