// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerApPanelApA.h"
SteerApPanelApA::SteerApPanelApA()
{
    InitializeData();
}
SteerApPanelApA::~SteerApPanelApA()
{
}
void SteerApPanelApA::InitializeData(void)
{
    SteerApPanel::InitializeData();
    InstrHeadingRef.SetDecimals(1);
    InstrHeading.SetDecimals(1);
    TextRotValue.SetDecimals(0);
    TextEngineValue.SetDecimals(0);
    TextThrustValue.SetDecimals(0);
}
