// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerApPanelAp2.h"
SteerApPanelAp2::SteerApPanelAp2()
{
    InitializeData();
}
SteerApPanelAp2::~SteerApPanelAp2()
{
}
void SteerApPanelAp2::InitializeData(void)
{
    SteerApPanel::InitializeData();
    InstrHeadingRef.SetDecimals(1);
    InstrHeading.SetDecimals(1);
    TextRotValue.SetDecimals(0);
    TextEngineValue.SetDecimals(0);
    TextThrustValue.SetDecimals(0);
}
