// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERAPPANELAP2_H)
#define __STEERAPPANELAP2_H
#include "SteerApPanel.h"
class SteerApPanelAp2 : public SteerApPanel
{
public:
    SteerApPanelAp2();
    virtual ~SteerApPanelAp2();
    virtual void InitializeData(void);
};
#endif // __STEERAPPANELAP2_H
