// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERAPDATAAPA_H)
#define __STEERAPDATAAPA_H
#include "SteerApData.h"
class SteerApDataApA : public SteerApData
{
public:
    SteerApDataApA();
    virtual ~SteerApDataApA();
    virtual void InitializeData(void);
};
#endif // __STEERAPDATAAPA_H
