// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerApData.h"
SteerApData::SteerApData()
{
}
SteerApData::~SteerApData()
{
}
void SteerApData::InitializeData(void)
{
    SetListData(m_ListData, 16);
    ResetItem();
}
