// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTERYMODEL_H)
#define __BATTERYMODEL_H
#include "ioSystem/Simulation/ioModel.h"
class BatteryModel : public ioModel
{
public:
    BatteryModel();
    virtual ~BatteryModel();
    virtual void InitializeItem(void);
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
};
#endif // __BATTERYMODEL_H
