// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BatteryModel.h"
BatteryModel::BatteryModel()
{
}
BatteryModel::~BatteryModel()
{
}
void BatteryModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void BatteryModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
