// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "GeneratorModel.h"
GeneratorModel::GeneratorModel()
{
}
GeneratorModel::~GeneratorModel()
{
}
void GeneratorModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&GeneratorData);
}
void GeneratorModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
