// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ioSystemPorts.h"
ioSystemPorts::ioSystemPorts()
{
}
ioSystemPorts::~ioSystemPorts()
{
}
Int32 ioSystemPorts::GetNetworkID(ioSystemPortsType nuid)
{
    return (Int32)nuid;
}
ioSystemPortsType ioSystemPorts::GetPortType(Int32 nuidValue)
{
    switch (nuidValue)
    {
    default: return Nuid_NotDefined; 
    case 0: return Nuid_NotDefined; 
    case 1: return Nuid_NetEthernet_192_168_10_Batt_CerboGx_10; 
    case 2: return Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11; 
    case 3: return Nuid_NetEthernet_192_168_10_Ids_OpM_12; 
    case 4: return Nuid_NetEthernet_192_168_10_Ids_OpA_13; 
    case 5: return Nuid_NetWiFi_192_168_11_Batt_CerboGx_10; 
    case 6: return Nuid_NetWiFi_192_168_11_Ids_CcM_C6015_11; 
    case 7: return Nuid_NetWiFi_192_168_11_Ids_OpM_12; 
    case 8: return Nuid_NetWiFi_192_168_11_Ids_OpA_13; 
    case 9: return Nuid_NetC_CanHs250_Steer_Ap_Ngx1_7; 
    case 10: return Nuid_NetC_CanHs250_Steer_Ap_GnssR_8; 
    case 11: return Nuid_NetC_CanHs250_Steer_Ap_Rudd_Rf_9; 
    } // switch
}
