// !!! This file is generated by ioStudio !!!
// Generation date and time: 21.FEB.2024 06:11:54
#include "pch.h"
#pragma hdrstop
#include "ioSystemData.h"
ioSystemData::ioSystemData()
{
}
ioSystemData::~ioSystemData()
{
}
Int32 ioSystemData::GetDataID(ioSystemDataType duid)
{
    return (Int32)duid;
}
ioSystemDataType ioSystemData::GetDataType(Int32 dataID)
{
    if ((dataID > 0) && (dataID < 249))
        return (ioSystemDataType)dataID;
    else
        return Duid_NotDefined;
}
