// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CmdModeRefPanel.h"
#include "Programs/ioSystemGraphics.h"
CmdModeRefPanel::CmdModeRefPanel()
{
}
CmdModeRefPanel::~CmdModeRefPanel()
{
}
void CmdModeRefPanel::InitializeData(void)
{
}
