// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefDrivePanel.h"
#include "Programs/ioSystemGraphics.h"
SetRefDrivePanel::SetRefDrivePanel()
{
}
SetRefDrivePanel::~SetRefDrivePanel()
{
}
void SetRefDrivePanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SetRefDrivePanelGraphics, 3);
    AddGraphics(&ButtonLeftThrust, Puid_Ids_Controller_ButtonLeftThrust);
    ButtonLeftThrust.SetTextForced((ioChars)"");
    AddGraphics(&InstrThrustCmd, Puid_Ids_Controller_InstrThrustCmd);
    InstrThrustCmd.SetTextForced((ioChars)"000");
    InstrThrustCmd.SetDecimals(1);
    AddGraphics(&ButtonRightThrust, Puid_Ids_Controller_ButtonRightThrust);
    ButtonRightThrust.SetTextForced((ioChars)"-1");
}
