// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFTHRUSTPANEL_H)
#define __SETREFTHRUSTPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioButtonText.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class SetRefThrustPanel : public ioPanel
{
public:
    SetRefThrustPanel();
    virtual ~SetRefThrustPanel();
    virtual void InitializeData(void);
    ioButtonText ButtonThrustLeftSmall;
    ioLabel LabelThrustCmdHeader;
    ioLabel LabelThrustCmdHeaderUnit;
    ioTextBlock InstrThrustCmd;
    ioButtonText ButtThrustRightSmall;
    ioButtonText ButtThrustLeftBig;
    ioButtonText ButtThrustMidZero;
    ioButtonText ButtRThrustightBig;
protected:
    ioGraphics* m_SetRefThrustPanelGraphics[8];
};
#endif // __SETREFTHRUSTPANEL_H
