// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFWINDPANEL_H)
#define __SETREFWINDPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioButtonText.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioIcon.h"
class SetRefWindPanel : public ioPanel
{
public:
    SetRefWindPanel();
    virtual ~SetRefWindPanel();
    virtual void InitializeData(void);
    ioButtonText ButtonWindLeftSmall;
    ioLabel LabelWindCmdHeader;
    ioLabel LabelWindCmdHeaderUnit;
    ioIcon IconWindPort;
    ioTextBlock InstrWindCmd;
    ioIcon IconWindStarb;
    ioButtonText ButtWindRightSmall;
    ioButtonText ButtWindLeftBig;
    ioButtonText ButtWindMidTrn;
    ioButtonText ButtWindRightBig;
protected:
    ioGraphics* m_SetRefWindPanelGraphics[10];
};
#endif // __SETREFWINDPANEL_H
