// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefHdgPanel.h"
#include "Programs/ioSystemGraphics.h"
SetRefHdgPanel::SetRefHdgPanel()
{
}
SetRefHdgPanel::~SetRefHdgPanel()
{
}
void SetRefHdgPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SetRefHdgPanelGraphics, 9);
    AddGraphics(&LabelHdgCmdHeader, Puid_Ids_Controller_LabelHdgCmdHeader);
    LabelHdgCmdHeader.SetTextForced((ioChars)"HDG CMD");
    AddGraphics(&LabelhdgCmdHeaderUnit, Puid_Ids_Controller_LabelhdgCmdHeaderUnit);
    LabelhdgCmdHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&InstrHdgCmd, Puid_Ids_Controller_InstrHdgCmd);
    InstrHdgCmd.SetTextForced((ioChars)"000");
    InstrHdgCmd.SetDecimals(1);
    AddGraphics(&ButtonLeftSmall, Puid_Ids_Controller_ButtonLeftSmall);
    ButtonLeftSmall.SetTextForced((ioChars)"-1");
    AddGraphics(&ButtMidZero, Puid_Ids_Controller_ButtMidZero);
    ButtMidZero.SetTextForced((ioChars)"0");
    AddGraphics(&ButtRightSmall, Puid_Ids_Controller_ButtRightSmall);
    ButtRightSmall.SetTextForced((ioChars)"+1");
    AddGraphics(&EncoderNumber, Puid_Ids_Controller_EncoderNumber);
    EncoderNumber.SetTextForced((ioChars)"0");
    AddGraphics(&ButtLeftBig, Puid_Ids_Controller_ButtLeftBig);
    ButtLeftBig.SetTextForced((ioChars)"-10");
    AddGraphics(&ButtRightBig, Puid_Ids_Controller_ButtRightBig);
    ButtRightBig.SetTextForced((ioChars)"+10");
}
