// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFDRIVEPANEL_H)
#define __SETREFDRIVEPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioButtonText.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class SetRefDrivePanel : public ioPanel
{
public:
    SetRefDrivePanel();
    virtual ~SetRefDrivePanel();
    virtual void InitializeData(void);
    ioButtonIcon ButtonLeftThrust;
    ioTextBlock InstrThrustCmd;
    ioButtonText ButtonRightThrust;
protected:
    ioGraphics* m_SetRefDrivePanelGraphics[3];
};
#endif // __SETREFDRIVEPANEL_H
