// !!! This C++ file is generated by ioStudio !!!
#if !defined(__DATACHARGE_H)
#define __DATACHARGE_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class DataCharge : public ioDataCollection
{
public:
    DataCharge();
    virtual ~DataCharge();
    void InitializeData(void);
    ioVarFloat VoltInputAc;
    ioVarFloat VoltOutputDc;
    ioVarBool IsOutputActive;
protected:
    ioData* m_ListData[3];
};
#endif // __DATACHARGE_H
