// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWCOMMANDMODEPANELCPA_H)
#define __POWCOMMANDMODEPANELCPA_H
#include "PowCommandModePanel.h"
class PowCommandModePanelCpA : public PowCommandModePanel
{
public:
    PowCommandModePanelCpA();
    virtual ~PowCommandModePanelCpA();
    virtual void InitializeData(void);
};
#endif // __POWCOMMANDMODEPANELCPA_H
