// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWCOMMANDPANELCPM_H)
#define __POWCOMMANDPANELCPM_H
#include "PowCommandPanel.h"
class PowCommandPanelCpM : public PowCommandPanel
{
public:
    PowCommandPanelCpM();
    virtual ~PowCommandPanelCpM();
    virtual void InitializeData(void);
};
#endif // __POWCOMMANDPANELCPM_H
