// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowCommandModePanelCpA.h"
#include "Programs/ioSystemGraphics.h"
PowCommandModePanelCpA::PowCommandModePanelCpA()
{
    InitializeData();
}
PowCommandModePanelCpA::~PowCommandModePanelCpA()
{
}
void PowCommandModePanelCpA::InitializeData(void)
{
    PowCommandModePanel::InitializeData();
}
