// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowCommandPanel.h"
PowCommandPanel::PowCommandPanel()
{
}
PowCommandPanel::~PowCommandPanel()
{
}
void PowCommandPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_PowCommandPanelGraphics, 6);
}
