// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWCOMMANDMODEPANELCPM_H)
#define __POWCOMMANDMODEPANELCPM_H
#include "PowCommandModePanel.h"
class PowCommandModePanelCpM : public PowCommandModePanel
{
public:
    PowCommandModePanelCpM();
    virtual ~PowCommandModePanelCpM();
    virtual void InitializeData(void);
};
#endif // __POWCOMMANDMODEPANELCPM_H
