// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowCommandPanelCpM.h"
#include "Programs/ioSystemGraphics.h"
PowCommandPanelCpM::PowCommandPanelCpM()
{
    InitializeData();
}
PowCommandPanelCpM::~PowCommandPanelCpM()
{
}
void PowCommandPanelCpM::InitializeData(void)
{
    PowCommandPanel::InitializeData();
    AddGraphics(&HeaderCommandPanelPow, Puid_Pow_CpM_HeaderCommandPanelPow);
    HeaderCommandPanelPow.SetTextForced((ioChars)"COMMAND POWER MID DECKHOUSE");
    AddGraphics(&ShapeCommandStatusPow, Puid_Pow_CpM_ShapeCommandStatusPow);
    AddGraphics(&LabelPowerMode, Puid_Pow_CpM_LabelPowerMode);
    LabelPowerMode.SetTextForced((ioChars)"NO POWER");
    AddGraphics(&TextCommandStatusPow, Puid_Pow_CpM_TextCommandStatusPow);
    TextCommandStatusPow.SetTextForced((ioChars)"No station in command");
    TextCommandStatusPow.SetDecimals(1);
    AddGraphics(&ButtTakeRequestPow, Puid_Pow_CpM_ButtTakeRequestPow);
    ButtTakeRequestPow.SetTextForced((ioChars)"Take");
    AddGraphics(&ButtReleasePow, Puid_Pow_CpM_ButtReleasePow);
    ButtReleasePow.SetTextForced((ioChars)"Release");
}
