// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowModePanelCpA.h"
#include "Programs/ioSystemGraphics.h"
PowModePanelCpA::PowModePanelCpA()
{
    InitializeData();
}
PowModePanelCpA::~PowModePanelCpA()
{
}
void PowModePanelCpA::InitializeData(void)
{
    PowModePanel::InitializeData();
    AddGraphics(&ButtInTransit, Puid_Pow_CpA_ButtInTransit);
    ButtInTransit.SetTextForced((ioChars)"In transit daylight (TRANSIT)");
    AddGraphics(&ButtInTransitEngine, Puid_Pow_CpA_ButtInTransitEngine);
    ButtInTransitEngine.SetTextForced((ioChars)"In transit night using engine (ENGINE)");
    AddGraphics(&ButtInTransitSailing, Puid_Pow_CpA_ButtInTransitSailing);
    ButtInTransitSailing.SetTextForced((ioChars)"In transit night sailing (SAILING)");
}
