// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattDcModel.h"
BattDcModel::BattDcModel()
{
}
BattDcModel::~BattDcModel()
{
}
void BattDcModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void BattDcModel::DoSimulation_100ms(void)
{
}
void BattDcModel::SimulateBatteryCurrent(Bool onCh1, Bool onCh2, Bool onCh3, Bool onCh4, Bool onCh5, Bool onCh6, Bool onCh7, Bool onCh8, Double* currentOut)
{
}
BattDcModelDc12::BattDcModelDc12()
{
}
BattDcModelDc12::~BattDcModelDc12()
{
}
void BattDcModelDc12::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&PowOut12M);
    AddData((ioDataCollection*)&PowOut12F);
    AddData((ioDataCollection*)&PowOut12A);
    AddData((ioDataCollection*)&BattDc12);
}
void BattDcModelDc12::DoSimulation_100ms(void)
{
    Double outValue1 = 0.0;
    SimulateBatteryCurrent(
        PowOut12M.OnCh1.GetValue(),
        PowOut12M.OnCh1.GetValue(),
        PowOut12M.OnCh1.GetValue(),
        PowOut12M.OnCh1.GetValue(),
        PowOut12M.OnCh1.GetValue(),
        PowOut12M.OnCh1.GetValue(),
        PowOut12M.OnCh1.GetValue(),
        PowOut12M.OnCh1.GetValue(),
        &outValue1
    );
    BattDc12.BattAmpOut.SetValue((Float)outValue1);
}
BattDcModelDc24::BattDcModelDc24()
{
}
BattDcModelDc24::~BattDcModelDc24()
{
}
void BattDcModelDc24::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&PowOut24M);
    AddData((ioDataCollection*)&PowOut24F);
    AddData((ioDataCollection*)&PowOut24A);
    AddData((ioDataCollection*)&BattDc24);
}
void BattDcModelDc24::DoSimulation_100ms(void)
{
    Double outValue1 = 0.0;
    SimulateBatteryCurrent(
        PowOut24M.OnCh1.GetValue(),
        PowOut24M.OnCh1.GetValue(),
        PowOut24M.OnCh1.GetValue(),
        PowOut24M.OnCh1.GetValue(),
        PowOut24M.OnCh1.GetValue(),
        PowOut24M.OnCh1.GetValue(),
        PowOut24M.OnCh1.GetValue(),
        PowOut24M.OnCh1.GetValue(),
        &outValue1
    );
    BattDc24.BattAmpOut.SetValue((Float)outValue1);
}
