// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattPanel.h"
#include "Programs/ioSystemGraphics.h"
BattPanel::BattPanel()
{
}
BattPanel::~BattPanel()
{
}
void BattPanel::InitializeData(void)
{
}
