// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTCHARGINGPANEL_H)
#define __BATTCHARGINGPANEL_H
#include "ioSystem/Panels/ioPanel.h"
class BattChargingPanel : public ioPanel
{
public:
    BattChargingPanel();
    virtual ~BattChargingPanel();
    void InitializeData(void);
};
#endif // __BATTCHARGINGPANEL_H
