// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattPanel.h"
BattPanel::BattPanel()
{
    InitializeData();
}
BattPanel::~BattPanel()
{
}
void BattPanel::InitializeData(void)
{
}
