// !!! This file is generated by ioStudio !!!
// Generation date and time: 09.FEB.2024 15:18:22
#include "pch.h"
#pragma hdrstop
#include "BattProg.h"
BattProg::BattProg()
{
}
BattProg::~BattProg()
{
}
void BattProg::ReadInput(Int32 activeSlot)
{
}
void BattProg::Run(Int32 activeSlot)
{
    Float out1_Float;
    SetRealValue(&out1_Float);
}
void BattProg::WriteOutput(Int32 activeSlot)
{
}
void BattProg::SetRealValue(Float out1_Float)
{
}
