// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTDATA_H)
#define __BATTDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioEvent.h"
#include "ioSystem/Data/ioMethod.h"
class BattData : public ioDataCollectionDynamic
{
public:
    BattData();
    virtual ~BattData();
    void InitializeData(void);
    ioVarFloat ChargeInputVolt;
    ioVarBool IsChargActive12V;
    ioVarBool IsChargActive24V;
    ioVarFloat StatusOfCharge;
    ioVarTimeInterval TimeTo10Percent;
    ioMethod RequestBattData;
    ioEvent ResponseBattData;
protected:
    ioData* m_ListData[7];
};
#endif // __BATTDATA_H
