// !!! This file is generated by ioStudio !!!
// Generation date and time: 09.FEB.2024 15:15:57
#if !defined(__BATTPROG_H)
#define __BATTPROG_H
#include "ioSystem/Threading/ioTask.h"
class BattProg : public ioTask
{
public:
    BattProg();
    virtual ~BattProg();
    virtual void ReadInput(Int32 activeSlot);
    virtual void Run(Int32 activeSlot);
    virtual void WriteOutput(Int32 activeSlot);
    virtual void SetRealValue(Float out1_Float);
    DcDataDc12 BattDcDataDc12;
    DcDataDc24 BattDcDataDc24;
    MainData BattData;
};
#endif // BATTPROG_H
