// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTSTATUSPANEL_H)
#define __BATTSTATUSPANEL_H
#include "ioSystem/Panels/ioPanel.h"
class BattStatusPanel : public ioPanel
{
public:
    BattStatusPanel();
    virtual ~BattStatusPanel();
    void InitializeData(void);
};
#endif // __BATTSTATUSPANEL_H
