// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattProgMonitorA.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
BattProgMonitorA::BattProgMonitorA()
{
}
BattProgMonitorA::~BattProgMonitorA()
{
}
void BattProgMonitorA::InitializeTask(void)
{
    ioProgram::InitializeTask();
    AddPanel((ioPanel*)&MainPanel);
    AddPanel((ioPanel*)&DcPanelDc12);
    AddPanel((ioPanel*)&DcPanelDc24);
}
void BattProgMonitorA::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
void BattProgMonitorA::ReceiveData(ioDataCollection* listData, ioData* data)
{
    if (listData == NULL) {}
    if (data == NULL) {}
    else
    {
        ioSystemDataType duid = ioSystemData::GetDataType(data->GetDataID());
        switch (duid)
        {
        case Duid_Batt_Dc12_ResponseDcData:
            DcPanelDc12.InstrVolt.SetValueVar(&DcDataDc12.BattVolt);
            DcPanelDc12.InstrAmpAvg.SetValueVar(&DcDataDc12.BattAmpOut);
            break;
        case Duid_Batt_Dc24_ResponseDcData:
            DcPanelDc24.InstrVolt.SetValueVar(&DcDataDc24.BattVolt);
            DcPanelDc24.InstrAmpAvg.SetValueVar(&DcDataDc24.BattAmpOut);
            break;
        } // switch
    } // else
}
