// !!! This file is generated by ioStudio !!!
// Generation date and time: 22.FEB.2024 07:21:31
#if !defined(__BATTPROGSENSOR_H)
#define __BATTPROGSENSOR_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Batt/Dc/BattDcDataDc12.h"
#include "Programs/Batt/Dc/BattDcDataDc24.h"
#include "Programs/Batt/BattData.h"
class BattProgSensor : public ioProgram
{
public:
    BattProgSensor();
    virtual ~BattProgSensor();
    virtual void ReadInput(Int32 activeSlot);
    virtual void Run(Int32 activeSlot);
    virtual void WriteOutput(Int32 activeSlot);
    virtual void CheckBattery(ioVarBool*  isOK, ioVarFloat* currentIn, ioVarFloat* currentOut, ioVarFloat* voltage, ioVarFloat* currentAvg);
    virtual void CalcSoc(ioVarFloat* currentAvg12V, ioVarFloat* currentAvg24V, ioVarFloat* soc, ioVarTimeInterval* timeTo10Perc);
    virtual void GetInputVoltageCharger(ioVarFloat* inputVoltage);
    BattDcDataDc12 DcDataDc12;
    BattDcDataDc24 DcDataDc24;
    BattData MainData;
};
#endif // __BATTPROGSENSOR_H
