// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattProgMonitor.h"
BattProgMonitor::BattProgMonitor()
{
}
BattProgMonitor::~BattProgMonitor()
{
}
void BattProgMonitor::ReadInput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void BattProgMonitor::Run(Int32 activeSlot)
{
    ioVarFloat in1_Float;
    ioVarDouble out1_Double;
    if (activeSlot == 0) {};
    in1_Float.SetValueVar(&DcDataDc12.BattVolt);
    SetRealValuePanel(&in1_Float, &out1_Double);
    DcPanelDc12.InstrVolt.SetValueVar(&out1_Double);
    
    in1_Float.SetValueVar(&DcDataDc12.BattAmpAvg);
    SetRealValuePanel(&in1_Float, &out1_Double);
    DcPanelDc12.InstrAmpAvg.SetValueVar(&out1_Double);
    
    in1_Float.SetValueVar(&DcDataDc24.BattVolt);
    SetRealValuePanel(&in1_Float, &out1_Double);
    DcPanelDc24.InstrVolt.SetValueVar(&out1_Double);
    
    in1_Float.SetValueVar(&DcDataDc24.BattAmpAvg);
    SetRealValuePanel(&in1_Float, &out1_Double);
    DcPanelDc24.InstrAmpAvg.SetValueVar(&out1_Double);
}
void BattProgMonitor::WriteOutput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void BattProgMonitor::SetRealValuePanel(ioVarFloat *inputValue, ioVarDouble* outValue)
{
    if (inputValue == NULL) {};
    if (outValue == NULL) {};
}
