// !!! This file is generated by ioStudio !!!
// Generation date and time: 26.JAN.2024 15:32:51
#include "pch.h"
#pragma hdrstop
#include "BattData.h"
BattData::BattData()
{
    InitializeData();
}
BattData::~BattData()
{
}
void BattData::InitializeData(void)
{
    ChargeInputVolt = (Float)220;
    IsChargActive12V = TRUE;
    IsChargActive24V = FALSE;
    StatusOfCharge = (Float)0.0;
    TimeTo10Percent.SetTotalSeconds(187140.000);
}
