// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattProgMonitor.h"
BattProgMonitor::BattProgMonitor()
{
}
BattProgMonitor::~BattProgMonitor()
{
}
void BattProgMonitor::ReadInput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void BattProgMonitor::Run(Int32 activeSlot)
{
    Float in1_Float;
    Double out1_Double;
    if (activeSlot == 0) {};
    in1_Float = DcDataDc12.BattVolt.GetValue();
    SetRealValuePanel(in1_Float, &out1_Double);
    DcPanelDc12.InstrVolt.SetValueReal(out1_Double);
    
    in1_Float = DcDataDc12.BattAmpAvg.GetValue();
    SetRealValuePanel(in1_Float, &out1_Double);
    DcPanelDc12.InstrAmpAvg.SetValueReal(out1_Double);
    
    in1_Float = DcDataDc24.BattVolt.GetValue();
    SetRealValuePanel(in1_Float, &out1_Double);
    DcPanelDc24.InstrVolt.SetValueReal(out1_Double);
    
    in1_Float = DcDataDc24.BattAmpAvg.GetValue();
    SetRealValuePanel(in1_Float, &out1_Double);
    DcPanelDc24.InstrAmpAvg.SetValueReal(out1_Double);
}
void BattProgMonitor::WriteOutput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void BattProgMonitor::SetRealValuePanel(Float inputValue, Double* outValue)
{
    if (inputValue == (Float)0.0) {};
    if (outValue == NULL) {};
}
