// !!! This file is generated by ioStudio !!!
// Generation date and time: 15.FEB.2024 11:41:14
#if !defined(__BATTPROG_H)
#define __BATTPROG_H
#include "ioSystem/Threading/ioTask.h"
#include "Programs/Batt/Dc/BattDcDataDc12.h"
#include "Programs/Batt/Dc/BattDcDataDc24.h"
#include "Programs/Batt/BattData.h"
#include "Programs/Batt/Dc/BattDcPanelDc12.h"
#include "Programs/Batt/Dc/BattDcPanelDc24.h"
#include "Programs/Batt/BattPanel.h"
class BattProg : public ioTask
{
public:
    BattProg();
    virtual ~BattProg();
    virtual void ReadInput(Int32 activeSlot);
    virtual void Run(Int32 activeSlot);
    virtual void WriteOutput(Int32 activeSlot);
    virtual Bool CheckBattery12V(Float currentIn, Float currentOut, Float voltage, Float* currentAvg);
    virtual Bool CheckBattery24V(Float currentIn, Float currentOut, Float voltage, Float* currentAvg);
    virtual void CalcSoc(Float currentAvg12V, Float currentAvg24V, Float* soc, ioTimeIntervalData* timeTo10Perc);
    virtual Float GetInputVoltageCharger(void);
    virtual Float SetPanelValue(Float valueData);
    BattDcDataDc12 DcDataDc12;
    BattDcDataDc24 DcDataDc24;
    BattData MainData;
    BattDcPanelDc12 DcPanelDc12;
    BattDcPanelDc24 DcPanelDc24;
    BattPanel MainPanel;
};
#endif // __BATTPROG_H
