// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTPROGMONITOR_H)
#define __BATTPROGMONITOR_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Batt/BattData.h"
#include "Programs/Batt/Dc/BattDcDataDc12.h"
#include "Programs/Batt/Dc/BattDcDataDc24.h"
#include "Programs/Batt/BattPanel.h"
#include "Programs/Batt/Dc/BattDcPanelDc12.h"
#include "Programs/Batt/Dc/BattDcPanelDc24.h"
class BattProgMonitor : public ioProgram
{
public:
    BattProgMonitor();
    virtual ~BattProgMonitor();
    virtual void InitializeTask(void);
    virtual void Run(Int32 activeSlot);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    BattData MainData;
    BattDcDataDc12 DcDataDc12;
    BattDcDataDc24 DcDataDc24;
    BattPanel MainPanel;
    BattDcPanelDc12 DcPanelDc12;
    BattDcPanelDc24 DcPanelDc24;
};
#endif // __BATTPROGMONITOR_H
