// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattStatusPanel.h"
BattStatusPanel::BattStatusPanel()
{
    InitializeData();
}
BattStatusPanel::~BattStatusPanel()
{
}
void BattStatusPanel::InitializeData(void)
{
}
