// !!! This file is generated by ioStudio !!!
// Generation date and time: 22.FEB.2024 07:21:31
#if !defined(__BATTPROGSENSOR_H)
#define __BATTPROGSENSOR_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Batt/Dc/BattDcDataDc12.h"
#include "Programs/Batt/Dc/BattDcDataDc24.h"
#include "Programs/Batt/BattData.h"
class BattProgSensor : public ioProgram
{
public:
    BattProgSensor();
    virtual ~BattProgSensor();
    virtual void ReadInput(Int32 activeSlot);
    virtual void Run(Int32 activeSlot);
    virtual void WriteOutput(Int32 activeSlot);
    virtual Bool CheckBattery(Float currentIn, Float currentOut, Float voltage, Float* currentAvg);
    virtual void CalcSoc(Float currentAvg12V, Float currentAvg24V, Float* soc, ioTimeIntervalData* timeTo10Perc);
    virtual Float GetInputVoltageCharger(void);
    BattDcDataDc12 DcDataDc12;
    BattDcDataDc24 DcDataDc24;
    BattData MainData;
};
#endif // __BATTPROGSENSOR_H
