///////////////////////////////////////////////////////////
//  ObAlertButton.cs
//  Implementation of the Class ObAlertButton
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:26:32
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Application 
{
    public enum ObAlertType
    {
        Alarm = 0,
        Warning,
        Caution,
        Running,
        Command,
        Notification,
        Flat,
        None
    }

	public class ObAlertButton 
    {
		public ObAlertType AlertType;
		public int Counter;
		public int NAlerts;
		private bool Standalone;

		public ObAlertButton()
        {
		}

		~ObAlertButton()
        {
		}


	}//end ObAlertButton

}//end namespace Application
