///////////////////////////////////////////////////////////
//  ObAlertMenu.cs
//  Implementation of the Class ObAlertMenu
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:26:57
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Application 
{
	public class ObAlertMenu 
    {
		public int Breakpoint;
		public bool Empty;
		public int MaxWidth;

		public ObAlertMenu()
        {
            Breakpoint = 0;
            Empty = false;
            MaxWidth = 300;
		}

		~ObAlertMenu()
        {
		}

	}//end ObAlertMenu

}//end namespace Application
