///////////////////////////////////////////////////////////
//  ObBrillianceMenu.cs
//  Implementation of the Class ObBrillianceMenu
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:28:26
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Application 
{
    public enum ObPaletteType
    {
        Day = 0,
        Dusk,
        Bright,
        Night
    }

	public class ObBrillianceMenu 
    {
		public int Brightness;
		public ObPaletteType Palette;
		public bool ShowAutoPalette;
		public bool ShowAutoBrightness;

		public ObBrillianceMenu()
        {
            Brightness = 100;
            Palette = ObPaletteType.Day;
            ShowAutoPalette = false;
            ShowAutoBrightness = false;
		}

		~ObBrillianceMenu()
        {
		}

	}//end ObBrillianceMenu

}//end namespace Application
