///////////////////////////////////////////////////////////
//  ObCardListButton.cs
//  Implementation of the Class ObCardListButton
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:28:38
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeApp.Components.Application 
{
	public class ObCardListButton 
    {
		public bool HasIconLeading;
		public bool HasIconTrailing;
		public string Label;
		public string LeadingIcon;
		public string TrailingIcon;

		public ObCardListButton()
        {
		}

		~ObCardListButton()
        {
		}

	}//end ObCardListButton

}//end namespace Application
