///////////////////////////////////////////////////////////
//  ObClock.cs
//  Implementation of the Class ObClock
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:28:51
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeApp.Components.Application 
{
	public class ObClock 
    {
		public int BlinkOnlyBraakpointPx;
		public string Date;
		public bool ShowDate;

		public ObClock()
        {
		}

		~ObClock()
        {
		}

	}//end ObClock

}//end namespace Application
