///////////////////////////////////////////////////////////
//  ObNotificationMessageItem.cs
//  Implementation of the Class ObNotificationMessageItem
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:29:22
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeApp.Components.Application 
{
	public class ObNotificationMessageItem 
    {

		public ObNotificationMessageItem()
        {
		}

		~ObNotificationMessageItem()
        {
		}

	}//end ObNotificationMessageItem

}//end namespace Application
