///////////////////////////////////////////////////////////
//  ObNotificationMessage.cs
//  Implementation of the Class ObNotificationMessage
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:29:03
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Application 
{
	public class ObNotificationMessage 
    {
		public bool Empty;
		public bool Large;

		public ObNotificationMessage()
        {
            Empty = false;
            Large = false;
		}

		~ObNotificationMessage()
        {
		}

	}//end ObNotificationMessage

}//end namespace Application
