///////////////////////////////////////////////////////////
//  ObTopBar.cs
//  Implementation of the Class ObTopBar
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:29:44
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Application 
{
	public class ObTopBar 
    {
		public int AppTitleBreakpointPx;
		public int AppsButtonBreakpointPx;
		public int ClockMinimizeBreakpointPx;
		public int DimmingButtonBreakpointPx;
		public bool MenuButtonActivated;
		public bool ShowAppsButton;
		public bool ShowClock;
		public bool ShowDate;
		public bool ShowDimmingButton;
		public bool WideMenuButton;

		public ObTopBar()
        {
		}

		~ObTopBar()
        {
		}

	}//end ObTopBar

}//end namespace Application
