// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SHUNTDATA_H)
#define __SHUNTDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class ShuntData : public ioDataCollection
{
public:
    ShuntData();
    virtual ~ShuntData();
    void InitializeData(void);
};
#endif // __SHUNTDATA_H
