// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ShuntData.h"
ShuntData::ShuntData()
{
    InitializeData();
}
ShuntData::~ShuntData()
{
}
void ShuntData::InitializeData(void)
{
    ResetItem();
}
