// !!! This C++ file is generated by ioStudio !!!
#if !defined(__MOTORSMODEL_H)
#define __MOTORSMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Power/Rotate/MotorsData.h"
class MotorsModel : public ioModel
{
public:
    MotorsModel();
    virtual ~MotorsModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    MotorsData DataModel;
};
#endif // __MOTORSMODEL_H
