// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "DiodeModel.h"
DiodeModel::DiodeModel()
{
}
DiodeModel::~DiodeModel()
{
}
// Initialize simulation model
void DiodeModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void DiodeModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
