// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchModel.h"
SwitchModel::SwitchModel()
{
}
SwitchModel::~SwitchModel()
{
}
// Initialize simulation model
void SwitchModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void SwitchModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
