// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CONSUMEMODELDATA_H)
#define __CONSUMEMODELDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class ConsumeModelData : public ioDataCollection
{
public:
    ConsumeModelData();
    virtual ~ConsumeModelData();
    void InitializeData(void);
    ioVarFloat PowerConsumer;
protected:
    ioData* m_ListData[1];
};
#endif // __CONSUMEMODELDATA_H
