// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ConsumeModelData.h"
ConsumeModelData::ConsumeModelData()
{
    InitializeData();
}
ConsumeModelData::~ConsumeModelData()
{
}
void ConsumeModelData::InitializeData(void)
{
    SetListData(m_ListData, 1);
    ResetItem();
    PowerConsumer.SetValue((Float)0.0);
    AddData((ioData*)&PowerConsumer, Duid_Ops_Consume_PowerConsumer);
}
