// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "JunctionData.h"
JunctionData::JunctionData()
{
    InitializeData();
}
JunctionData::~JunctionData()
{
}
void JunctionData::InitializeData(void)
{
    SetListData(m_ListData, 3);
    ResetItem();
    MaxFuseCurrent.SetValue((Float)0.15);
    AddData((ioData*)&MaxFuseCurrent, Duid_Ops_Consume_MaxFuseCurrent);
    IsFuseBlown.SetValue(FALSE);
    AddData((ioData*)&IsFuseBlown, Duid_Ops_Consume_IsFuseBlown);
    AddData((ioData*)&ResetFuse, Duid_Ops_Consume_ResetFuse);
}
