// !!! This C++ file is generated by ioStudio !!!
#if !defined(__JUNCTIONDATA_H)
#define __JUNCTIONDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioMethod.h"
class JunctionData : public ioDataCollection
{
public:
    JunctionData();
    virtual ~JunctionData();
    void InitializeData(void);
    ioVarFloat MaxFuseCurrent;
    ioVarBool IsFuseBlown;
    ioMethod ResetFuse;
protected:
    ioData* m_ListData[3];
};
#endif // __JUNCTIONDATA_H
