// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ConvDcDcData.h"
ConvDcDcData::ConvDcDcData()
{
    InitializeData();
}
ConvDcDcData::~ConvDcDcData()
{
}
void ConvDcDcData::InitializeData(void)
{
    SetListData(m_ListData, 6);
    ResetItem();
    VoltageInputDcDc.SetValue((Float)12.00);
    AddData((ioData*)&VoltageInputDcDc, Duid_Power_Convert_VoltageInputDcDc);
    VoltageOutputDcDc.SetValue((Float)24);
    AddData((ioData*)&VoltageOutputDcDc, Duid_Power_Convert_VoltageOutputDcDc);
    IsDcDcOutputActive.SetValue(TRUE);
    AddData((ioData*)&IsDcDcOutputActive, Duid_Power_Convert_IsDcDcOutputActive);
    MaxOutCurrentDcDc.SetValue((Float)20);
    AddData((ioData*)&MaxOutCurrentDcDc, Duid_Power_Convert_MaxOutCurrentDcDc);
    CurrentInputDcDc.SetValue((Float)0.0);
    AddData((ioData*)&CurrentInputDcDc, Duid_Power_Convert_CurrentInputDcDc);
    CurrentOutputDcDc.SetValue((Float)0.0);
    AddData((ioData*)&CurrentOutputDcDc, Duid_Power_Convert_CurrentOutputDcDc);
}
