///////////////////////////////////////////////////////////
//  ObAzimuthThruster.cs
//  Implementation of the Class ObAzimuthThruster
//  Generated by Enterprise Architect
//  Created on:      28-Feb-2024 20:15:27
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace OpenBridgeApp.NavigationInstruments 
{
	public class ObAzimuthThruster : ObThruster 
    {
		public int Angle;
		public int AngleSetpoint;
		public bool AtAngleSetpoint;
		public bool AtThrustSetpoint;
		public int Loading;
		public ObStateCommand State;
		public int Thrust;
		public int ThrustSetpoint;
		public bool ThrustSetpointAtZero;
		public int Width;

		public ObAzimuthThruster()
        {
            Angle = 0;
            AngleSetpoint = 0;
            AtAngleSetpoint = true;
            AtThrustSetpoint = true;
            Loading = 0;
            State = ObStateCommand.NotInCommand;
            Thrust = 0;
            ThrustSetpoint = 0;
            ThrustSetpointAtZero = true;
            Width = 300;
        }

		~ObAzimuthThruster()
        {
		}

	}//end ObAzimuthThruster

}//end namespace NavigationInstruments
