// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTDCPANEL_H)
#define __BATTDCPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class BattDcPanel : public ioPanel
{
public:
    BattDcPanel();
    virtual ~BattDcPanel();
    virtual void InitializeData(void);
    ioLabel LabelBatt;
    ioTextBlock InstrVolt;
    ioLabel LabelVolt;
    ioTextBlock InstrAmpAvg;
    ioLabel LabelAmpAvg;
    ioTextBlock InstrAmpDiff;
protected:
    ioGraphics* m_BattDcPanelGraphics[8];
};
#endif // __BATTDCPANEL_H
