// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTDCDATADC24_H)
#define __BATTDCDATADC24_H
#include "BattDcData.h"
class BattDcDataDc24 : public BattDcData
{
public:
    BattDcDataDc24();
    virtual ~BattDcDataDc24();
    virtual void InitializeData(void);
};
#endif // __BATTDCDATADC24_H
