// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWERNETMODEL_H)
#define __POWERNETMODEL_H
#include "ioSystem/Simulation/ioModel.h"
class PowerNetModel : public ioModel
{
public:
    PowerNetModel();
    virtual ~PowerNetModel();
    virtual void InitializeItem(void);
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
};
#endif // __POWERNETMODEL_H
