// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowerNetModel.h"
PowerNetModel::PowerNetModel()
{
}
PowerNetModel::~PowerNetModel()
{
}
void PowerNetModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void PowerNetModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
