// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ShuntModel.h"
ShuntModel::ShuntModel()
{
}
ShuntModel::~ShuntModel()
{
}
void ShuntModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void ShuntModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
