// !!! This C++ file is generated by ioStudio !!!
#if !defined(__INSTRUMENTDEPTH_H)
#define __INSTRUMENTDEPTH_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioUiComponent.h"
class InstrumentDepth : public ioPanel
{
public:
    InstrumentDepth();
    virtual ~InstrumentDepth();
    virtual void InitializeData(void);
    ioLabel LabeDptInstrHeader;
    ioLabel LabelDptInstrHeaderUnit;
    ioTextBlock InstrDptInstr;
    ioUiComponent CompDepth;
protected:
    ioGraphics* m_InstrumentDepthGraphics[4];
};
#endif // __INSTRUMENTDEPTH_H
