// !!! This C++ file is generated by ioStudio !!!
#if !defined(__ROUTEINSTRPANEL_H)
#define __ROUTEINSTRPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioIcon.h"
class RouteInstrPanel : public ioPanel
{
public:
    RouteInstrPanel();
    virtual ~RouteInstrPanel();
    virtual void InitializeData(void);
    ioLabel LabelBtwHeader;
    ioLabel LabelBtwHeaderUnit;
    ioLabel LabelXteHeader;
    ioLabel LabelXteHeaderUnit;
    ioLabel LabelCogHeader;
    ioLabel LabelCogHeaderUnit;
    ioLabel LabelSogHeader;
    ioLabel LabelSogHeaderUnit;
    ioTextBlock InstrBtw;
    ioIcon IconXteLeft;
    ioTextBlock InstrXte;
    ioIcon IconXteRight;
    ioTextBlock InstrCog;
    ioTextBlock InstrSog;
    ioLabel LabelEtaWptHeader;
    ioLabel LabelEtaWptHeaderUnit;
    ioLabel LabelEtaRteHeader;
    ioLabel LabelEtaRteHeaderUnit;
    ioLabel LabelTtgWpthHeader;
    ioLabel LabeDptlDepthHeader;
    ioLabel LabelDptHeaderUnit;
    ioTextBlock InstrEtaWptDate;
    ioTextBlock InstrEtaWptTime;
    ioTextBlock InstrEtaRteDate;
    ioTextBlock InstrEtaRteTime;
    ioTextBlock InstrTtgWpt;
    ioTextBlock InstrDpt;
protected:
    ioGraphics* m_RouteInstrPanelGraphics[27];
};
#endif // __ROUTEINSTRPANEL_H
