// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SelectRouteFlyout.h"
#include "Programs/ioSystemGraphics.h"
SelectRouteFlyout::SelectRouteFlyout()
{
}
SelectRouteFlyout::~SelectRouteFlyout()
{
}
void SelectRouteFlyout::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SelectRouteFlyoutGraphics, 7);
    AddGraphics(&LabelRteFolderHeader, Puid_Ids_Track_LabelRteFolderHeader);
    LabelRteFolderHeader.SetTextForced((ioChars)"RTE folder");
    AddGraphics(&RadioRteFolder, Puid_Ids_Track_RadioRteFolder);
    AddGraphics(&CmbRteFolder, Puid_Ids_Track_CmbRteFolder);
    AddGraphics(&LabelRteSourceHeader, Puid_Ids_Track_LabelRteSourceHeader);
    LabelRteSourceHeader.SetTextForced((ioChars)"RTE source");
    AddGraphics(&RadioRteSource, Puid_Ids_Track_RadioRteSource);
    AddGraphics(&CmbRteSource, Puid_Ids_Track_CmbRteSource);
    AddGraphics(&ButtonCancelRteSelect, Puid_Ids_Track_ButtonCancelRteSelect);
    ButtonCancelRteSelect.SetTextForced((ioChars)"Cancel");
}
