// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SELECTROUTEFLYOUT_H)
#define __SELECTROUTEFLYOUT_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioRadioButton.h"
#include "ioSystem/Panels/ioComboBox.h"
#include "ioSystem/Panels/ioButtonText.h"
class SelectRouteFlyout : public ioPanel
{
public:
    SelectRouteFlyout();
    virtual ~SelectRouteFlyout();
    virtual void InitializeData(void);
    ioLabel LabelRteFolderHeader;
    ioRadioButton RadioRteFolder;
    ioComboBox CmbRteFolder;
    ioLabel LabelRteSourceHeader;
    ioRadioButton RadioRteSource;
    ioComboBox CmbRteSource;
    ioButtonIcon ButtonCancelRteSelect;
protected:
    ioGraphics* m_SelectRouteFlyoutGraphics[7];
};
#endif // __SELECTROUTEFLYOUT_H
