// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SELECTWAYPOINTFLYOUT_H)
#define __SELECTWAYPOINTFLYOUT_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioComboBox.h"
#include "ioSystem/Panels/ioButtonText.h"
class SelectWaypointFlyout : public ioPanel
{
public:
    SelectWaypointFlyout();
    virtual ~SelectWaypointFlyout();
    virtual void InitializeData(void);
    ioLabel LabelWptSelectHeader;
    ioComboBox CmbWptSelect;
    ioButtonIcon ButtonPrevWpt;
    ioLabel LabelBtwSelectWptHeader;
    ioLabel LabelBtwSelectWptHeaderUnit;
    ioLabel LabelDtwSelectWptHeader;
    ioLabel LabelDtwSelectWptHeaderUnit;
    ioButtonIcon ButtonCancelWptSelect;
    ioButtonIcon ButtonNextWpt;
    ioTextBlock InstrBtwSelectWpt;
    ioTextBlock InstrDtwSelectWpt;
    ioButtonShape ButtonSetActiveWpt;
protected:
    ioGraphics* m_SelectWaypointFlyoutGraphics[12];
};
#endif // __SELECTWAYPOINTFLYOUT_H
