// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefTrackPanel.h"
#include "Programs/ioSystemGraphics.h"
SetRefTrackPanel::SetRefTrackPanel()
{
}
SetRefTrackPanel::~SetRefTrackPanel()
{
}
void SetRefTrackPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SetRefTrackPanelGraphics, 8);
    AddGraphics(&ButtSelectRoute, Puid_Ids_Track_ButtSelectRoute);
    AddGraphics(&LabelSelectedRteHeader, Puid_Ids_Track_LabelSelectedRteHeader);
    LabelSelectedRteHeader.SetTextForced((ioChars)"RTE");
    AddGraphics(&TextSelectedRte, Puid_Ids_Track_TextSelectedRte);
    TextSelectedRte.SetTextForced((ioChars)"Name of route");
    TextSelectedRte.SetDecimals(1);
    AddGraphics(&ButtSelectWaypoint, Puid_Ids_Track_ButtSelectWaypoint);
    AddGraphics(&ButtSelectWptPrev, Puid_Ids_Track_ButtSelectWptPrev);
    ButtSelectWptPrev.SetTextForced((ioChars)"Previous WPT");
    AddGraphics(&ButtSelectWptNext, Puid_Ids_Track_ButtSelectWptNext);
    ButtSelectWptNext.SetTextForced((ioChars)"Next WPT");
    AddGraphics(&LabelSelectedWptHeader, Puid_Ids_Track_LabelSelectedWptHeader);
    LabelSelectedWptHeader.SetTextForced((ioChars)"WPT");
    AddGraphics(&TextSelectedWpt, Puid_Ids_Track_TextSelectedWpt);
    TextSelectedWpt.SetTextForced((ioChars)"Name of waypoint");
    TextSelectedWpt.SetDecimals(1);
}
