// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefTrackPanelMode.h"
#include "Programs/ioSystemGraphics.h"
SetRefTrackPanelMode::SetRefTrackPanelMode()
{
}
SetRefTrackPanelMode::~SetRefTrackPanelMode()
{
}
void SetRefTrackPanelMode::InitializeData(void)
{
}
