// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFTRACKPANEL_H)
#define __SETREFTRACKPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioButtonTextFlyout.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioButtonText.h"
class SetRefTrackPanel : public ioPanel
{
public:
    SetRefTrackPanel();
    virtual ~SetRefTrackPanel();
    virtual void InitializeData(void);
    ioButtonTextFlyout ButtSelectRoute;
    ioLabel LabelSelectedRteHeader;
    ioTextBlock TextSelectedRte;
    ioButtonTextFlyout ButtSelectWaypoint;
    ioButtonText ButtSelectWptPrev;
    ioButtonText ButtSelectWptNext;
    ioLabel LabelSelectedWptHeader;
    ioTextBlock TextSelectedWpt;
protected:
    ioGraphics* m_SetRefTrackPanelGraphics[8];
};
#endif // __SETREFTRACKPANEL_H
