// !!! This C++ file is generated by ioStudio !!!
#if !defined(__TRACKPLOTPANEL_H)
#define __TRACKPLOTPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class TrackPlotPanel : public ioPanel
{
public:
    TrackPlotPanel();
    virtual ~TrackPlotPanel();
    virtual void InitializeData(void);
    ioLabel LabelBtwPlotHeader;
    ioLabel LabelBtwPlotHeaderUnit;
    ioTextBlock InstrBtwPlot;
    ioLabel LabelTtwPlotHeader;
    ioLabel LabelTtwPlotHeaderUnit;
    ioTextBlock InstrTtwPlot;
    ioLabel LabelCogPlotHeader;
    ioLabel LabelCogPlotHeaderUnit;
    ioTextBlock InstrCogPlot;
    ioLabel LabelDptPlotHeader;
    ioLabel LabelDptPlotHeaderUnit;
    ioTextBlock InstrDptPlot;
    ioLabel LabelXtePlotHeader;
    ioLabel LabelXtePlotHeaderUnit;
    ioTextBlock InstrXtePlot;
    ioLabel LabelSogPlotHeader;
    ioLabel LabelSogPlotHeaderUnit;
    ioTextBlock InstrSogPlot;
protected:
    ioGraphics* m_TrackPlotPanelGraphics[18];
};
#endif // __TRACKPLOTPANEL_H
