// !!! This file is generated by ioStudio !!!
// Generation date and time: 12.FEB.2024 15:16:38
#if !defined(__BATTDCDATA_H)
#define __BATTDCDATA_H
#include "ioSystem/Data/ioDataCollectionDynamic.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class BattDcData : public ioDataCollectionDynamic
{
public:
    BattDcData();
    virtual ~BattDcData();
    virtual void InitializeData(void);
    ioVarFloat BattVolt;
    ioVarFloat BattAmpOut;
    ioVarFloat BattAmpIn;
    ioVarFloat BattAmpAvg;
protected:
    ioData* m_ListData[4];
};
#endif // __BATTDCDATA_H
