// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattDcDataDc24.h"
BattDcDataDc24::BattDcDataDc24()
{
    InitializeData();
}
BattDcDataDc24::~BattDcDataDc24()
{
}
void BattDcDataDc24::InitializeData(void)
{
    BattDcData::InitializeData();
    BattVolt.SetValue((Float)24);
    AddData((ioData*)&BattVolt, Duid_Batt_Dc24_BattVolt);
    BattAmpM.SetValue((Float)0);
    AddData((ioData*)&BattAmpM, Duid_Batt_Dc24_BattAmpM);
    BattAmpF.SetValue((Float)0);
    AddData((ioData*)&BattAmpF, Duid_Batt_Dc24_BattAmpF);
    BattAmpA.SetValue((Float)0.0);
    AddData((ioData*)&BattAmpA, Duid_Batt_Dc24_BattAmpA);
    BattAmpOut.SetValue((Float)0);
    AddData((ioData*)&BattAmpOut, Duid_Batt_Dc24_BattAmpOut);
    BattAmpIn.SetValue((Float)0);
    AddData((ioData*)&BattAmpIn, Duid_Batt_Dc24_BattAmpIn);
    BattAmpAvg.SetValue((Float)0.00);
    AddData((ioData*)&BattAmpAvg, Duid_Batt_Dc24_BattAmpAvg);
    IsChargeActive.SetValue(FALSE);
    AddData((ioData*)&IsChargeActive, Duid_Batt_Dc24_IsChargeActive);
    AddData((ioData*)&ResponseDcData, Duid_Batt_Dc24_ResponseDcData);
    BattSoc.SetValue((Float)99.9);
    AddData((ioData*)&BattSoc, Duid_Batt_Dc24_BattSoc);
}
