// !!! This file is generated by ioStudio !!!
// Generation date and time: 12.FEB.2024 15:16:38
#if !defined(__BATTDCDATADC12_H)
#define __BATTDCDATADC12_H
#include "BattDcData.h"
class BattDcDataDc12 : public BattDcData
{
public:
    BattDcDataDc12();
    virtual ~BattDcDataDc12();
    virtual void InitializeData(void);
};
#endif // __BATTDCDATADC12_H
