// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattDcData.h"
BattDcData::BattDcData()
{
}
BattDcData::~BattDcData()
{
}
void BattDcData::InitializeData(void)
{
    SetListData(m_ListData, 6);
    ResetItem();
    ResponseDcData.SetVariablesBuffer(m_ResponseDcDataVars, 2);
    ResponseDcData.AddVariable(&BattVolt);
    ResponseDcData.AddVariable(&BattAmpAvg);
}
