// !!! This file is generated by ioStudio !!!
// Generation date and time: 30.JAN.2024 14:59:31
#include "pch.h"
#pragma hdrstop
#include "BattDcDataDc24.h"
BattDcDataDc24::BattDcDataDc24()
{
    InitializeData();
}
BattDcDataDc24::~BattDcDataDc24()
{
}
void BattDcDataDc24::InitializeData(void)
{
    BattDcData::InitializeData();
    BattVolt.SetValue((Float)24);
    AddData((ioData*)&BattVolt, Duid_Batt_Dc24_BattVolt);
    BattAmpOut.SetValue((Float)0);
    AddData((ioData*)&BattAmpOut, Duid_Batt_Dc24_BattAmpOut);
    BattAmpIn.SetValue((Float)0);
    AddData((ioData*)&BattAmpIn, Duid_Batt_Dc24_BattAmpIn);
}
