// !!! This file is generated by ioStudio !!!
// Generation date and time: 21.FEB.2024 06:09:22
#if !defined(__BATTDCDATADC24_H)
#define __BATTDCDATADC24_H
#include "BattDcData.h"
class BattDcDataDc24 : public BattDcData
{
public:
    BattDcDataDc24();
    virtual ~BattDcDataDc24();
    virtual void InitializeData(void);
};
#endif // __BATTDCDATADC24_H
