// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattDcDataDc12.h"
BattDcDataDc12::BattDcDataDc12()
{
    InitializeData();
}
BattDcDataDc12::~BattDcDataDc12()
{
}
void BattDcDataDc12::InitializeData(void)
{
    BattDcData::InitializeData();
    BattVolt.SetValue((Float)12.00);
    AddData((ioData*)&BattVolt, Duid_Batt_Dc12_BattVolt);
    BattAmpOut.SetValue((Float)0);
    AddData((ioData*)&BattAmpOut, Duid_Batt_Dc12_BattAmpOut);
    BattAmpIn.SetValue((Float)0);
    AddData((ioData*)&BattAmpIn, Duid_Batt_Dc12_BattAmpIn);
    BattAmpAvg.SetValue((Float)0);
    AddData((ioData*)&BattAmpAvg, Duid_Batt_Dc12_BattAmpAvg);
    AddData((ioData*)&RequestDcData, Duid_Batt_Dc12_RequestDcData);
    AddData((ioData*)&ResponseDcData, Duid_Batt_Dc12_ResponseDcData);
}
