// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTDCDATA_H)
#define __BATTDCDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioEnumeration.h"
#include "ioSystem/Data/ioEvent.h"
class TypeDcBatt : public ioEnumeration
{
public:
    TypeDcBatt();
    virtual ~TypeDcBatt();
    virtual Bool GetActiveText(ioString* enumText);
    static const Int32 DC12V = 0;
    static const Int32 DC24V = 1;
};
class BattDcData : public ioDataCollection
{
public:
    BattDcData();
    virtual ~BattDcData();
    virtual void InitializeData(void);
    ioVarFloat BattVolt;
    ioVarFloat BattAmpM;
    ioVarFloat BattAmpF;
    ioVarFloat BattAmpA;
    ioVarFloat BattAmpOut;
    ioVarFloat BattAmpIn;
    ioVarFloat BattAmpAvg;
    ioVarBool IsChargeActive;
    ioEvent ResponseDcData;
    ioVarFloat BattSoc;
protected:
    ioData* m_ListData[10];
    ioVar* m_ResponseDcDataVars[3];
};
#endif // __BATTDCDATA_H
