// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTDCPANELDC24_H)
#define __BATTDCPANELDC24_H
#include "BattDcPanel.h"
class BattDcPanelDc24 : public BattDcPanel
{
public:
    BattDcPanelDc24();
    virtual ~BattDcPanelDc24();
    virtual void InitializeData(void);
};
#endif // __BATTDCPANELDC24_H
