// !!! This file is generated by ioStudio !!!
// Generation date and time: 30.JAN.2024 12:18:43
#include "pch.h"
#pragma hdrstop
#include "BattDcPanel.h"
BattDcPanel::BattDcPanel()
{
}
BattDcPanel::~BattDcPanel()
{
}
void BattDcPanel::InitializeData(void)
{
}
