// !!! This file is generated by ioStudio !!!
// Generation date and time: 30.JAN.2024 14:59:31
#if !defined(__BATTDCDATADC12_H)
#define __BATTDCDATADC12_H
#include "BattDcData.h"
class BattDcDataDc12 : public BattDcData
{
public:
    BattDcDataDc12();
    virtual ~BattDcDataDc12();
    virtual void InitializeData(void);
};
#endif // BATTDCDATADC12_H
