// !!! This file is generated by ioStudio !!!
// Generation date and time: 30.JAN.2024 14:59:31
#include "pch.h"
#pragma hdrstop
#include "BattDcData.h"
BattDcData::BattDcData()
{
}
BattDcData::~BattDcData()
{
}
void BattDcData::InitializeData(void)
{
    SetListData(m_ListData, 3);
    ResetItem();
}
