// !!! This file is generated by ioStudio !!!
// Generation date and time: 21.FEB.2024 06:09:22
#include "pch.h"
#pragma hdrstop
#include "BattDcData.h"
BattDcData::BattDcData()
{
}
BattDcData::~BattDcData()
{
}
void BattDcData::InitializeData(void)
{
    SetListData(m_ListData, 6);
    ResetItem();
}
