// !!! This file is generated by ioStudio !!!
// Generation date and time: 30.JAN.2024 12:18:43
#if !defined(__BATTDCPANEL_H)
#define __BATTDCPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class BattDcPanel : public ioPanel
{
public:
    BattDcPanel();
    virtual ~BattDcPanel();
    virtual void InitializeData(void);
    ioLabel LabelBatt;
    ioTextBlock InstrVolt;
    ioLabel LabelVolt;
    ioTextBlock InstrAmpAvg;
    ioLabel LabelAmpAvg;
    ioTextBlock InstrAmpDiff;
};
#endif // BATTDCPANEL_H
