// !!! This file is generated by ioStudio !!!
// Generation date and time: 30.JAN.2024 12:18:43
#if !defined(__BATTDCPANELDC24_H)
#define __BATTDCPANELDC24_H
#include "BattDcPanel.h"
class BattDcPanelDc24 : public BattDcPanel
{
public:
    BattDcPanelDc24();
    virtual ~BattDcPanelDc24();
    virtual void InitializeData(void);
};
#endif // BATTDCPANELDC24_H
