// !!! This file is generated by ioStudio !!!
#if !defined(__STEERAP1PANEL_H)
#define __STEERAP1PANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioShape.h"
#include "ioSystem/Panels/ioUiComponent.h"
class SteerAp1Panel : public ioPanel
{
public:
    SteerAp1Panel();
    virtual ~SteerAp1Panel();
    void InitializeData(void);
    ioLabel LabelApSteer;
    ioTextBlock InstrHeadingRef;
    ioLabel LabelHeading;
    ioTextBlock InstrHeading;
    ioShape ShapeContourShip;
    ioUiComponent CompThruster;
    ioUiComponent CompRudder;
    ioUiComponent CompRateOfTurn;
    ioUiComponent CompEngine;
    ioTextBlock TextRotValue;
    ioLabel LabelRot;
    ioTextBlock TextEngineValue;
    ioLabel LabelEngine;
    ioTextBlock TextThrustValue;
    ioLabel LabelThrust;
};
#endif // __STEERAP1PANEL_H
