// !!! This file is generated by ioStudio !!!
// Generation date and time: 30.JAN.2024 15:01:38
#include "pch.h"
#pragma hdrstop
#include "SteerAp1Data.h"
SteerAp1Data::SteerAp1Data()
{
    InitializeData();
}
SteerAp1Data::~SteerAp1Data()
{
}
void SteerAp1Data::InitializeData(void)
{
    SetListData(m_ListData, 4);
    ResetItem();
    MeasRudderAngle.SetValue((Float)0.0);
    AddData((ioData*)&MeasRudderAngle, Duid_Steer_Ap1_MeasRudderAngle);
    MeasThrust.SetValue((Float)0.0);
    AddData((ioData*)&MeasThrust, Duid_Steer_Ap1_MeasThrust);
    MeasRateOfTurn.SetValue((Float)0.0);
    AddData((ioData*)&MeasRateOfTurn, Duid_Steer_Ap1_MeasRateOfTurn);
    MeasHeading.SetValue((Float)0.00);
    AddData((ioData*)&MeasHeading, Duid_Steer_Ap1_MeasHeading);
}
