// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerAp1Panel.h"
SteerAp1Panel::SteerAp1Panel()
{
    InitializeData();
}
SteerAp1Panel::~SteerAp1Panel()
{
}
void SteerAp1Panel::InitializeData(void)
{
}
