// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "NetBatteryModel.h"
NetBatteryModel::NetBatteryModel()
{
}
NetBatteryModel::~NetBatteryModel()
{
}
// Initialize simulation model
void NetBatteryModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void NetBatteryModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
