// !!! This C++ file is generated by ioStudio !!!
#if !defined(__NETBATTERYMODEL_H)
#define __NETBATTERYMODEL_H
#include "ioSystem/Simulation/ioModel.h"
class NetBatteryModel : public ioModel
{
public:
    NetBatteryModel();
    virtual ~NetBatteryModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
};
#endif // __NETBATTERYMODEL_H
