// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "NetModbusModel.h"
NetModbusModel::NetModbusModel()
{
}
NetModbusModel::~NetModbusModel()
{
}
// Initialize simulation model
void NetModbusModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void NetModbusModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
