// !!! This C++ file is generated by ioStudio !!!
#if !defined(__NETMODBUSMODEL_H)
#define __NETMODBUSMODEL_H
#include "ioSystem/Simulation/ioModel.h"
class NetModbusModel : public ioModel
{
public:
    NetModbusModel();
    virtual ~NetModbusModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
};
#endif // __NETMODBUSMODEL_H
