// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowerNetModel.h"
PowerNetModel::PowerNetModel()
{
}
PowerNetModel::~PowerNetModel()
{
}
// Initialize simulation model
void PowerNetModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void PowerNetModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
