///////////////////////////////////////////////////////////
//  ObNavigationItem.cs
//  Implementation of the Class ObNavigationItem
//  Generated by Enterprise Architect
//  Created on:      27-Feb-2024 17:44:41
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeApp.Components.Menu 
{
	public class ObNavigationItem 
    {
		public bool Checked;
		public string Label;

		public ObNavigationItem()
        {
		}

		~ObNavigationItem()
        {
		}

	}//end ObNavigationItem

}//end namespace Menu
