///////////////////////////////////////////////////////////
//  ObNavigationMenu.cs
//  Implementation of the Class ObNavigationMenu
//  Generated by Enterprise Architect
//  Created on:      27-Feb-2024 17:44:16
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Menu 
{
	public class ObNavigationMenu 
    {
        List<ObNavigationItem> m_Items;

		public ObNavigationMenu()
        {
            m_Items = new List<ObNavigationItem>();
        }

		~ObNavigationMenu()
        {
		}

	}//end ObNavigationMenu

}//end namespace Menu
