// !!! This C++ file is generated by ioStudio !!!
#if !defined(__IDSPROGOPERATEM_H)
#define __IDSPROGOPERATEM_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "ioSystem/Ports/System/ioPortProgramSystem.h"
class IdsProgOperateM : public ioProgram
{
public:
    IdsProgOperateM();
    virtual ~IdsProgOperateM();
    virtual void Run(Int32 activeSlot);
    virtual void RunOperateM(void);
    ioPortProgramSystem PortSystem;
};
#endif // __IDSPROGOPERATEM_H
