// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "IdsProgOperateA.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
IdsProgOperateA::IdsProgOperateA()
{
}
IdsProgOperateA::~IdsProgOperateA()
{
}
void IdsProgOperateA::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
    RunOperateA();
}
void IdsProgOperateA::RunOperateA(void)
{
}
