// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "IdsProgControl.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
IdsProgControl::IdsProgControl()
{
}
IdsProgControl::~IdsProgControl()
{
}
void IdsProgControl::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
    RunControl();
}
void IdsProgControl::RunControl(void)
{
}
