// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BatteryData.h"
BatteryData::BatteryData()
{
    InitializeData();
}
BatteryData::~BatteryData()
{
}
void BatteryData::InitializeData(void)
{
    SetListData(m_ListData, 5);
    ResetItem();
    BatteryChargeResistance.SetValue((Float)0.15);
    AddData((ioData*)&BatteryChargeResistance, Duid_Power_Source_BatteryChargeResistance);
    BatteryEnergy.SetValue((Float)300);
    AddData((ioData*)&BatteryEnergy, Duid_Power_Source_BatteryEnergy);
    VoltageBattery.SetValue((Float)12.00);
    AddData((ioData*)&VoltageBattery, Duid_Power_Source_VoltageBattery);
    CurrentBattery.SetValue((Float)0.00);
    AddData((ioData*)&CurrentBattery, Duid_Power_Source_CurrentBattery);
    StatusOfCharge.SetValue((Float)0.0);
    AddData((ioData*)&StatusOfCharge, Duid_Power_Source_StatusOfCharge);
}
