// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTERYDATA_H)
#define __BATTERYDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class BatteryData : public ioDataCollection
{
public:
    BatteryData();
    virtual ~BatteryData();
    void InitializeData(void);
    ioVarFloat BatteryChargeResistance;
    ioVarFloat BatteryEnergy;
    ioVarFloat VoltageBattery;
    ioVarFloat CurrentBattery;
    ioVarFloat StatusOfCharge;
protected:
    ioData* m_ListData[5];
};
#endif // __BATTERYDATA_H
