// !!! This C++ file is generated by ioStudio !!!
#if !defined(__GENERATORDATA_H)
#define __GENERATORDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class GeneratorData : public ioDataCollection
{
public:
    GeneratorData();
    virtual ~GeneratorData();
    void InitializeData(void);
    ioVarFloat VoltOutputGenerator;
    ioVarBool IsGeneratorOutputActive;
    ioVarFloat MaxOutCurrentGenerator;
    ioVarFloat CurrentGenerator;
protected:
    ioData* m_ListData[4];
};
#endif // __GENERATORDATA_H
