// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "GeneratorData.h"
GeneratorData::GeneratorData()
{
    InitializeData();
}
GeneratorData::~GeneratorData()
{
}
void GeneratorData::InitializeData(void)
{
    SetListData(m_ListData, 4);
    ResetItem();
    VoltOutputGenerator.SetValue((Float)12);
    AddData((ioData*)&VoltOutputGenerator, Duid_Power_Source_VoltOutputGenerator);
    IsGeneratorOutputActive.SetValue(TRUE);
    AddData((ioData*)&IsGeneratorOutputActive, Duid_Power_Source_IsGeneratorOutputActive);
    MaxOutCurrentGenerator.SetValue((Float)0.0);
    AddData((ioData*)&MaxOutCurrentGenerator, Duid_Power_Source_MaxOutCurrentGenerator);
    CurrentGenerator.SetValue((Float)0.0);
    AddData((ioData*)&CurrentGenerator, Duid_Power_Source_CurrentGenerator);
}
