// !!! This C++ file is generated by ioStudio !!!
#if !defined(__VICTRONPANEL_H)
#define __VICTRONPANEL_H
#include "ioSystem/Panels/ioPanel.h"
class VictronPanel : public ioPanel
{
public:
    VictronPanel();
    virtual ~VictronPanel();
    virtual void InitializeData(void);
};
#endif // __VICTRONPANEL_H
