// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "VictronMonitor.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
VictronMonitor::VictronMonitor()
{
}
VictronMonitor::~VictronMonitor()
{
}
void VictronMonitor::InitializeTask(void)
{
    ioProgram::InitializeTask();
    AddPanel((ioPanel*)&MainPanel);
}
