// !!! This C++ file is generated by ioStudio !!!
#if !defined(__DIODEDATA_H)
#define __DIODEDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class DiodeData : public ioDataCollection
{
public:
    DiodeData();
    virtual ~DiodeData();
    void InitializeData(void);
};
#endif // __DIODEDATA_H
