// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SWITCHDCDATA_H)
#define __SWITCHDCDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioMethod.h"
class SwitchDcData : public ioDataCollection
{
public:
    SwitchDcData();
    virtual ~SwitchDcData();
    void InitializeData(void);
    ioVarFloat MaxFuseCurrent;
    ioVarBool IsFuseBlown;
    ioMethod ResetFuse;
protected:
    ioData* m_ListData[3];
};
#endif // __SWITCHDCDATA_H
