// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchAcData.h"
SwitchAcData::SwitchAcData()
{
    InitializeData();
}
SwitchAcData::~SwitchAcData()
{
}
void SwitchAcData::InitializeData(void)
{
    ResetItem();
}
