// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchDcData.h"
SwitchDcData::SwitchDcData()
{
    InitializeData();
}
SwitchDcData::~SwitchDcData()
{
}
void SwitchDcData::InitializeData(void)
{
    SetListData(m_ListData, 3);
    ResetItem();
    MaxFuseCurrent.SetValue((Float)20);
    AddData((ioData*)&MaxFuseCurrent, Duid_Power_Isolate_MaxFuseCurrent);
    IsFuseBlown.SetValue(FALSE);
    AddData((ioData*)&IsFuseBlown, Duid_Power_Isolate_IsFuseBlown);
    AddData((ioData*)&ResetFuse, Duid_Power_Isolate_ResetFuse);
}
