// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SWITCHACDATA_H)
#define __SWITCHACDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class SwitchAcData : public ioDataCollection
{
public:
    SwitchAcData();
    virtual ~SwitchAcData();
    void InitializeData(void);
};
#endif // __SWITCHACDATA_H
