// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchDcData.h"
SwitchDcData::SwitchDcData()
{
}
SwitchDcData::~SwitchDcData()
{
}
void SwitchDcData::InitializeData(void)
{
    SetListData(m_ListData, 3);
    ResetItem();
}
