// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SWITCHDCDATABATTERY_H)
#define __SWITCHDCDATABATTERY_H
#include "SwitchDcData.h"
class SwitchDcDataBattery : public SwitchDcData
{
public:
    SwitchDcDataBattery();
    virtual ~SwitchDcDataBattery();
    virtual void InitializeData(void);
};
#endif // __SWITCHDCDATABATTERY_H
