// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SWITCHDCDATAINVERTER_H)
#define __SWITCHDCDATAINVERTER_H
#include "SwitchDcData.h"
class SwitchDcDataInverter : public SwitchDcData
{
public:
    SwitchDcDataInverter();
    virtual ~SwitchDcDataInverter();
    virtual void InitializeData(void);
};
#endif // __SWITCHDCDATAINVERTER_H
