// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchDcDataBattery.h"
SwitchDcDataBattery::SwitchDcDataBattery()
{
    InitializeData();
}
SwitchDcDataBattery::~SwitchDcDataBattery()
{
}
void SwitchDcDataBattery::InitializeData(void)
{
    SwitchDcData::InitializeData();
    MaxFuseCurrent.SetValue((Float)20);
    AddData((ioData*)&MaxFuseCurrent, Duid_Power_Isolate_Battery_MaxFuseCurrent);
    IsFuseBlown.SetValue(FALSE);
    AddData((ioData*)&IsFuseBlown, Duid_Power_Isolate_Battery_IsFuseBlown);
    AddData((ioData*)&ResetFuse, Duid_Power_Isolate_Battery_ResetFuse);
}
