// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchDcDataInverter.h"
SwitchDcDataInverter::SwitchDcDataInverter()
{
    InitializeData();
}
SwitchDcDataInverter::~SwitchDcDataInverter()
{
}
void SwitchDcDataInverter::InitializeData(void)
{
    SwitchDcData::InitializeData();
    MaxFuseCurrent.SetValue((Float)20);
    AddData((ioData*)&MaxFuseCurrent, Duid_Power_Isolate_Inverter_MaxFuseCurrent);
    IsFuseBlown.SetValue(FALSE);
    AddData((ioData*)&IsFuseBlown, Duid_Power_Isolate_Inverter_IsFuseBlown);
    AddData((ioData*)&ResetFuse, Duid_Power_Isolate_Inverter_ResetFuse);
}
