// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PanelDcDc.h"
#include "Programs/ioSystemGraphics.h"
PanelDcDc::PanelDcDc()
{
}
PanelDcDc::~PanelDcDc()
{
}
void PanelDcDc::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_PanelDcDcGraphics, 5);
    AddGraphics(&SelectDcDc, Puid_Victron_DcDc_PanelDcDc_SelectDcDc);
    AddGraphics(&LabelHeaderDcDcInput, Puid_Victron_DcDc_LabelHeaderDcDcInput);
    LabelHeaderDcDcInput.SetTextForced((ioChars)"DC-DC INPUT [VDC]");
    AddGraphics(&LabelHeaderDcDcOutput, Puid_Victron_DcDc_LabelHeaderDcDcOutput);
    LabelHeaderDcDcOutput.SetTextForced((ioChars)"DC-DC OUTPUT [VDC]");
    AddGraphics(&InstrVoltInput, Puid_Victron_DcDc_InstrVoltInput);
    InstrVoltInput.SetTextForced((ioChars)"12.1");
    InstrVoltInput.SetDecimals(1);
    AddGraphics(&InstVoltOutput, Puid_Victron_DcDc_InstVoltOutput);
    InstVoltOutput.SetTextForced((ioChars)"24.2");
    InstVoltOutput.SetDecimals(1);
}
