// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "IdsProgControl.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
IdsProgControl::IdsProgControl()
{
}
IdsProgControl::~IdsProgControl()
{
}
void IdsProgControl::InitializeTask(void)
{
    ioProgram::InitializeTask();
}
