// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "IdsProgOperate.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
IdsProgOperate::IdsProgOperate()
{
}
IdsProgOperate::~IdsProgOperate()
{
}
void IdsProgOperate::InitializeTask(void)
{
    ioProgram::InitializeTask();
}
void IdsProgOperate::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
