// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "IdsPowerOperate.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
#include "Programs/ioSystemData.h"
IdsPowerOperate::IdsPowerOperate()
{
}
IdsPowerOperate::~IdsPowerOperate()
{
}
// Initialize program attributes and operations
void IdsPowerOperate::InitializeTask(void)
{
    ioProgram::InitializeTask();
}
// Receive data in program from the network (listData: List containing the data, data: Data received)
void IdsPowerOperate::ReceiveData(ioDataCollection* listData, ioData* data)
{
    if (listData == NULL) {}
    if (data == NULL) {}
}
// Read from inputs before running program tasks (activeSlot: Task slot ID)
void IdsPowerOperate::ReadInput(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
// Run program tasks at regular intervals (activeSlot: Task slot ID)
void IdsPowerOperate::RunTask(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
// Write to outputs after running program tasks (activeSlot: Task slot ID)
void IdsPowerOperate::WriteOutput(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
// Map system data ID to network data ID for given protocol (protocol: Type of protocol for the data, dataID: Unique ID value for the system data, returns: Unique ID value for the network data)
Int32 IdsPowerOperate::MapSystemDataIDToNetworkID(ioPortProgramProtocol protocol, Int32 dataID)
{
    return ioProgram::MapSystemDataIDToNetworkID(protocol, dataID);
}
