///////////////////////////////////////////////////////////
//  ObDivider.cs
//  Implementation of the Class ObDivider
//  Generated by Enterprise Architect
//  Created on:      26-Feb-2024 20:50:55
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeAppLib.Components.Core 
{
	public class ObDivider 
    {
		public ObDivider()
        {
		}

		~ObDivider()
        {
		}

	}//end ObDivider

}//end namespace Core
