// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CONSUMERDATA_H)
#define __CONSUMERDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class ConsumerData : public ioDataCollection
{
public:
    ConsumerData();
    virtual ~ConsumerData();
    void InitializeData(void);
    ioVarBool IsOutputOn;
protected:
    ioData* m_ListData[1];
};
#endif // __CONSUMERDATA_H
