// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CONSUMERMODELDATA_H)
#define __CONSUMERMODELDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class ConsumerModelData : public ioDataCollection
{
public:
    ConsumerModelData();
    virtual ~ConsumerModelData();
    void InitializeData(void);
    ioVarFloat PowerConsumer;
protected:
    ioData* m_ListData[1];
};
#endif // __CONSUMERMODELDATA_H
