// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWCOMMANDPANEL_H)
#define __POWCOMMANDPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioShape.h"
#include "ioSystem/Panels/ioButtonText.h"
class PowCommandPanel : public ioPanel
{
public:
    PowCommandPanel();
    virtual ~PowCommandPanel();
    virtual void InitializeData(void);
    ioLabel HeaderCommandPanelPow;
    ioShape ShapeCommandStatusPow;
    ioLabel LabelPowerMode;
    ioTextBlock TextCommandStatusPow;
    ioButtonShape ButtTakeRequestPow;
    ioButtonShape ButtReleasePow;
protected:
    ioGraphics* m_PowCommandPanelGraphics[6];
};
#endif // __POWCOMMANDPANEL_H
