// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWCOMMANDMODEPANEL_H)
#define __POWCOMMANDMODEPANEL_H
#include "ioSystem/Panels/ioPanel.h"
class PowCommandModePanel : public ioPanel
{
public:
    PowCommandModePanel();
    virtual ~PowCommandModePanel();
    virtual void InitializeData(void);
};
#endif // __POWCOMMANDMODEPANEL_H
