// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowCommandModePanel.h"
#include "Programs/ioSystemGraphics.h"
PowCommandModePanel::PowCommandModePanel()
{
}
PowCommandModePanel::~PowCommandModePanel()
{
}
void PowCommandModePanel::InitializeData(void)
{
}
