// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowIndicatorPanel.h"
#include "Programs/ioSystemGraphics.h"
PowIndicatorPanel::PowIndicatorPanel()
{
}
PowIndicatorPanel::~PowIndicatorPanel()
{
}
void PowIndicatorPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_PowIndicatorPanelGraphics, 16);
    AddGraphics(&ShpOnOffInd1, Puid_Ids_Consume_ShpOnOffInd1);
    AddGraphics(&LabelNameInd1, Puid_Ids_Consume_LabelNameInd1);
    LabelNameInd1.SetTextForced((ioChars)"NamePowerOutput1");
    AddGraphics(&ShpOnOffInd2, Puid_Ids_Consume_ShpOnOffInd2);
    AddGraphics(&LabelNameInd2, Puid_Ids_Consume_LabelNameInd2);
    LabelNameInd2.SetTextForced((ioChars)"NamePowerOutput2");
    AddGraphics(&ShpOnOffInd3, Puid_Ids_Consume_ShpOnOffInd3);
    AddGraphics(&LabelNameInd3, Puid_Ids_Consume_LabelNameInd3);
    LabelNameInd3.SetTextForced((ioChars)"NamePowerOutput3");
    AddGraphics(&ShpOnOffInd4, Puid_Ids_Consume_ShpOnOffInd4);
    AddGraphics(&LabelNameInd4, Puid_Ids_Consume_LabelNameInd4);
    LabelNameInd4.SetTextForced((ioChars)"NamePowerOutput4");
    AddGraphics(&ShpOnOffInd5, Puid_Ids_Consume_ShpOnOffInd5);
    AddGraphics(&LabelNameInd5, Puid_Ids_Consume_LabelNameInd5);
    LabelNameInd5.SetTextForced((ioChars)"NamePowerOutput5");
    AddGraphics(&ShpOnOffInd6, Puid_Ids_Consume_ShpOnOffInd6);
    AddGraphics(&LabelNameInd6, Puid_Ids_Consume_LabelNameInd6);
    LabelNameInd6.SetTextForced((ioChars)"NamePowerOutput6");
    AddGraphics(&ShpOnOffInd7, Puid_Ids_Consume_ShpOnOffInd7);
    AddGraphics(&LabelNameInd7, Puid_Ids_Consume_LabelNameInd7);
    LabelNameInd7.SetTextForced((ioChars)"NamePowerOutput7");
    AddGraphics(&ShpOnOffInd8, Puid_Ids_Consume_ShpOnOffInd8);
    AddGraphics(&LabelNameInd8, Puid_Ids_Consume_LabelNameInd8);
    LabelNameInd8.SetTextForced((ioChars)"NamePowerOutput8");
}
