// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWMODEPANEL_H)
#define __POWMODEPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioButtonText.h"
class PowModePanel : public ioPanel
{
public:
    PowModePanel();
    virtual ~PowModePanel();
    virtual void InitializeData(void);
    ioButtonText ButtDockIdle;
    ioButtonText ButtDockConnectedShore;
    ioButtonText ButtDockNotConnected;
    ioButtonText ButtInTransit;
    ioButtonText ButtInTransitEngine;
    ioButtonText ButtInTransitSailing;
protected:
    ioGraphics* m_PowModePanelGraphics[6];
};
#endif // __POWMODEPANEL_H
