// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchboardData.h"
SwitchboardData::SwitchboardData()
{
    InitializeData();
}
SwitchboardData::~SwitchboardData()
{
}
void SwitchboardData::InitializeData(void)
{
    SetListData(m_ListData, 8);
    ResetItem();
    IsOutputOn1.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn1, Duid_Ids_Consume_IsOutputOn1);
    IsOutputOn2.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn2, Duid_Ids_Consume_IsOutputOn2);
    IsOutputOn3.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn3, Duid_Ids_Consume_IsOutputOn3);
    IsOutputOn4.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn4, Duid_Ids_Consume_IsOutputOn4);
    IsOutputOn5.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn5, Duid_Ids_Consume_IsOutputOn5);
    IsOutputOn6.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn6, Duid_Ids_Consume_IsOutputOn6);
    IsOutputOn7.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn7, Duid_Ids_Consume_IsOutputOn7);
    IsOutputOn8.SetValue(FALSE);
    AddData((ioData*)&IsOutputOn8, Duid_Ids_Consume_IsOutputOn8);
}
