// !!! This C++ file is generated by ioStudio !!!
#if !defined(__ORIONTRSMARTISO12_24_10_H)
#define __ORIONTRSMARTISO12_24_10_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ids/Convert/DataDcDc.h"
class OrionTrSmartIso12_24_10 : public ioModel
{
public:
    OrionTrSmartIso12_24_10();
    virtual ~OrionTrSmartIso12_24_10();
    virtual void InitializeItem(void);
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    virtual void SimulateVoltOutput(Float voltInput, Bool isOutputActive, Float* voltOutput);
    DataDcDc DcDcData;
};
#endif // __ORIONTRSMARTISO12_24_10_H
