// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SmartIp43_12V_50_2.h"
SmartIp43_12V_50_2::SmartIp43_12V_50_2()
{
}
SmartIp43_12V_50_2::~SmartIp43_12V_50_2()
{
}
void SmartIp43_12V_50_2::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&ChargeData);
}
void SmartIp43_12V_50_2::DoSimulation_100ms(Int32 slotCounter_100ms)
{
    Float out0_Float;
    if ((slotCounter_100ms % 10) == 0)
    {
        SimulateVoltOutput(
                ChargeData.VoltageInputAc.GetValue(), 
                ChargeData.IsChargingActive.GetValue(),
                &out0_Float
        );
        ChargeData.VoltageOutputDc.SetValue(out0_Float);
    } // if
}
void SmartIp43_12V_50_2::SimulateVoltOutput(Float voltInputAc, Bool isOutputActive, Float* voltOutputDc)
{
}
