// !!! This C++ file is generated by ioStudio !!!
#if !defined(__PROGRAMCERBOGX_H)
#define __PROGRAMCERBOGX_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "ioModbus/ioPortProgramModbus.h"
#include "Programs/Victron/Charge/DataCharge.h"
#include "Programs/Victron/Io/DataCerboGx.h"
#include "Programs/Victron/DcDc/DataDcDc.h"
#include "Programs/Victron/Charge/PanelCharge.h"
#include "Programs/Victron/DcDc/PanelDcDc.h"
class ProgramCerboGx : public ioProgram
{
public:
    ProgramCerboGx();
    virtual ~ProgramCerboGx();
    virtual void InitializeTask(void);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    virtual void Run(Int32 activeSlot);
    ioPortProgramModbus PortModbus;
    DataCharge ChargeData;
    DataCerboGx CgxData;
    DataDcDc DcDcData;
    PanelCharge ChargePanel;
    PanelDcDc DcDcPanel;
};
#endif // __PROGRAMCERBOGX_H
