// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SHUNTMODEL_H)
#define __SHUNTMODEL_H
#include "ioSystem/Simulation/ioModel.h"
class ShuntModel : public ioModel
{
public:
    ShuntModel();
    virtual ~ShuntModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
};
#endif // __SHUNTMODEL_H
