// !!! This C++ file is generated by ioStudio !!!
#if !defined(__COMMANDPANELCP2_H)
#define __COMMANDPANELCP2_H
#include "CommandPanel.h"
class CommandPanelCp2 : public CommandPanel
{
public:
    CommandPanelCp2();
    virtual ~CommandPanelCp2();
    virtual void InitializeData(void);
};
#endif // __COMMANDPANELCP2_H
