// !!! This file is generated by ioStudio !!!
#if !defined(__COMMANDPANELCP1_H)
#define __COMMANDPANELCP1_H
#include "CommandPanel.h"
class CommandPanelCp1 : public CommandPanel
{
public:
    CommandPanelCp1();
    virtual ~CommandPanelCp1();
    virtual void InitializeData(void);
};
#endif // __COMMANDPANELCP1_H
