// !!! This file is generated by ioStudio !!!
#if !defined(__MODEPANELCP2_H)
#define __MODEPANELCP2_H
#include "ModePanel.h"
class ModePanelCp2 : public ModePanel
{
public:
    ModePanelCp2();
    virtual ~ModePanelCp2();
    virtual void InitializeData(void);
};
#endif // __MODEPANELCP2_H
