// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ModePanelCp2.h"
ModePanelCp2::ModePanelCp2()
{
    InitializeData();
}
ModePanelCp2::~ModePanelCp2()
{
}
void ModePanelCp2::InitializeData(void)
{
    ModePanel::InitializeData();
}
