// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefPanel.h"
SetRefPanel::SetRefPanel()
{
}
SetRefPanel::~SetRefPanel()
{
}
void SetRefPanel::InitializeData(void)
{
}
