// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefPanelCp1.h"
SetRefPanelCp1::SetRefPanelCp1()
{
    InitializeData();
}
SetRefPanelCp1::~SetRefPanelCp1()
{
}
void SetRefPanelCp1::InitializeData(void)
{
    SetRefPanel::InitializeData();
}
