// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefPanelCp2.h"
SetRefPanelCp2::SetRefPanelCp2()
{
    InitializeData();
}
SetRefPanelCp2::~SetRefPanelCp2()
{
}
void SetRefPanelCp2::InitializeData(void)
{
    SetRefPanel::InitializeData();
}
