// !!! This file is generated by ioStudio !!!
#if !defined(__STEERCONTROLDATACP1_H)
#define __STEERCONTROLDATACP1_H
#include "SteerControlData.h"
class SteerControlDataCp1 : public SteerControlData
{
public:
    SteerControlDataCp1();
    virtual ~SteerControlDataCp1();
    virtual void InitializeData(void);
};
#endif // __STEERCONTROLDATACP1_H
