// !!! This file is generated by ioStudio !!!
#if !defined(__STEERCONTROLDATA_H)
#define __STEERCONTROLDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioEvent.h"
#include "ioSystem/Data/ioMethod.h"
class SteerControlData : public ioDataCollectionDynamic
{
public:
    SteerControlData();
    virtual ~SteerControlData();
    virtual void InitializeData(void);
    ioMethod TakeCommand;
    ioMethod ModeDp;
    ioMethod ModeRiver;
    ioMethod ModeTrack;
    ioMethod ModeWork;
    ioMethod ModeAuto;
    ioMethod ModeStandby;
    ioVarInt32 SteerMode;
    ioMethod Release;
    ioEvent OnChangeCommand;
    ioEvent OnChangeSteerMode;
    ioMethod LeftSmall;
    ioMethod MidZero;
    ioMethod RightSmall;
    ioMethod LeftBig;
    ioMethod RightBig;
    ioMethod EncoderNumber;
protected:
    ioData* m_ListData[17];
};
#endif // __STEERCONTROLDATA_H
