// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerControlData.h"
SteerControlData::SteerControlData()
{
}
SteerControlData::~SteerControlData()
{
}
void SteerControlData::InitializeData(void)
{
    SetListData(m_ListData, 8);
    ResetItem();
}
