// !!! This C++ file is generated by ioStudio !!!
#if !defined(__DATABATTERYMODEL_H)
#define __DATABATTERYMODEL_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class DataBatteryModel : public ioDataCollection
{
public:
    DataBatteryModel();
    virtual ~DataBatteryModel();
    void InitializeData(void);
    ioVarFloat BatteryChargeResistance;
protected:
    ioData* m_ListData[1];
};
#endif // __DATABATTERYMODEL_H
