// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "DataGenerator.h"
DataGenerator::DataGenerator()
{
    InitializeData();
}
DataGenerator::~DataGenerator()
{
}
void DataGenerator::InitializeData(void)
{
    SetListData(m_ListData, 3);
    ResetItem();
    VoltOutputGenerator.SetValue((Float)12);
    AddData((ioData*)&VoltOutputGenerator, Duid_Ids_Source_VoltOutputGenerator);
    IsGeneratorOutputActive.SetValue(TRUE);
    AddData((ioData*)&IsGeneratorOutputActive, Duid_Ids_Source_IsGeneratorOutputActive);
    MaxOutCurrentGenerator.SetValue(160.00);
    AddData((ioData*)&MaxOutCurrentGenerator, Duid_Ids_Source_MaxOutCurrentGenerator);
}
