// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "DataBatteryModel.h"
DataBatteryModel::DataBatteryModel()
{
    InitializeData();
}
DataBatteryModel::~DataBatteryModel()
{
}
void DataBatteryModel::InitializeData(void)
{
    SetListData(m_ListData, 2);
    ResetItem();
    BatteryChargeResistance.SetValue((Float)0.15);
    AddData((ioData*)&BatteryChargeResistance, Duid_Ids_Source_BatteryChargeResistance);
    BatteryEnergy.SetValue((Float)300);
    AddData((ioData*)&BatteryEnergy, Duid_Ids_Source_BatteryEnergy);
}
