// !!! This C++ file is generated by ioStudio !!!
#if !defined(__DATABATTERY_H)
#define __DATABATTERY_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class DataBattery : public ioDataCollection
{
public:
    DataBattery();
    virtual ~DataBattery();
    void InitializeData(void);
    ioVarFloat VoltageBattery;
    ioVarFloat CurrentBattery;
    ioVarFloat StatusOfCharge;
protected:
    ioData* m_ListData[3];
};
#endif // __DATABATTERY_H
