// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PanelBattery.h"
#include "Programs/ioSystemGraphics.h"
PanelBattery::PanelBattery()
{
}
PanelBattery::~PanelBattery()
{
}
void PanelBattery::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_PanelBatteryGraphics, 4);
    AddGraphics(&LabelHeaderVoltBattery, Puid_Ids_Source_LabelHeaderVoltBattery);
    LabelHeaderVoltBattery.SetTextForced((ioChars)"VOLTAGE BATTERY [VDC]");
    AddGraphics(&InstrVoltBattery, Puid_Ids_Source_InstrVoltBattery);
    InstrVoltBattery.SetTextForced((ioChars)"12.1");
    InstrVoltBattery.SetDecimals(1);
    AddGraphics(&LabelHeaderCurrBattery, Puid_Ids_Source_LabelHeaderCurrBattery);
    LabelHeaderCurrBattery.SetTextForced((ioChars)"CURRENT BATTERY [A]");
    AddGraphics(&InstrCurrBattery, Puid_Ids_Source_InstrCurrBattery);
    InstrCurrBattery.SetTextForced((ioChars)"1.3");
    InstrCurrBattery.SetDecimals(1);
}
