// !!! This C++ file is generated by ioStudio !!!
#if !defined(__PANELBATTERY_H)
#define __PANELBATTERY_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class PanelBattery : public ioPanel
{
public:
    PanelBattery();
    virtual ~PanelBattery();
    virtual void InitializeData(void);
    ioLabel LabelHeaderVoltBattery;
    ioTextBlock InstrVoltBattery;
    ioLabel LabelHeaderCurrBattery;
    ioTextBlock InstrCurrBattery;
protected:
    ioGraphics* m_PanelBatteryGraphics[4];
};
#endif // __PANELBATTERY_H
