///////////////////////////////////////////////////////////
//  ObAlertMenuItem.cs
//  Implementation of the Class ObAlertMenuItem
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:27:12
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeAppLib.Components.Application 
{
	public class ObAlertMenuItem 
    {
		public ObAlertMenuItem()
        {
		}

		~ObAlertMenuItem()
        {
		}

	}//end ObAlertMenuItem

}//end namespace Application
