///////////////////////////////////////////////////////////
//  ObAlertTopbarElement.cs
//  Implementation of the Class ObAlertTopbarElement
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:28:03
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using OpenBridgeAppLib.Palettes;

namespace OpenBridgeAppLib.Components.Application 
{
	public class ObAlertTopbarElement 
    {
		public bool AlertMuted;
		public ObAlertType AlertType;
		public int MaxWidth;
		public int NAlerts;
		public bool ShowAck;

		public ObAlertTopbarElement()
        {
            AlertMuted = false;
            AlertType = ObAlertType.None;
            MaxWidth = 300;
            NAlerts = 1;
            ShowAck = true;
		}

		~ObAlertTopbarElement()
        {
		}

	}//end ObAlertTopbarElement

}//end namespace Application
