///////////////////////////////////////////////////////////
//  ObAppMenu.cs
//  Implementation of the Class ObAppMenu
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:28:17
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeAppLib.Components.Application 
{
	public class ObAppMenu 
    {
		public ObAppMenu()
        {
		}

		~ObAppMenu()
        {
		}

	}//end ObAppMenu

}//end namespace Application
