///////////////////////////////////////////////////////////
//  ObClock.cs
//  Implementation of the Class ObClock
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:28:51
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeAppLib.Components.Application 
{
	public class ObClock 
    {
		public int BlinkOnlyBreakpointPx;
		public string Date;
		public bool ShowDate;

		public ObClock()
        {
            BlinkOnlyBreakpointPx = 0;
            Date = string.Empty;
            ShowDate = true;
        }

		~ObClock()
        {
		}

	}//end ObClock

}//end namespace Application
