///////////////////////////////////////////////////////////
//  ObScrollbar.cs
//  Implementation of the Class ObScrollbar
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:29:32
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeAppLib.Components.Application 
{
	public class ObScrollbar 
    {
		public ObScrollbar()
        {
		}

		~ObScrollbar()
        {
		}

	}//end ObScrollbar

}//end namespace Application
