// !!! This C++ file is generated by ioStudio !!!
#if !defined(__FUSEMODELDATA_H)
#define __FUSEMODELDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioMethod.h"
class FuseModelData : public ioDataCollection
{
public:
    FuseModelData();
    virtual ~FuseModelData();
    void InitializeData(void);
    ioVarFloat MaxFuseCurrent;
    ioVarBool IsFuseBlown;
    ioMethod ResetFuse;
protected:
    ioData* m_ListData[3];
};
#endif // __FUSEMODELDATA_H
