// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "InstrumentResultForce.h"
#include "Programs/ioSystemGraphics.h"
InstrumentResultForce::InstrumentResultForce()
{
}
InstrumentResultForce::~InstrumentResultForce()
{
}
void InstrumentResultForce::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_InstrumentResultForceGraphics, 7);
    AddGraphics(&LabelResultAngleHeader, Puid_Ids_Position_LabelResultAngleHeader);
    LabelResultAngleHeader.SetTextForced((ioChars)"ANGLE");
    AddGraphics(&LabelResultAngleHeaderUnit, Puid_Ids_Position_LabelResultAngleHeaderUnit);
    LabelResultAngleHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&LabelResultSpeedHeader, Puid_Ids_Position_LabelResultSpeedHeader);
    LabelResultSpeedHeader.SetTextForced((ioChars)"SPEED");
    AddGraphics(&LabelResultSpeedHeaderUnit, Puid_Ids_Position_LabelResultSpeedHeaderUnit);
    LabelResultSpeedHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&InstrResultAngle, Puid_Ids_Position_InstrResultAngle);
    InstrResultAngle.SetTextForced((ioChars)"000");
    InstrResultAngle.SetDecimals(1);
    AddGraphics(&InstrResultSpeed, Puid_Ids_Position_InstrResultSpeed);
    InstrResultSpeed.SetTextForced((ioChars)"0.0");
    InstrResultSpeed.SetDecimals(1);
    AddGraphics(&CompResultForce, Puid_Ids_Position_CompResultForce);
}
