// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "InstrumentWind.h"
#include "Programs/ioSystemGraphics.h"
InstrumentWind::InstrumentWind()
{
}
InstrumentWind::~InstrumentWind()
{
}
void InstrumentWind::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_InstrumentWindGraphics, 14);
    AddGraphics(&LabelAwaInstrHeader, Puid_Ids_Position_LabelAwaInstrHeader);
    LabelAwaInstrHeader.SetTextForced((ioChars)"AWA");
    AddGraphics(&LabelAwaInstrHeaderUnit, Puid_Ids_Position_LabelAwaInstrHeaderUnit);
    LabelAwaInstrHeaderUnit.SetTextForced((ioChars)"°");
    AddGraphics(&LabelAwsInstrHeader, Puid_Ids_Position_LabelAwsInstrHeader);
    LabelAwsInstrHeader.SetTextForced((ioChars)"AWS");
    AddGraphics(&LabelAwsInstrHeaderUnit, Puid_Ids_Position_LabelAwsInstrHeaderUnit);
    LabelAwsInstrHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&LabelWDirInstrHeader, Puid_Ids_Position_LabelWDirInstrHeader);
    LabelWDirInstrHeader.SetTextForced((ioChars)"WDIR");
    AddGraphics(&LabelWDirInstrHeaderUnit, Puid_Ids_Position_LabelWDirInstrHeaderUnit);
    LabelWDirInstrHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&LabelWSpdInstrHeader, Puid_Ids_Position_LabelWSpdInstrHeader);
    LabelWSpdInstrHeader.SetTextForced((ioChars)"WSPD");
    AddGraphics(&LabelWSpdInstrHeaderUnit, Puid_Ids_Position_LabelWSpdInstrHeaderUnit);
    LabelWSpdInstrHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&IconAwaInstrLeft, Puid_Ids_Position_IconAwaInstrLeft);
    AddGraphics(&InstrAwaInstr, Puid_Ids_Position_InstrAwaInstr);
    InstrAwaInstr.SetTextForced((ioChars)"0");
    InstrAwaInstr.SetDecimals(1);
    AddGraphics(&IconAwaInstrRight, Puid_Ids_Position_IconAwaInstrRight);
    AddGraphics(&InstrAwsInstr, Puid_Ids_Position_InstrAwsInstr);
    InstrAwsInstr.SetTextForced((ioChars)"0.0");
    InstrAwsInstr.SetDecimals(1);
    AddGraphics(&InstrWDirInstr, Puid_Ids_Position_InstrWDirInstr);
    InstrWDirInstr.SetTextForced((ioChars)"000");
    InstrWDirInstr.SetDecimals(1);
    AddGraphics(&InstrWSpdInstr, Puid_Ids_Position_InstrWSpdInstr);
    InstrWSpdInstr.SetTextForced((ioChars)"0.0");
    InstrWSpdInstr.SetDecimals(1);
}
