// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PositionInstrPanel.h"
#include "Programs/ioSystemGraphics.h"
PositionInstrPanel::PositionInstrPanel()
{
}
PositionInstrPanel::~PositionInstrPanel()
{
}
void PositionInstrPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_PositionInstrPanelGraphics, 19);
    AddGraphics(&LabelBtwPosIndHeader, Puid_Ids_Position_LabelBtwPosIndHeader);
    LabelBtwPosIndHeader.SetTextForced((ioChars)"BTW");
    AddGraphics(&LabelBtwPosIndHeaderUnit, Puid_Ids_Position_LabelBtwPosIndHeaderUnit);
    LabelBtwPosIndHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&InstrBtwPosInstInstr, Puid_Ids_Position_InstrBtwPosInstInstr);
    InstrBtwPosInstInstr.SetTextForced((ioChars)"000");
    InstrBtwPosInstInstr.SetDecimals(1);
    AddGraphics(&LabelHdgPosIndHeader, Puid_Ids_Position_LabelHdgPosIndHeader);
    LabelHdgPosIndHeader.SetTextForced((ioChars)"HDG");
    AddGraphics(&LabelBtwPosIndHeaderUnit, Puid_Ids_Position_LabelBtwPosIndHeaderUnit);
    LabelBtwPosIndHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&InstrHdgPosInstInstr, Puid_Ids_Position_InstrHdgPosInstInstr);
    InstrHdgPosInstInstr.SetTextForced((ioChars)"000.0");
    InstrHdgPosInstInstr.SetDecimals(1);
    AddGraphics(&LabelCogPosIndHeader, Puid_Ids_Position_LabelCogPosIndHeader);
    LabelCogPosIndHeader.SetTextForced((ioChars)"COG");
    AddGraphics(&LabelCogPosIndHeaderUnit, Puid_Ids_Position_LabelCogPosIndHeaderUnit);
    LabelCogPosIndHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&InstrCogPosInstInstr, Puid_Ids_Position_InstrCogPosInstInstr);
    InstrCogPosInstInstr.SetTextForced((ioChars)"000.0");
    InstrCogPosInstInstr.SetDecimals(1);
    AddGraphics(&UiPosSteerPanel, Puid_Ids_Position_PositionInstrPanel_UiPosSteerPanel);
    AddGraphics(&LabelFwdNorthPosIndHeader, Puid_Ids_Position_LabelFwdNorthPosIndHeader);
    LabelFwdNorthPosIndHeader.SetTextForced((ioChars)"FWD");
    AddGraphics(&LabelFwdNorthPosIndHeaderUnit, Puid_Ids_Position_LabelFwdNorthPosIndHeaderUnit);
    LabelFwdNorthPosIndHeaderUnit.SetTextForced((ioChars)"m");
    AddGraphics(&InstrFwdNorthPosInstInstr, Puid_Ids_Position_InstrFwdNorthPosInstInstr);
    InstrFwdNorthPosInstInstr.SetTextForced((ioChars)"0.0");
    InstrFwdNorthPosInstInstr.SetDecimals(1);
    AddGraphics(&LabelDriftPosIndHeader, Puid_Ids_Position_LabelDriftPosIndHeader);
    LabelDriftPosIndHeader.SetTextForced((ioChars)"DRIFT");
    AddGraphics(&LabelDriftPosIndHeaderUnit, Puid_Ids_Position_LabelDriftPosIndHeaderUnit);
    LabelDriftPosIndHeaderUnit.SetTextForced((ioChars)"m/s");
    AddGraphics(&InstrDriftPosInstInstr, Puid_Ids_Position_InstrDriftPosInstInstr);
    InstrDriftPosInstInstr.SetTextForced((ioChars)"0.0");
    InstrDriftPosInstInstr.SetDecimals(1);
    AddGraphics(&LabelStbdEastPosIndHeader, Puid_Ids_Position_LabelStbdEastPosIndHeader);
    LabelStbdEastPosIndHeader.SetTextForced((ioChars)"STBD");
    AddGraphics(&LabelStbdEastPosIndHeaderUnit, Puid_Ids_Position_LabelStbdEastPosIndHeaderUnit);
    LabelStbdEastPosIndHeaderUnit.SetTextForced((ioChars)"m");
    AddGraphics(&InstrStbdPosInstInstr, Puid_Ids_Position_InstrStbdPosInstInstr);
    InstrStbdPosInstInstr.SetTextForced((ioChars)"0.0");
    InstrStbdPosInstInstr.SetDecimals(1);
}
