// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefPosPanel.h"
#include "Programs/ioSystemGraphics.h"
SetRefPosPanel::SetRefPosPanel()
{
}
SetRefPosPanel::~SetRefPosPanel()
{
}
void SetRefPosPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SetRefPosPanelGraphics, 4);
    AddGraphics(&ButtonWestPort, Puid_Ids_Position_ButtonWestPort);
    ButtonWestPort.SetTextForced((ioChars)"Port");
    AddGraphics(&ButtonNorthFwd, Puid_Ids_Position_ButtonNorthFwd);
    ButtonNorthFwd.SetTextForced((ioChars)"Forward");
    AddGraphics(&ButtonSouthBack, Puid_Ids_Position_ButtonSouthBack);
    ButtonSouthBack.SetTextForced((ioChars)"Back");
    AddGraphics(&ButtonEastStarb, Puid_Ids_Position_ButtonEastStarb);
    ButtonEastStarb.SetTextForced((ioChars)"Starboard");
}
