// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFPOSPANEL_H)
#define __SETREFPOSPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioButtonText.h"
class SetRefPosPanel : public ioPanel
{
public:
    SetRefPosPanel();
    virtual ~SetRefPosPanel();
    virtual void InitializeData(void);
    ioButtonIcon ButtonWestPort;
    ioButtonIcon ButtonNorthFwd;
    ioButtonIcon ButtonSouthBack;
    ioButtonIcon ButtonEastStarb;
protected:
    ioGraphics* m_SetRefPosPanelGraphics[4];
};
#endif // __SETREFPOSPANEL_H
