// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetupRefPosFlyout.h"
#include "Programs/ioSystemGraphics.h"
SetupRefPosFlyout::SetupRefPosFlyout()
{
}
SetupRefPosFlyout::~SetupRefPosFlyout()
{
}
void SetupRefPosFlyout::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SetupRefPosFlyoutGraphics, 4);
    AddGraphics(&LabelEnableSteeringPosRef, Puid_Ids_Position_LabelEnableSteeringPosRef);
    LabelEnableSteeringPosRef.SetTextForced((ioChars)"ENABLE STEERING AXIS");
    AddGraphics(&DividerEnableSteeringPosRef, Puid_Ids_Position_DividerEnableSteeringPosRef);
    AddGraphics(&ButtonEnableSurgeSteer, Puid_Ids_Position_ButtonEnableSurgeSteer);
    ButtonEnableSurgeSteer.SetTextForced((ioChars)"Surge");
    AddGraphics(&ButtonEnableSwaySteer, Puid_Ids_Position_ButtonEnableSwaySteer);
    ButtonEnableSwaySteer.SetTextForced((ioChars)"Sway");
}
