// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETUPREFPOSFLYOUT_H)
#define __SETUPREFPOSFLYOUT_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioDivider.h"
#include "ioSystem/Panels/ioButtonText.h"
class SetupRefPosFlyout : public ioPanel
{
public:
    SetupRefPosFlyout();
    virtual ~SetupRefPosFlyout();
    virtual void InitializeData(void);
    ioLabel LabelEnableSteeringPosRef;
    ioDivider DividerEnableSteeringPosRef;
    ioButtonIcon ButtonEnableSurgeSteer;
    ioButtonIcon ButtonEnableSwaySteer;
protected:
    ioGraphics* m_SetupRefPosFlyoutGraphics[4];
};
#endif // __SETUPREFPOSFLYOUT_H
