// !!! This C++ file is generated by ioStudio !!!
#if !defined(__DATAGENERATOR_H)
#define __DATAGENERATOR_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class DataGenerator : public ioDataCollection
{
public:
    DataGenerator();
    virtual ~DataGenerator();
    void InitializeData(void);
    ioVarFloat VoltOutputGenerator;
    ioVarBool IsGeneratorOutputActive;
    ioVarFloat MaxOutCurrentGenerator;
    ioVarFloat CurrentGenerator;
protected:
    ioData* m_ListData[4];
};
#endif // __DATAGENERATOR_H
