// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ChargeModel.h"
ChargeModel::ChargeModel()
{
}
ChargeModel::~ChargeModel()
{
}
void ChargeModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void ChargeModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
void ChargeModel::SimulateVoltOutput(Float voltInputAc, Bool isOutputActive, Float* voltOutputDc)
{
}
