// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "DcDcModel.h"
DcDcModel::DcDcModel()
{
}
DcDcModel::~DcDcModel()
{
}
void DcDcModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void DcDcModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
