// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "MaksPowerMp200Dynamo.h"
MaksPowerMp200Dynamo::MaksPowerMp200Dynamo()
{
}
MaksPowerMp200Dynamo::~MaksPowerMp200Dynamo()
{
}
void MaksPowerMp200Dynamo::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&GeneratorData);
}
void MaksPowerMp200Dynamo::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
