// !!! This C++ file is generated by ioStudio !!!
#if !defined(__MAKSPOWERMP200DYNAMO_H)
#define __MAKSPOWERMP200DYNAMO_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ops/Source/DataGenerator.h"
class MaksPowerMp200Dynamo : public ioModel
{
public:
    MaksPowerMp200Dynamo();
    virtual ~MaksPowerMp200Dynamo();
    virtual void InitializeItem(void);
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    DataGenerator GeneratorData;
};
#endif // __MAKSPOWERMP200DYNAMO_H
