// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "MaksPowerBattLithium2x150Ah12V.h"
MaksPowerBattLithium2x150Ah12V::MaksPowerBattLithium2x150Ah12V()
{
}
MaksPowerBattLithium2x150Ah12V::~MaksPowerBattLithium2x150Ah12V()
{
}
void MaksPowerBattLithium2x150Ah12V::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&BatteryData);
    AddData((ioDataCollection*)&ModelData);
}
void MaksPowerBattLithium2x150Ah12V::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
