// !!! This C++ file is generated by ioStudio !!!
#if !defined(__MAKSPOWERBATTOPTIMA50AH12V_H)
#define __MAKSPOWERBATTOPTIMA50AH12V_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ids/Source/DataBattery.h"
#include "Programs/Ids/Source/DataBatteryModel.h"
class MaksPowerBattOptima50Ah12V : public ioModel
{
public:
    MaksPowerBattOptima50Ah12V();
    virtual ~MaksPowerBattOptima50Ah12V();
    virtual void InitializeItem(void);
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    DataBattery BatteryData;
    DataBatteryModel ModelData;
};
#endif // __MAKSPOWERBATTOPTIMA50AH12V_H
