// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "MaksPowerBattOptima50Ah12V.h"
MaksPowerBattOptima50Ah12V::MaksPowerBattOptima50Ah12V()
{
}
MaksPowerBattOptima50Ah12V::~MaksPowerBattOptima50Ah12V()
{
}
void MaksPowerBattOptima50Ah12V::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&BatteryData);
    AddData((ioDataCollection*)&ModelData);
}
void MaksPowerBattOptima50Ah12V::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
