///////////////////////////////////////////////////////////
//  ObTable.cs
//  Implementation of the Class ObTable
//  Generated by Enterprise Architect
//  Created on:      27-Feb-2024 17:51:38
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeAppLib.Components.Tables 
{
	public class ObTable 
    {
		public ObTable()
        {
		}

		~ObTable()
        {
		}

	}//end ObTable

}//end namespace Tables
