// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ioSystemPorts.h"
ioSystemPorts::ioSystemPorts()
{
}
ioSystemPorts::~ioSystemPorts()
{
}
Int32 ioSystemPorts::GetNetworkID(ioSystemPortsType nuid)
{
    return (Int32)nuid;
}
ioSystemPortsType ioSystemPorts::GetPortType(Int32 nuidValue)
{
    switch (nuidValue)
    {
    default: return Nuid_NotDefined; 
    case 0: return Nuid_NotDefined; 
    case 1: return Nuid_NetEthernet_192_168_10_Ops_Network_NetBatteryGate_10; 
    case 2: return Nuid_NetEthernet_192_168_10_Ops_Network_Ipc_11; 
    case 3: return Nuid_NetEthernet_192_168_10_Ops_Instrument_InstrumentDisplay_12; 
    case 4: return Nuid_NetWiFi_192_168_11_Ops_Network_NetBatteryGate_10; 
    case 5: return Nuid_NetWiFi_192_168_11_Ops_Network_Ipc_11; 
    case 6: return Nuid_NetWiFi_192_168_11_Ops_Instrument_InstrumentDisplay_12; 
    case 7: return Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_ComToUsbA; 
    case 8: return Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_ComToUsbB; 
    case 9: return Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_Com1; 
    case 10: return Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_Com2; 
    case 11: return Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_Com3; 
    case 12: return Nuid_NetBattery_Power_Power_Convert_Charger_Com1; 
    case 13: return Nuid_NetBattery_Power_Power_Convert_ConvDcDc_Com1; 
    case 14: return Nuid_NetBattery_Power_Ops_Network_Shunt_Com1; 
    case 15: return Nuid_NetOps_Power_Ops_Consume_Junction_PowerNet; 
    case 16: return Nuid_NetOps_Power_Ops_Network_Ipc_PowerNet; 
    case 17: return Nuid_NetOps_Panels_Ops_Consume_Switchboard_PowerPanelIo; 
    case 18: return Nuid_NetOps_Panels_Ops_Consume_Junction_PowerPanelIo; 
    case 19: return Nuid_NetAc_Dock_Power_Convert_Charger_PI1; 
    case 20: return Nuid_NetAc_Dock_Power_Isolate_SwitchAc_PO1; 
    case 21: return Nuid_NetDc_Generator_Power_Isolate_Diode_PI1; 
    case 22: return Nuid_NetDc_Generator_Power_Source_Generator_PO1; 
    case 23: return Nuid_NetDc_Aux_Power_Source_Battery_PO1; 
    case 24: return Nuid_NetDc_Aux_Power_Convert_Charger_PO1; 
    case 25: return Nuid_NetDc_Aux_Power_Isolate_SwitchDc_PO1; 
    case 26: return Nuid_NetDc_Aux_Power_Isolate_Diode_PO1; 
    case 27: return Nuid_NetDc_Aux_Power_Network_Shunt_PI1; 
    case 28: return Nuid_NetDc_Aux_Ops_Consume_Junction_PI1; 
    case 29: return Nuid_NetDc_Aux_Ops_Network_NetBatteryGate_PI1; 
    case 30: return Nuid_NetDc_Aux_Ops_Network_Ipc_PI1; 
    case 31: return Nuid_NetDc_Aux_Ops_Instrument_InstrumentDisplay_PI1; 
    case 32: return Nuid_NetDc_Motor_Power_Source_Battery_PO1; 
    case 33: return Nuid_NetDc_Motor_Power_Convert_Charger_PO2; 
    case 34: return Nuid_NetDc_Motor_Power_Isolate_Diode_PO2; 
    case 35: return Nuid_NetDc_Motor_Power_Isolate_SwitchDc_PO1; 
    case 36: return Nuid_NetDc_Motor_Power_Rotate_StartMotor_PI1; 
    case 37: return Nuid_NetDc_Level_Power_Source_Battery_PO1; 
    case 38: return Nuid_NetDc_Level_Power_Convert_Charger_PO1; 
    case 39: return Nuid_NetDc_Level_Power_Convert_ConvDcDc_PO1; 
    case 40: return Nuid_NetDc_Level_Power_Isolate_SwitchDc_PO1; 
    case 41: return Nuid_NetDc_Level_Power_Isolate_Diode_PO3; 
    case 42: return Nuid_NetDc_Level_Power_Network_Shunt_PO2; 
    } // switch
}
