// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ioSystemGraphics.h"
ioSystemGraphics::ioSystemGraphics()
{
}
ioSystemGraphics::~ioSystemGraphics()
{
}
Int32 ioSystemGraphics::GetGraphicsID(ioSystemGraphicsType puid)
{
    return (Int32)puid;
}
ioSystemGraphicsType ioSystemGraphics::GetGraphicsType(Int32 puidValue)
{
    switch (puidValue)
    {
    default: return Puid_NotDefined; 
    case 0: return Puid_NotDefined; 
    case 13: return Puid_Ids_Convert_SelectCharger; 
    case 15: return Puid_Ids_Convert_InstrVoltOutputDc; 
    case 16: return Puid_Ids_Convert_LabelHeaderChargeInput; 
    case 17: return Puid_Ids_Convert_LabelHeaderChargeOutput; 
    case 18: return Puid_Ids_Convert_InstrVoltInputAc; 
    case 19: return Puid_Ids_Convert_InstVoltOutputDc; 
    case 20: return Puid_Ids_Convert_SelectDcDc; 
    case 21: return Puid_Ids_Convert_LabelHeaderDcDcInput; 
    case 22: return Puid_Ids_Convert_LabelHeaderDcDcOutput; 
    case 23: return Puid_Ids_Convert_InstrVoltInputDcDc; 
    case 24: return Puid_Ids_Convert_InstrVoltOutputDcDc; 
    case 1: return Puid_Victron_PanelCharge; 
    case 2: return Puid_Victron_PanelDcDc; 
    } // switch
}
