// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ioSystemData.h"
TypeUnit::TypeUnit()
{
}
TypeUnit::~TypeUnit()
{
}
Bool TypeUnit::GetActiveText(ioString* enumText)
{
    if (enumText == NULL) return FALSE;
    Int32 activeID = GetValueSigned();
    switch (activeID)
    {
    case 0: enumText->Set((ioChars)"m/s"); return TRUE;
    case 1: enumText->Set((ioChars)"kt"); return TRUE;
    case 2: enumText->Set((ioChars)"kg"); return TRUE;
    case 3: enumText->Set((ioChars)"nm"); return TRUE;
    case 4: enumText->Set((ioChars)"m"); return TRUE;
    case 5: enumText->Set((ioChars)"°C"); return TRUE;
    default: enumText->Set((ioChars)"NotDefined");  return FALSE;
    } // switch
}
StationModeType::StationModeType()
{
}
StationModeType::~StationModeType()
{
}
Bool StationModeType::GetActiveText(ioString* enumText)
{
    if (enumText == NULL) return FALSE;
    Int32 activeID = GetValueSigned();
    switch (activeID)
    {
    case 0: enumText->Set((ioChars)"No command"); return TRUE;
    case 1: enumText->Set((ioChars)"Taken"); return TRUE;
    case 2: enumText->Set((ioChars)"Remote control"); return TRUE;
    case 3: enumText->Set((ioChars)"Taken and locked"); return TRUE;
    case 4: enumText->Set((ioChars)"Take over request"); return TRUE;
    default: enumText->Set((ioChars)"NotDefined");  return FALSE;
    } // switch
}
ioSystemData::ioSystemData()
{
}
ioSystemData::~ioSystemData()
{
}
Int32 ioSystemData::GetDataID(ioSystemDataType duid)
{
    return (Int32)duid;
}
ioSystemDataType ioSystemData::GetDataType(Int32 duidValue)
{
    switch (duidValue)
    {
    default: return Duid_NotDefined; 
    case 0: return Duid_NotDefined; 
    case 1: return Duid_Ids_Consume_TakeCommandPow; 
    case 2: return Duid_Ids_Consume_ReleaseCommandPow; 
    case 3: return Duid_Ids_Consume_ActiveStationPow; 
    case 4: return Duid_Ids_Consume_OnChangeCommandPow; 
    case 5: return Duid_Ids_Consume_StationModePow; 
    case 6: return Duid_Ids_Consume_PowModeIdle; 
    case 7: return Duid_Ids_Consume_PowModeShore; 
    case 8: return Duid_Ids_Consume_PowModeDisconnect; 
    case 9: return Duid_Ids_Consume_PowModeTransitDay; 
    case 10: return Duid_Ids_Consume_PowModeTransitNightEngine; 
    case 11: return Duid_Ids_Consume_PowModeTransitNightSail; 
    case 12: return Duid_Ids_Consume_PowMode; 
    case 13: return Duid_Ids_Consume_OnChangePowMode; 
    case 14: return Duid_Ops_Consume_PowerConsumer; 
    case 15: return Duid_Ops_Consume_MaxFuseCurrent; 
    case 16: return Duid_Ops_Consume_IsFuseBlown; 
    case 17: return Duid_Ops_Consume_ResetFuse; 
    case 18: return Duid_Ids_Consume_IsOutputOn1; 
    case 19: return Duid_Ids_Consume_IsOutputOn2; 
    case 20: return Duid_Ids_Consume_IsOutputOn3; 
    case 21: return Duid_Ids_Consume_IsOutputOn4; 
    case 22: return Duid_Ids_Consume_IsOutputOn5; 
    case 23: return Duid_Ids_Consume_IsOutputOn6; 
    case 24: return Duid_Ids_Consume_IsOutputOn7; 
    case 25: return Duid_Ids_Consume_IsOutputOn8; 
    case 26: return Duid_Power_Convert_VoltageInputAc; 
    case 27: return Duid_Power_Convert_IsChargingActive; 
    case 28: return Duid_Power_Convert_CurrentOutputDc; 
    case 29: return Duid_Power_Convert_VoltageOutputDc; 
    case 30: return Duid_Power_Convert_CurrentInputAc; 
    case 31: return Duid_Power_Convert_MaxOutCurrentDc; 
    case 32: return Duid_Power_Convert_VoltageInputDcDc; 
    case 33: return Duid_Power_Convert_VoltageOutputDcDc; 
    case 34: return Duid_Power_Convert_IsDcDcOutputActive; 
    case 35: return Duid_Power_Convert_MaxOutCurrentDcDc; 
    case 36: return Duid_Power_Convert_CurrentInputDcDc; 
    case 37: return Duid_Power_Convert_CurrentOutputDcDc; 
    case 38: return Duid_Power_Isolate_MaxFuseCurrent; 
    case 39: return Duid_Power_Isolate_IsFuseBlown; 
    case 40: return Duid_Power_Isolate_ResetFuse; 
    case 41: return Duid_Power_Source_BatteryChargeResistance; 
    case 42: return Duid_Power_Source_BatteryEnergy; 
    case 43: return Duid_Power_Source_VoltageBattery; 
    case 44: return Duid_Power_Source_CurrentBattery; 
    case 45: return Duid_Power_Source_StatusOfCharge; 
    case 46: return Duid_Power_Source_VoltOutputGenerator; 
    case 47: return Duid_Power_Source_IsGeneratorOutputActive; 
    case 48: return Duid_Power_Source_MaxOutCurrentGenerator; 
    case 49: return Duid_Power_Source_CurrentGenerator; 
    } // switch
}
