// !!! This C++ file is generated by ioStudio !!!
#if !defined(__IOSYSTEMGRAPHICS_H)
#define __IOSYSTEMGRAPHICS_H
#include "ioSystem/Core/ioTypes.h"
typedef enum
{
    Puid_NotDefined = 0,
    Puid_Ids_Convert_SelectCharger = 13,
    Puid_Ids_Convert_InstrVoltOutputDc = 15,
    Puid_Ids_Convert_LabelHeaderChargeInput = 16,
    Puid_Ids_Convert_LabelHeaderChargeOutput = 17,
    Puid_Ids_Convert_InstrVoltInputAc = 18,
    Puid_Ids_Convert_InstVoltOutputDc = 19,
    Puid_Ids_Convert_SelectDcDc = 20,
    Puid_Ids_Convert_LabelHeaderDcDcInput = 21,
    Puid_Ids_Convert_LabelHeaderDcDcOutput = 22,
    Puid_Ids_Convert_InstrVoltInputDcDc = 23,
    Puid_Ids_Convert_InstrVoltOutputDcDc = 24,
    Puid_Victron_PanelCharge = 1,
    Puid_Victron_PanelDcDc = 2,
} ioSystemGraphicsType;
class ioSystemGraphics
{
public:
    ioSystemGraphics();
    virtual ~ioSystemGraphics();
    static Int32 GetGraphicsID(ioSystemGraphicsType puid);
    static ioSystemGraphicsType GetGraphicsType(Int32 puidValue);
};
#endif // __IOSYSTEMGRAPHICS_H
