// !!! This C++ file is generated by ioStudio !!!
#if !defined(__IOSYSTEMPORTS_H)
#define __IOSYSTEMPORTS_H
#include "ioSystem/Core/ioTypes.h"
typedef enum
{
    Nuid_NotDefined = 0,
    Nuid_NetEthernet_192_168_10_Victron_CerboGx_10 = 1,
    Nuid_NetEthernet_192_168_10_Ids_PlcIpc_11 = 2,
    Nuid_NetEthernet_192_168_10_Ids_Op_12 = 3,
    Nuid_NetWiFi_192_168_11_Victron_Io_CerboGx_10 = 4,
    Nuid_NetWiFi_192_168_11_Ids_PlcIpc_11 = 5,
    Nuid_NetWiFi_192_168_11_Ids_Op_12 = 6,
    Nuid_NetVeDirect_Io_Victron_Io_VeDirectToUsbA_VeDirect = 7,
    Nuid_NetVeDirect_Io_Victron_Io_VeDirectToUsbB_VeDirect = 8,
    Nuid_NetVeDirect_Io_Victron_Io_CerboGx_VeDirect1 = 9,
    Nuid_NetVeDirect_Io_Victron_Io_CerboGx_VeDirect2 = 10,
    Nuid_NetVeDirect_Io_Victron_Io_CerboGx_VeDirect3 = 11,
    Nuid_NetVeDirect_Io_Victron_Source_Chg12V_VeDirect = 12,
    Nuid_NetVeDirect_Io_Victron_Source_Chg24V_VeDirect = 13,
    Nuid_NetVeDirect_Io_Victron_Convert_Aux24V_VeDirect = 14,
    Nuid_NetVeDirect_Io_Victron_Convert_24VT_VeDirect = 15,
    Nuid_NetAc_Dock_Ids_Isolate_SwitchCharge_Input = 16,
    Nuid_NetAc_Dock_Ids_Convert_Charge_Input = 29,
    Nuid_NetDc_Generator_Ids_Isolate_Diode_Input = 17,
    Nuid_NetDc_Generator_Ids_Source_Generator_Output = 18,
    Nuid_NetDc_Aux_Ids_Source_BattAux_Pos = 22,
    Nuid_NetDc_Aux_Ids_Isolate_Diode_Output1 = 19,
    Nuid_NetDc_Aux_Ids_Isolate_FuseAux_Port1 = 21,
    Nuid_NetDc_Aux_Ids_Isolate_SwitchAux_Input = 24,
    Nuid_NetDc_Aux_Ids_Convert_Charge_Battery = 23,
    Nuid_NetDc_Aux_Ids_Io_Shunt_Output = 20,
    Nuid_NetDc_Aux_Ids_Consume_Aux_Input = 25,
    Nuid_NetDc_Motor_Ids_Source_BattMotor_Pos = 30,
    Nuid_NetDc_Motor_Ids_Isolate_Diode_Output2 = 26,
    Nuid_NetDc_Motor_Ids_Isolate_FuseMotor_Port1 = 27,
    Nuid_NetDc_Motor_Ids_Isolate_SwitchMotor_Input = 28,
    Nuid_NetDc_Motor_Ids_Convert_Charge_Motor = 31,
    Nuid_NetDc_Motor_Ids_Consume_Motor_Input = 35,
    Nuid_NetDc_Level_Ids_Isolate_Diode_Output3 = 32,
    Nuid_NetDc_Level_Ids_Convert_DcDc_Output = 33,
    Nuid_NetDc_Level_Ids_Consume_Level_Input = 34,
} ioSystemPortsType;
class ioSystemPorts
{
public:
    ioSystemPorts();
    virtual ~ioSystemPorts();
    static Int32 GetNetworkID(ioSystemPortsType nuid);
    static ioSystemPortsType GetPortType(Int32 nuidValue);
};
#endif // __IOSYSTEMPORTS_H
