// !!! This C++ file is generated by ioStudio !!!
#if !defined(__IOSYSTEMPORTS_H)
#define __IOSYSTEMPORTS_H
#include "ioSystem/Core/ioTypes.h"
typedef enum
{
    Nuid_NotDefined = 0,
    Nuid_NetEthernet_192_168_10_Ops_Network_NetBatteryGate_10 = 1,
    Nuid_NetEthernet_192_168_10_Ops_Network_Ipc_11 = 2,
    Nuid_NetEthernet_192_168_10_Ops_Instrument_InstrumentDisplay_12 = 3,
    Nuid_NetWiFi_192_168_11_Ops_Network_NetBatteryGate_10 = 4,
    Nuid_NetWiFi_192_168_11_Ops_Network_Ipc_11 = 5,
    Nuid_NetWiFi_192_168_11_Ops_Instrument_InstrumentDisplay_12 = 6,
    Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_ComToUsbA = 7,
    Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_ComToUsbB = 8,
    Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_Com1 = 9,
    Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_Com2 = 10,
    Nuid_NetBattery_Power_Ops_Network_NetBatteryGate_Com3 = 11,
    Nuid_NetBattery_Power_Power_Convert_Charger_Com1 = 12,
    Nuid_NetBattery_Power_Power_Convert_ConvDcDc_Com1 = 13,
    Nuid_NetBattery_Power_Ops_Network_Shunt_Com1 = 14,
    Nuid_NetOps_Power_Ops_Consume_Junction_PowerNet = 15,
    Nuid_NetOps_Power_Ops_Network_Ipc_PowerNet = 16,
    Nuid_NetOps_Panels_Ops_Consume_Switchboard_PowerPanelIo = 17,
    Nuid_NetOps_Panels_Ops_Consume_Junction_PowerPanelIo = 18,
    Nuid_NetAc_Dock_Power_Convert_Charger_PI1 = 19,
    Nuid_NetAc_Dock_Power_Isolate_SwitchAc_PO1 = 20,
    Nuid_NetDc_Generator_Power_Isolate_Diode_PI1 = 21,
    Nuid_NetDc_Generator_Power_Source_Generator_PO1 = 22,
    Nuid_NetDc_Aux_Power_Source_Battery_PO1 = 23,
    Nuid_NetDc_Aux_Power_Convert_Charger_PO1 = 24,
    Nuid_NetDc_Aux_Power_Isolate_SwitchDc_PO1 = 25,
    Nuid_NetDc_Aux_Power_Isolate_Diode_PO1 = 26,
    Nuid_NetDc_Aux_Power_Network_Shunt_PI1 = 27,
    Nuid_NetDc_Aux_Ops_Consume_Junction_PI1 = 28,
    Nuid_NetDc_Aux_Ops_Network_NetBatteryGate_PI1 = 29,
    Nuid_NetDc_Aux_Ops_Network_Ipc_PI1 = 30,
    Nuid_NetDc_Aux_Ops_Instrument_InstrumentDisplay_PI1 = 31,
    Nuid_NetDc_Motor_Power_Source_Battery_PO1 = 32,
    Nuid_NetDc_Motor_Power_Convert_Charger_PO2 = 33,
    Nuid_NetDc_Motor_Power_Isolate_Diode_PO2 = 34,
    Nuid_NetDc_Motor_Power_Isolate_SwitchDc_PO1 = 35,
    Nuid_NetDc_Motor_Power_Rotate_StartMotor_PI1 = 36,
    Nuid_NetDc_Level_Power_Source_Battery_PO1 = 37,
    Nuid_NetDc_Level_Power_Convert_Charger_PO1 = 38,
    Nuid_NetDc_Level_Power_Convert_ConvDcDc_PO1 = 39,
    Nuid_NetDc_Level_Power_Isolate_SwitchDc_PO1 = 40,
    Nuid_NetDc_Level_Power_Isolate_Diode_PO3 = 41,
    Nuid_NetDc_Level_Power_Network_Shunt_PO2 = 42,
} ioSystemPortsType;
class ioSystemPorts
{
public:
    ioSystemPorts();
    virtual ~ioSystemPorts();
    static Int32 GetNetworkID(ioSystemPortsType nuid);
    static ioSystemPortsType GetPortType(Int32 nuidValue);
};
#endif // __IOSYSTEMPORTS_H
