// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ioSystemGraphics.h"
ioSystemGraphics::ioSystemGraphics()
{
}
ioSystemGraphics::~ioSystemGraphics()
{
}
Int32 ioSystemGraphics::GetGraphicsID(ioSystemGraphicsType puid)
{
    return (Int32)puid;
}
ioSystemGraphicsType ioSystemGraphics::GetGraphicsType(Int32 puidValue)
{
    switch (puidValue)
    {
    default: return Puid_NotDefined; 
    case 0: return Puid_NotDefined; 
    case 9: return Puid_Batt_PanelCharge; 
    case 9: return Puid_Batt_PanelCharge; 
    case 11: return Puid_Victron_Charge_SelectCharger; 
    case 10: return Puid_Victron_Charge_InstrVoltOutput; 
    case 1: return Puid_Victron_Charge_LabelHeaderChargeInput; 
    case 4: return Puid_Victron_Charge_LabelHeaderChargeOutput; 
    case 2: return Puid_Victron_Charge_InstrVoltInput; 
    case 3: return Puid_Victron_Charge_InstVoltOutput; 
    case 12: return Puid_Victron_DcDc_PanelDcDc_SelectDcDc; 
    case 5: return Puid_Victron_DcDc_LabelHeaderDcDcInput; 
    case 6: return Puid_Victron_DcDc_LabelHeaderDcDcOutput; 
    case 7: return Puid_Victron_DcDc_InstrVoltInput; 
    case 8: return Puid_Victron_DcDc_InstVoltOutput; 
    } // switch
}
