// !!! This C++ file is generated by ioStudio !!!
#if !defined(__IOSYSTEMGRAPHICS_H)
#define __IOSYSTEMGRAPHICS_H
#include "ioSystem/Core/ioTypes.h"
typedef enum
{
    Puid_NotDefined = 0,
    Puid_Batt_LabelBattCharging = 1,
    Puid_Batt_GridChargerInput = 2,
    Puid_Batt_InstrChargeInputVolt = 3,
    Puid_Batt_LabelChargeInputVolt = 4,
    Puid_Batt_GridChargeActive12V = 5,
    Puid_Batt_ShapeActiveCharge12V = 6,
    Puid_Batt_LabelActiveCharge12V = 7,
    Puid_Batt_GridChargeActive24V = 8,
    Puid_Batt_ShapeActiveCharge24V = 9,
    Puid_Batt_LabelActiveCharge24V = 10,
    Puid_Batt_BattPanel12V = 11,
    Puid_Batt_BattPanel24V = 12,
    Puid_Batt_BattStatusGrid = 13,
    Puid_Batt_BattChargingGrid = 14,
    Puid_Batt_LabelStatus = 15,
    Puid_Batt_GridSoc = 16,
    Puid_Batt_InstrSoc = 17,
    Puid_Batt_LabelSoc = 18,
    Puid_Batt_GridTime = 19,
    Puid_Batt_InstrTime = 20,
    Puid_Batt_LabelTime = 21,
    Puid_Batt_Dc12_LabelBatt = 22,
    Puid_Batt_Dc12_GridVolt = 23,
    Puid_Batt_Dc12_InstrVolt = 24,
    Puid_Batt_Dc12_LabelVolt = 25,
    Puid_Batt_Dc12_GridBattAmp = 26,
    Puid_Batt_Dc12_InstrAmpAvg = 27,
    Puid_Batt_Dc12_LabelAmpAvg = 28,
    Puid_Batt_Dc12_InstrAmpDiff = 29,
    Puid_Batt_Dc24_LabelBatt = 30,
    Puid_Batt_Dc24_GridVolt = 31,
    Puid_Batt_Dc24_InstrVolt = 32,
    Puid_Batt_Dc24_LabelVolt = 33,
    Puid_Batt_Dc24_GridBattAmp = 34,
    Puid_Batt_Dc24_InstrAmpAvg = 35,
    Puid_Batt_Dc24_LabelAmpAvg = 36,
    Puid_Batt_Dc24_InstrAmpDiff = 37,
} ioSystemGraphicsType;
class ioSystemGraphics
{
public:
    ioSystemGraphics();
    virtual ~ioSystemGraphics();
    static Int32 GetGraphicsID(ioSystemGraphicsType puid);
    static ioSystemGraphicsType GetGraphicsType(Int32 puidValue);
};
#endif // __IOSYSTEMGRAPHICS_H
