// !!! This C++ file is generated by ioStudio !!!
#if !defined(__IOSYSTEMPORTS_H)
#define __IOSYSTEMPORTS_H
#include "ioSystem/Core/ioTypes.h"
typedef enum
{
    Nuid_NotDefined = 0,
    Nuid_NetEthernet_192_168_10_Ops_Network_OpsBatteryGate_9 = 1,
    Nuid_NetEthernet_192_168_10_Victron_Network_CerboGx_10 = 2,
    Nuid_NetEthernet_192_168_10_Ops_OpsController_11 = 3,
    Nuid_NetEthernet_192_168_10_Ops_OpsInstrumentDisplay_12 = 4,
    Nuid_NetWiFi_192_168_11_Ops_Network_OpsBatteryGate_9 = 5,
    Nuid_NetWiFi_192_168_11_Victron_Network_CerboGx_10 = 6,
    Nuid_NetWiFi_192_168_11_Ops_OpsController_11 = 7,
    Nuid_NetWiFi_192_168_11_Ops_OpsInstrumentDisplay_12 = 8,
    Nuid_NetVeDirect_Victron_Victron_Network_VeDirectToUsbA_VeDirect = 9,
    Nuid_NetVeDirect_Victron_Victron_Network_VeDirectToUsbB_VeDirect = 10,
    Nuid_NetVeDirect_Victron_Victron_Network_CerboGx_VeDirect1 = 11,
    Nuid_NetVeDirect_Victron_Victron_Network_CerboGx_VeDirect2 = 12,
    Nuid_NetVeDirect_Victron_Victron_Network_CerboGx_VeDirect3 = 13,
    Nuid_NetVeDirect_Victron_Ops_Convert_OpsAcDcCharger_VeDirect = 14,
    Nuid_NetVeDirect_Victron_Ops_Convert_OpsDcDcConverter_VeDirect = 15,
    Nuid_NetVeDirect_Victron_Ops_Network_OpsSmartShunt_VeDirect = 16,
    Nuid_NetAc_Dock_Ops_Isolate_OpsPowerSwitch_Input = 17,
    Nuid_NetAc_Dock_Ops_Convert_OpsAcDcCharger_Input = 18,
    Nuid_NetDc_Generator_Ops_Isolate_OpsDiodeIsolator_Input = 19,
    Nuid_NetDc_Generator_Rotate_Source_EngineGenerator_Output = 20,
    Nuid_NetDc_Aux_Ops_Source_OpsLithiumBattery_Pos = 21,
    Nuid_NetDc_Aux_Ops_Isolate_OpsDiodeIsolator_Output1 = 22,
    Nuid_NetDc_Aux_Ops_Isolate_OpsBatteryFuse_Port1 = 23,
    Nuid_NetDc_Aux_Ops_Isolate_OpsPowerSwitch_Input = 24,
    Nuid_NetDc_Aux_Ops_Convert_OpsBatteryCharger_Battery = 25,
    Nuid_NetDc_Aux_Ops_Network_OpsSmartShunt_Output = 26,
    Nuid_NetDc_Aux_Ops_Consume_OpsPowerJunction_Input = 27,
    Nuid_NetDc_Motor_Ops_Source_OpsMotorBattery_Pos = 28,
    Nuid_NetDc_Motor_Ops_Isolate_OpsDiodeIsolator_Output2 = 29,
    Nuid_NetDc_Motor_Ops_Isolate_OpsBatteryFuse_Port1 = 30,
    Nuid_NetDc_Motor_Ops_Convert_OpsBatteryCharger_Motor = 31,
    Nuid_NetDc_Motor_Rotate_Consume_EngineStartMotor_Input = 32,
    Nuid_NetDc_Level_Ops_Isolate_OpsDiodeIsolator_Output3 = 33,
    Nuid_NetDc_Level_Ops_Convert_OpsDcDcConverter_Output = 34,
    Nuid_NetDc_Level_Ops_Isolate_OpsBatteryFuse_Port1 = 35,
    Nuid_NetDc_Level_Ops_Source_OpsLithiumBattery_Pos = 36,
} ioSystemPortsType;
class ioSystemPorts
{
public:
    ioSystemPorts();
    virtual ~ioSystemPorts();
    static Int32 GetNetworkID(ioSystemPortsType nuid);
    static ioSystemPortsType GetPortType(Int32 nuidValue);
};
#endif // __IOSYSTEMPORTS_H
