// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ConsumerModel.h"
ConsumerModel::ConsumerModel()
{
}
ConsumerModel::~ConsumerModel()
{
}
void ConsumerModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&DataModel);
}
void ConsumerModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
