// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CONSUMERMODEL_H)
#define __CONSUMERMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ids/Consume/ConsumerModelData.h"
#include "Programs/Ids/Consume/ConsumerData.h"
class ConsumerModel : public ioModel
{
public:
    ConsumerModel();
    virtual ~ConsumerModel();
    virtual void InitializeItem(void);
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    ConsumerModelData DataModel;
    ConsumerData DataProgram;
};
#endif // __CONSUMERMODEL_H
