// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CONSUMERMODEL_H)
#define __CONSUMERMODEL_H
#include "ioSystem/Simulation/ioModel.h"
class ConsumerModel : public ioModel
{
public:
    ConsumerModel();
    virtual ~ConsumerModel();
    virtual void InitializeItem(void);
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
};
#endif // __CONSUMERMODEL_H
