// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchBoardModel.h"
SwitchBoardModel::SwitchBoardModel()
{
}
SwitchBoardModel::~SwitchBoardModel()
{
}
void SwitchBoardModel::InitializeItem(void)
{
    ioModel::InitializeItem();
}
void SwitchBoardModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
