// !!! This C++ file is generated by ioStudio !!!
#if !defined(__IOSYSTEMDATA_H)
#define __IOSYSTEMDATA_H
#include "ioSystem/Core/ioTypes.h"
#include "ioSystem/Data/ioEnumeration.h"
typedef enum
{
    Duid_NotDefined = 0,
    Duid_Batt_ChargeInputVolt = 1,
    Duid_Batt_IsChargActive12V = 2,
    Duid_Batt_IsChargActive24V = 3,
    Duid_Batt_StatusOfCharge = 4,
    Duid_Batt_TimeTo10Percent = 5,
    Duid_Batt_RequestBattData = 6,
    Duid_Batt_ResponseBattData = 7,
    Duid_Batt_Dc12_BattVolt = 8,
    Duid_Batt_Dc12_BattAmpOut = 9,
    Duid_Batt_Dc12_BattAmpIn = 10,
    Duid_Batt_Dc12_BattAmpAvg = 11,
    Duid_Batt_Dc12_RequestDcData = 12,
    Duid_Batt_Dc12_ResponseDcData = 13,
    Duid_Batt_Dc24_BattVolt = 14,
    Duid_Batt_Dc24_BattAmpOut = 15,
    Duid_Batt_Dc24_BattAmpIn = 16,
    Duid_Batt_Dc24_BattAmpAvg = 17,
    Duid_Batt_Dc24_RequestDcData = 18,
    Duid_Batt_Dc24_ResponseDcData = 19,
} ioSystemDataType;
class TypeUnit : public ioEnumeration
{
public:
    TypeUnit();
    virtual ~TypeUnit();
    virtual Bool GetActiveText(ioString* enumText);
    static const Int32 M_S = 0;
    static const Int32 KT = 1;
    static const Int32 KG = 2;
    static const Int32 NM = 3;
    static const Int32 M = 4;
    static const Int32 _C = 5;
};
class StationModeType : public ioEnumeration
{
public:
    StationModeType();
    virtual ~StationModeType();
    virtual Bool GetActiveText(ioString* enumText);
    static const Int32 NO_COMMAND = 0;
    static const Int32 TAKEN = 1;
    static const Int32 REMOTE_CONTROL = 2;
    static const Int32 TAKEN_AND_LOCKED = 3;
    static const Int32 TAKE_OVER_REQUEST = 4;
};
class ioSystemData
{
public:
    ioSystemData();
    virtual ~ioSystemData();
    static Int32 GetDataID(ioSystemDataType duid);
    static ioSystemDataType GetDataType(Int32 duidValue);
};
#endif // __IOSYSTEMDATA_H
