// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CmdModeRefPanelCpA.h"
#include "Programs/ioSystemGraphics.h"
CmdModeRefPanelCpA::CmdModeRefPanelCpA()
{
    InitializeData();
}
CmdModeRefPanelCpA::~CmdModeRefPanelCpA()
{
}
void CmdModeRefPanelCpA::InitializeData(void)
{
    CmdModeRefPanel::InitializeData();
}
