// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CMDMODEPANEL_H)
#define __CMDMODEPANEL_H
#include "ioSystem/Panels/ioPanel.h"
class CmdModePanel : public ioPanel
{
public:
    CmdModePanel();
    virtual ~CmdModePanel();
    virtual void InitializeData(void);
protected:
    ioGraphics* m_CmdModePanelGraphics[2];
};
#endif // __CMDMODEPANEL_H
