// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CMDMODEPANELCPA_H)
#define __CMDMODEPANELCPA_H
#include "CmdModePanel.h"
class CmdModePanelCpA : public CmdModePanel
{
public:
    CmdModePanelCpA();
    virtual ~CmdModePanelCpA();
    virtual void InitializeData(void);
};
#endif // __CMDMODEPANELCPA_H
