// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CMDMODEPANELCPM_H)
#define __CMDMODEPANELCPM_H
#include "CmdModePanel.h"
class CmdModePanelCpM : public CmdModePanel
{
public:
    CmdModePanelCpM();
    virtual ~CmdModePanelCpM();
    virtual void InitializeData(void);
};
#endif // __CMDMODEPANELCPM_H
