// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CmdModeRefPanelCpM.h"
#include "Programs/ioSystemGraphics.h"
CmdModeRefPanelCpM::CmdModeRefPanelCpM()
{
    InitializeData();
}
CmdModeRefPanelCpM::~CmdModeRefPanelCpM()
{
}
void CmdModeRefPanelCpM::InitializeData(void)
{
    CmdModeRefPanel::InitializeData();
}
