// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CmdModePanel.h"
CmdModePanel::CmdModePanel()
{
}
CmdModePanel::~CmdModePanel()
{
}
void CmdModePanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_CmdModePanelGraphics, 2);
}
