// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CMDPANELSTEERCPA_H)
#define __CMDPANELSTEERCPA_H
#include "CmdPanelSteer.h"
class CmdPanelSteerCpA : public CmdPanelSteer
{
public:
    CmdPanelSteerCpA();
    virtual ~CmdPanelSteerCpA();
    virtual void InitializeData(void);
};
#endif // __CMDPANELSTEERCPA_H
