// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CmdPanelSteerCpA.h"
#include "Programs/ioSystemGraphics.h"
CmdPanelSteerCpA::CmdPanelSteerCpA()
{
    InitializeData();
}
CmdPanelSteerCpA::~CmdPanelSteerCpA()
{
}
void CmdPanelSteerCpA::InitializeData(void)
{
    CmdPanelSteer::InitializeData();
    AddGraphics(&HeaderCommandPanelSteer, Puid_Steer_CpA_HeaderCommandPanelSteer);
    HeaderCommandPanelSteer.SetTextForced((ioChars)"COMMAND STEERING AFT COCKPIT");
    AddGraphics(&ShapeCommandStatusSteer, Puid_Steer_CpA_ShapeCommandStatusSteer);
    AddGraphics(&LabelSteerMode, Puid_Steer_CpA_LabelSteerMode);
    LabelSteerMode.SetTextForced((ioChars)"OFF");
    AddGraphics(&TextCommandStatusSteer, Puid_Steer_CpA_TextCommandStatusSteer);
    TextCommandStatusSteer.SetTextForced((ioChars)"No station in command");
    TextCommandStatusSteer.SetDecimals(1);
    AddGraphics(&ButtTakeRequestSteer, Puid_Steer_CpA_ButtTakeRequestSteer);
    ButtTakeRequestSteer.SetTextForced((ioChars)"Take");
    AddGraphics(&ButtReleaseSteer, Puid_Steer_CpA_ButtReleaseSteer);
    ButtReleaseSteer.SetTextForced((ioChars)"Release");
}
