// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CmdPanelSteer.h"
CmdPanelSteer::CmdPanelSteer()
{
}
CmdPanelSteer::~CmdPanelSteer()
{
}
void CmdPanelSteer::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_CmdPanelSteerGraphics, 6);
}
