// !!! This C++ file is generated by ioStudio !!!
#if !defined(__COMMANDPANELCPM_H)
#define __COMMANDPANELCPM_H
#include "CommandPanel.h"
class CommandPanelCpM : public CommandPanel
{
public:
    CommandPanelCpM();
    virtual ~CommandPanelCpM();
    virtual void InitializeData(void);
};
#endif // __COMMANDPANELCPM_H
