// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CommandPanelCpM.h"
CommandPanelCpM::CommandPanelCpM()
{
    InitializeData();
}
CommandPanelCpM::~CommandPanelCpM()
{
}
void CommandPanelCpM::InitializeData(void)
{
    CommandPanel::InitializeData();
    TextCommandStatus.SetDecimals(1);
}
