// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CommandPanelCp2.h"
CommandPanelCp2::CommandPanelCp2()
{
    InitializeData();
}
CommandPanelCp2::~CommandPanelCp2()
{
}
void CommandPanelCp2::InitializeData(void)
{
    CommandPanel::InitializeData();
    TextCommandStatus.SetDecimals(1);
}
