// !!! This C++ file is generated by ioStudio !!!
#if !defined(__COMMANDPANELCPA_H)
#define __COMMANDPANELCPA_H
#include "CommandPanel.h"
class CommandPanelCpA : public CommandPanel
{
public:
    CommandPanelCpA();
    virtual ~CommandPanelCpA();
    virtual void InitializeData(void);
};
#endif // __COMMANDPANELCPA_H
