// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CommandPanel.h"
CommandPanel::CommandPanel()
{
}
CommandPanel::~CommandPanel()
{
}
void CommandPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_CommandPanelGraphics, 6);
}
