// !!! This C++ file is generated by ioStudio !!!
#if !defined(__COMMANDPANEL_H)
#define __COMMANDPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioShape.h"
#include "ioSystem/Panels/ioButtonText.h"
class CommandPanel : public ioPanel
{
public:
    CommandPanel();
    virtual ~CommandPanel();
    virtual void InitializeData(void);
    ioLabel HeaderCommandPanel;
    ioShape ShapeCommandStatus;
    ioLabel LabelCommandStatus;
    ioTextBlock TextCommandStatus;
    ioButtonShape ButtTakeRequest;
    ioButtonShape ButtRelease;
protected:
    ioGraphics* m_CommandPanelGraphics[6];
};
#endif // __COMMANDPANEL_H
