// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "CommandPanelCp1.h"
CommandPanelCp1::CommandPanelCp1()
{
    InitializeData();
}
CommandPanelCp1::~CommandPanelCp1()
{
}
void CommandPanelCp1::InitializeData(void)
{
    CommandPanel::InitializeData();
    TextCommandStatus.SetDecimals(1);
}
