// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ModePanel.h"
ModePanel::ModePanel()
{
}
ModePanel::~ModePanel()
{
}
void ModePanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_ModePanelGraphics, 7);
}
