// !!! This C++ file is generated by ioStudio !!!
#if !defined(__MODEPANEL_H)
#define __MODEPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioButtonText.h"
class ModePanel : public ioPanel
{
public:
    ModePanel();
    virtual ~ModePanel();
    virtual void InitializeData(void);
    ioLabel HeaderModeControl;
    ioButtonShape ButtDp;
    ioButtonShape ButtTrack;
    ioButtonShape ButtRiver;
    ioButtonShape ButtWork;
    ioButtonShape ButtCourse;
    ioButtonShape ButtStandby;
protected:
    ioGraphics* m_ModePanelGraphics[7];
};
#endif // __MODEPANEL_H
