// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ModePanelCpM.h"
ModePanelCpM::ModePanelCpM()
{
    InitializeData();
}
ModePanelCpM::~ModePanelCpM()
{
}
void ModePanelCpM::InitializeData(void)
{
    ModePanel::InitializeData();
}
