// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ModePanelCpA.h"
ModePanelCpA::ModePanelCpA()
{
    InitializeData();
}
ModePanelCpA::~ModePanelCpA()
{
}
void ModePanelCpA::InitializeData(void)
{
    ModePanel::InitializeData();
}
