// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefPanelCpM.h"
SetRefPanelCpM::SetRefPanelCpM()
{
    InitializeData();
}
SetRefPanelCpM::~SetRefPanelCpM()
{
}
void SetRefPanelCpM::InitializeData(void)
{
    SetRefPanel::InitializeData();
}
