// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFPANELCP2_H)
#define __SETREFPANELCP2_H
#include "SetRefPanel.h"
class SetRefPanelCp2 : public SetRefPanel
{
public:
    SetRefPanelCp2();
    virtual ~SetRefPanelCp2();
    virtual void InitializeData(void);
};
#endif // __SETREFPANELCP2_H
