// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetRefPanelCpA.h"
SetRefPanelCpA::SetRefPanelCpA()
{
    InitializeData();
}
SetRefPanelCpA::~SetRefPanelCpA()
{
}
void SetRefPanelCpA::InitializeData(void)
{
    SetRefPanel::InitializeData();
}
