// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFPANELCPM_H)
#define __SETREFPANELCPM_H
#include "SetRefPanel.h"
class SetRefPanelCpM : public SetRefPanel
{
public:
    SetRefPanelCpM();
    virtual ~SetRefPanelCpM();
    virtual void InitializeData(void);
};
#endif // __SETREFPANELCPM_H
