// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETREFPANELCPA_H)
#define __SETREFPANELCPA_H
#include "SetRefPanel.h"
class SetRefPanelCpA : public SetRefPanel
{
public:
    SetRefPanelCpA();
    virtual ~SetRefPanelCpA();
    virtual void InitializeData(void);
};
#endif // __SETREFPANELCPA_H
