// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerCpData.h"
SteerCpData::SteerCpData()
{
}
SteerCpData::~SteerCpData()
{
}
void SteerCpData::InitializeData(void)
{
    SetListData(m_ListData, 19);
    ResetItem();
    OnChangeCommand.SetVariablesBuffer(m_OnChangeCommandVars, 2);
    OnChangeCommand.AddVariable(&ActiveStation);
    OnChangeCommand.AddVariable(&StationMode);
    OnChangeSteerMode.SetVariablesBuffer(m_OnChangeSteerModeVars, 1);
    OnChangeSteerMode.AddVariable(&SteerMode);
}
