// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerCpData.h"
SteerCpData::SteerCpData()
{
}
SteerCpData::~SteerCpData()
{
}
void SteerCpData::InitializeData(void)
{
    SetListData(m_ListData, 17);
    ResetItem();
}
