// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERCPDATA_H)
#define __STEERCPDATA_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioEnumeration.h"
#include "ioSystem/Data/ioEvent.h"
#include "ioSystem/Data/ioMethod.h"
class SteerModeType : public ioEnumeration
{
public:
    SteerModeType();
    virtual ~SteerModeType();
    virtual Bool GetActiveText(ioString* enumText);
    static const Int32 STANDBY = 0;
    static const Int32 RIVER = 1;
    static const Int32 AUTO = 2;
    static const Int32 TRACK = 3;
    static const Int32 WORK = 4;
    static const Int32 DP = 5;
};
class SteerStationType : public ioEnumeration
{
public:
    SteerStationType();
    virtual ~SteerStationType();
    virtual Bool GetActiveText(ioString* enumText);
    static const Int32 STEER_AT_MID_DECKHOUSE = 0;
    static const Int32 STEER_AT_AFT_COCKPIT = 1;
};
class SteerCpData : public ioDataCollection
{
public:
    SteerCpData();
    virtual ~SteerCpData();
    virtual void InitializeData(void);
    SteerStationType ActiveStationSteer;
    StationModeType StationModeSteer;
    ioMethod TakeCommandSteer;
    ioMethod ReleaseCommandSteer;
    ioEvent OnChangeCommandSteer;
    ioMethod ModeDp;
    ioMethod ModeRiver;
    ioMethod ModeTrack;
    ioMethod ModeWork;
    ioMethod ModeAuto;
    ioMethod ModeStandby;
    SteerModeType SteerMode;
    ioEvent OnChangeSteerMode;
    ioMethod LeftSmall;
    ioMethod MidZero;
    ioMethod RightSmall;
    ioMethod LeftBig;
    ioMethod RightBig;
    ioMethod EncoderNumber;
protected:
    ioData* m_ListData[19];
    ioVar* m_OnChangeCommandSteerVars[2];
    ioVar* m_OnChangeSteerModeVars[1];
};
#endif // __STEERCPDATA_H
