// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERCPDATACPM_H)
#define __STEERCPDATACPM_H
#include "SteerCpData.h"
class SteerCpDataCpM : public SteerCpData
{
public:
    SteerCpDataCpM();
    virtual ~SteerCpDataCpM();
    virtual void InitializeData(void);
};
#endif // __STEERCPDATACPM_H
