// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerCpDataCpA.h"
SteerCpDataCpA::SteerCpDataCpA()
{
    InitializeData();
}
SteerCpDataCpA::~SteerCpDataCpA()
{
}
void SteerCpDataCpA::InitializeData(void)
{
    SteerCpData::InitializeData();
    ActiveStationSteer.SetValueSigned(1);
    AddData((ioData*)&ActiveStationSteer, Duid_Steer_CpA_ActiveStationSteer);
    StationModeSteer.SetValueSigned(0);
    AddData((ioData*)&StationModeSteer, Duid_Steer_CpA_StationModeSteer);
    AddData((ioData*)&TakeCommandSteer, Duid_Steer_CpA_TakeCommandSteer);
    AddData((ioData*)&ReleaseCommandSteer, Duid_Steer_CpA_ReleaseCommandSteer);
    AddData((ioData*)&OnChangeCommandSteer, Duid_Steer_CpA_OnChangeCommandSteer);
    AddData((ioData*)&ModeDp, Duid_Steer_CpA_ModeDp);
    AddData((ioData*)&ModeRiver, Duid_Steer_CpA_ModeRiver);
    AddData((ioData*)&ModeTrack, Duid_Steer_CpA_ModeTrack);
    AddData((ioData*)&ModeWork, Duid_Steer_CpA_ModeWork);
    AddData((ioData*)&ModeAuto, Duid_Steer_CpA_ModeAuto);
    AddData((ioData*)&ModeStandby, Duid_Steer_CpA_ModeStandby);
    SteerMode.SetValueSigned(0);
    AddData((ioData*)&SteerMode, Duid_Steer_CpA_SteerMode);
    AddData((ioData*)&OnChangeSteerMode, Duid_Steer_CpA_OnChangeSteerMode);
    AddData((ioData*)&LeftSmall, Duid_Steer_CpA_LeftSmall);
    AddData((ioData*)&MidZero, Duid_Steer_CpA_MidZero);
    AddData((ioData*)&RightSmall, Duid_Steer_CpA_RightSmall);
    AddData((ioData*)&LeftBig, Duid_Steer_CpA_LeftBig);
    AddData((ioData*)&RightBig, Duid_Steer_CpA_RightBig);
    AddData((ioData*)&EncoderNumber, Duid_Steer_CpA_EncoderNumber);
}
