// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERCPDATACP2_H)
#define __STEERCPDATACP2_H
#include "SteerCpData.h"
class SteerCpDataCp2 : public SteerCpData
{
public:
    SteerCpDataCp2();
    virtual ~SteerCpDataCp2();
    virtual void InitializeData(void);
};
#endif // __STEERCPDATACP2_H
