// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SteerCpDataCp1.h"
SteerCpDataCp1::SteerCpDataCp1()
{
    InitializeData();
}
SteerCpDataCp1::~SteerCpDataCp1()
{
}
void SteerCpDataCp1::InitializeData(void)
{
    SteerCpData::InitializeData();
    AddData((ioData*)&TakeCommand, Duid_Steer_Cp1_TakeCommand);
    AddData((ioData*)&ModeDp, Duid_Steer_Cp1_ModeDp);
    AddData((ioData*)&ModeRiver, Duid_Steer_Cp1_ModeRiver);
    AddData((ioData*)&ModeTrack, Duid_Steer_Cp1_ModeTrack);
    AddData((ioData*)&ModeWork, Duid_Steer_Cp1_ModeWork);
    AddData((ioData*)&ModeAuto, Duid_Steer_Cp1_ModeAuto);
    AddData((ioData*)&ModeStandby, Duid_Steer_Cp1_ModeStandby);
    SteerMode.SetValueSigned(0);
    AddData((ioData*)&SteerMode, Duid_Steer_Cp1_SteerMode);
    AddData((ioData*)&Release, Duid_Steer_Cp1_Release);
    AddData((ioData*)&OnChangeCommand, Duid_Steer_Cp1_OnChangeCommand);
    AddData((ioData*)&OnChangeSteerMode, Duid_Steer_Cp1_OnChangeSteerMode);
    AddData((ioData*)&LeftSmall, Duid_Steer_Cp1_LeftSmall);
    AddData((ioData*)&MidZero, Duid_Steer_Cp1_MidZero);
    AddData((ioData*)&RightSmall, Duid_Steer_Cp1_RightSmall);
    AddData((ioData*)&LeftBig, Duid_Steer_Cp1_LeftBig);
    AddData((ioData*)&RightBig, Duid_Steer_Cp1_RightBig);
    AddData((ioData*)&EncoderNumber, Duid_Steer_Cp1_EncoderNumber);
}
