// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERCPDATACP1_H)
#define __STEERCPDATACP1_H
#include "SteerCpData.h"
class SteerCpDataCp1 : public SteerCpData
{
public:
    SteerCpDataCp1();
    virtual ~SteerCpDataCp1();
    virtual void InitializeData(void);
};
#endif // __STEERCPDATACP1_H
