// !!! This C++ file is generated by ioStudio !!!
#if !defined(__STEERCPDATACPA_H)
#define __STEERCPDATACPA_H
#include "SteerCpData.h"
class SteerCpDataCpA : public SteerCpData
{
public:
    SteerCpDataCpA();
    virtual ~SteerCpDataCpA();
    virtual void InitializeData(void);
};
#endif // __STEERCPDATACPA_H
