// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ChargeModel.h"
ChargeModel::ChargeModel()
{
}
ChargeModel::~ChargeModel()
{
}
// Initialize simulation model
void ChargeModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&ChargeData);
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void ChargeModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
void ChargeModel::SimulateVoltOutput(Float voltInputAc, Bool isOutputActive, Float* voltOutputDc)
{
}
