// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CHARGEMODEL_H)
#define __CHARGEMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ids/Convert/DataCharge.h"
class ChargeModel : public ioModel
{
public:
    ChargeModel();
    virtual ~ChargeModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    virtual void SimulateVoltOutput(Float voltInputAc, Bool isOutputActive, Float* voltOutputDc);
    DataCharge ChargeData;
};
#endif // __CHARGEMODEL_H
