// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ConningInstrPanel.h"
#include "Programs/ioSystemGraphics.h"
ConningInstrPanel::ConningInstrPanel()
{
}
ConningInstrPanel::~ConningInstrPanel()
{
}
void ConningInstrPanel::InitializeData(void)
{
}
