// !!! This C++ file is generated by ioStudio !!!
#if !defined(__INSTRUMENTYAW_H)
#define __INSTRUMENTYAW_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class InstrumentYaw : public ioPanel
{
public:
    InstrumentYaw();
    virtual ~InstrumentYaw();
    virtual void InitializeData(void);
    ioLabel LabelHdgCmdInstrHeader;
    ioLabel LabelHdgCmdInstrHeaderUnit;
    ioLabel LabelHdgInstrHeader;
    ioLabel LabelHdgInstrHeaderUnit;
    ioTextBlock InstrHdgCmdInstr;
    ioTextBlock InstrHdgInstr;
protected:
    ioGraphics* m_InstrumentYawGraphics[6];
};
#endif // __INSTRUMENTYAW_H
