// !!! This C++ file is generated by ioStudio !!!
#if !defined(__INSTRUMENTWIND_H)
#define __INSTRUMENTWIND_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioIcon.h"
class InstrumentWind : public ioPanel
{
public:
    InstrumentWind();
    virtual ~InstrumentWind();
    virtual void InitializeData(void);
    ioLabel LabelAwaInstrHeader;
    ioLabel LabelAwaInstrHeaderUnit;
    ioLabel LabelAwsInstrHeader;
    ioLabel LabelAwsInstrHeaderUnit;
    ioLabel LabelWDirInstrHeader;
    ioLabel LabelWDirInstrHeaderUnit;
    ioLabel LabelWSpdInstrHeader;
    ioLabel LabelWSpdInstrHeaderUnit;
    ioIcon IconAwaInstrLeft;
    ioTextBlock InstrAwaInstr;
    ioIcon IconAwaInstrRight;
    ioTextBlock InstrAwsInstr;
    ioTextBlock InstrWDirInstr;
    ioTextBlock InstrWSpdInstr;
protected:
    ioGraphics* m_InstrumentWindGraphics[14];
};
#endif // __INSTRUMENTWIND_H
