// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetDriftInstrPanel.h"
#include "Programs/ioSystemGraphics.h"
SetDriftInstrPanel::SetDriftInstrPanel()
{
}
SetDriftInstrPanel::~SetDriftInstrPanel()
{
}
void SetDriftInstrPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SetDriftInstrPanelGraphics, 42);
    AddGraphics(&LabelWindCmdHeaderDrf, Puid_Ids_Pilot_LabelWindCmdHeaderDrf);
    LabelWindCmdHeaderDrf.SetTextForced((ioChars)"WCMD");
    AddGraphics(&LabelWindCmdHeaderUnitDrf, Puid_Ids_Pilot_LabelWindCmdHeaderUnitDrf);
    LabelWindCmdHeaderUnitDrf.SetTextForced((ioChars)"°");
    AddGraphics(&LabelSetAngleHeader, Puid_Ids_Pilot_LabelSetAngleHeader);
    LabelSetAngleHeader.SetTextForced((ioChars)"SET");
    AddGraphics(&LabelSetAngleHeaderUnit, Puid_Ids_Pilot_LabelSetAngleHeaderUnit);
    LabelSetAngleHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&LabelDriftHeader, Puid_Ids_Pilot_LabelDriftHeader);
    LabelDriftHeader.SetTextForced((ioChars)"DRIFT");
    AddGraphics(&LabelDriftHeaderUnit, Puid_Ids_Pilot_LabelDriftHeaderUnit);
    LabelDriftHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&LabelCogHeader, Puid_Ids_Pilot_LabelCogHeader);
    LabelCogHeader.SetTextForced((ioChars)"COG");
    AddGraphics(&LabelCogHeaderUnit, Puid_Ids_Pilot_LabelCogHeaderUnit);
    LabelCogHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&LabelSogHeader, Puid_Ids_Pilot_LabelSogHeader);
    LabelSogHeader.SetTextForced((ioChars)"SOG");
    AddGraphics(&LabelSogHeaderUnit, Puid_Ids_Pilot_LabelSogHeaderUnit);
    LabelSogHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&LabelHdgHeader, Puid_Ids_Pilot_LabelHdgHeader);
    LabelHdgHeader.SetTextForced((ioChars)"HDG");
    AddGraphics(&LabelHdgHeaderUnit, Puid_Ids_Pilot_LabelHdgHeaderUnit);
    LabelHdgHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&IconWcmdLeft, Puid_Ids_Pilot_IconWcmdLeft);
    AddGraphics(&InstrWindCmdDrf, Puid_Ids_Pilot_InstrWindCmdDrf);
    InstrWindCmdDrf.SetTextForced((ioChars)"0");
    InstrWindCmdDrf.SetDecimals(1);
    AddGraphics(&IconWcmdRight, Puid_Ids_Pilot_IconWcmdRight);
    AddGraphics(&InstrSetAngle, Puid_Ids_Pilot_InstrSetAngle);
    InstrSetAngle.SetTextForced((ioChars)"000");
    InstrSetAngle.SetDecimals(1);
    AddGraphics(&InstrDrift, Puid_Ids_Pilot_InstrDrift);
    InstrDrift.SetTextForced((ioChars)"0.0");
    InstrDrift.SetDecimals(1);
    AddGraphics(&InstrCog, Puid_Ids_Pilot_InstrCog);
    InstrCog.SetTextForced((ioChars)"0.0");
    InstrCog.SetDecimals(1);
    AddGraphics(&InstrSog, Puid_Ids_Pilot_InstrSog);
    InstrSog.SetTextForced((ioChars)"0.0");
    InstrSog.SetDecimals(1);
    AddGraphics(&InstrHdg, Puid_Ids_Pilot_InstrHdg);
    InstrHdg.SetTextForced((ioChars)"000.0");
    InstrHdg.SetDecimals(1);
    AddGraphics(&LabelAwaHeader, Puid_Ids_Pilot_LabelAwaHeader);
    LabelAwaHeader.SetTextForced((ioChars)"AWA");
    AddGraphics(&LabelAwaHeaderUnit, Puid_Ids_Pilot_LabelAwaHeaderUnit);
    LabelAwaHeaderUnit.SetTextForced((ioChars)"°");
    AddGraphics(&LabelTwaHeader, Puid_Ids_Pilot_LabelTwaHeader);
    LabelTwaHeader.SetTextForced((ioChars)"TWA");
    AddGraphics(&LabelTwaHeaderUnit, Puid_Ids_Pilot_LabelTwaHeaderUnit);
    LabelTwaHeaderUnit.SetTextForced((ioChars)"°");
    AddGraphics(&LabelAwsHeader, Puid_Ids_Pilot_LabelAwsHeader);
    LabelAwsHeader.SetTextForced((ioChars)"AWS");
    AddGraphics(&LabelAwsHeaderUnit, Puid_Ids_Pilot_LabelAwsHeaderUnit);
    LabelAwsHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&LabelWdirHeader, Puid_Ids_Pilot_LabelWdirHeader);
    LabelWdirHeader.SetTextForced((ioChars)"WDIR");
    AddGraphics(&LabelWdirHeaderUnit, Puid_Ids_Pilot_LabelWdirHeaderUnit);
    LabelWdirHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&LabelDepthHeader, Puid_Ids_Pilot_LabelDepthHeader);
    LabelDepthHeader.SetTextForced((ioChars)"DPT");
    AddGraphics(&LabelDepthHeaderUnit, Puid_Ids_Pilot_LabelDepthHeaderUnit);
    LabelDepthHeaderUnit.SetTextForced((ioChars)"m");
    AddGraphics(&LabelSpeedHeader, Puid_Ids_Pilot_LabelSpeedHeader);
    LabelSpeedHeader.SetTextForced((ioChars)"STW");
    AddGraphics(&LabelSpeedHeaderUnit, Puid_Ids_Pilot_LabelSpeedHeaderUnit);
    LabelSpeedHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&IconAwaLeft, Puid_Ids_Pilot_IconAwaLeft);
    AddGraphics(&InstrAwa, Puid_Ids_Pilot_InstrAwa);
    InstrAwa.SetTextForced((ioChars)"0");
    InstrAwa.SetDecimals(1);
    AddGraphics(&IconAwaRight, Puid_Ids_Pilot_IconAwaRight);
    AddGraphics(&IconTwaLeft, Puid_Ids_Pilot_IconTwaLeft);
    AddGraphics(&InstrTwa, Puid_Ids_Pilot_InstrTwa);
    InstrTwa.SetTextForced((ioChars)"0");
    InstrTwa.SetDecimals(1);
    AddGraphics(&IconTwaRight, Puid_Ids_Pilot_IconTwaRight);
    AddGraphics(&InstrAws, Puid_Ids_Pilot_InstrAws);
    InstrAws.SetTextForced((ioChars)"0.0");
    InstrAws.SetDecimals(1);
    AddGraphics(&InstrWdir, Puid_Ids_Pilot_InstrWdir);
    InstrWdir.SetTextForced((ioChars)"000");
    InstrWdir.SetDecimals(1);
    AddGraphics(&InstrDepth, Puid_Ids_Pilot_InstrDepth);
    InstrDepth.SetTextForced((ioChars)"0.0");
    InstrDepth.SetDecimals(1);
    AddGraphics(&InstrSpeed, Puid_Ids_Pilot_InstrSpeed);
    InstrSpeed.SetTextForced((ioChars)"0.0");
    InstrSpeed.SetDecimals(1);
}
