// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SetDriftInstrPanel.h"
#include "Programs/ioSystemGraphics.h"
SetDriftInstrPanel::SetDriftInstrPanel()
{
}
SetDriftInstrPanel::~SetDriftInstrPanel()
{
}
void SetDriftInstrPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_SetDriftInstrPanelGraphics, 25);
    AddGraphics(&LabelWindCmdHeader, Puid_Ids_Pilot_LabelWindCmdHeader);
    LabelWindCmdHeader.SetTextForced((ioChars)"WCMD");
    AddGraphics(&LabelWindCmdHeaderUnit, Puid_Ids_Pilot_LabelWindCmdHeaderUnit);
    LabelWindCmdHeaderUnit.SetTextForced((ioChars)"°");
    AddGraphics(&LabelSetAngleHeader, Puid_Ids_Pilot_LabelSetAngleHeader);
    LabelSetAngleHeader.SetTextForced((ioChars)"SET");
    AddGraphics(&LabelSetAngleHeaderUnit, Puid_Ids_Pilot_LabelSetAngleHeaderUnit);
    LabelSetAngleHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&LabelDriftHeader, Puid_Ids_Pilot_LabelDriftHeader);
    LabelDriftHeader.SetTextForced((ioChars)"DRIFT");
    AddGraphics(&LabelDriftHeaderUnit, Puid_Ids_Pilot_LabelDriftHeaderUnit);
    LabelDriftHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&LabelCogHeader, Puid_Ids_Pilot_LabelCogHeader);
    LabelCogHeader.SetTextForced((ioChars)"COG");
    AddGraphics(&LabelCogHeaderUnit, Puid_Ids_Pilot_LabelCogHeaderUnit);
    LabelCogHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&LabelSogHeader, Puid_Ids_Pilot_LabelSogHeader);
    LabelSogHeader.SetTextForced((ioChars)"SOG");
    AddGraphics(&LabelSogHeaderUnit, Puid_Ids_Pilot_LabelSogHeaderUnit);
    LabelSogHeaderUnit.SetTextForced((ioChars)"kn");
    AddGraphics(&LabelHdgHeader, Puid_Ids_Pilot_LabelHdgHeader);
    LabelHdgHeader.SetTextForced((ioChars)"HDG");
    AddGraphics(&LabelHdgHeaderUnit, Puid_Ids_Pilot_LabelHdgHeaderUnit);
    LabelHdgHeaderUnit.SetTextForced((ioChars)"°T");
    AddGraphics(&IconWcmdLeft, Puid_Ids_Pilot_IconWcmdLeft);
    AddGraphics(&InstrWindCmd, Puid_Ids_Pilot_InstrWindCmd);
    InstrWindCmd.SetTextForced((ioChars)"0");
    InstrWindCmd.SetDecimals(1);
    AddGraphics(&IconWcmdRight, Puid_Ids_Pilot_IconWcmdRight);
    AddGraphics(&InstrSetAngle, Puid_Ids_Pilot_InstrSetAngle);
    InstrSetAngle.SetTextForced((ioChars)"000");
    InstrSetAngle.SetDecimals(1);
    AddGraphics(&InstrDrift, Puid_Ids_Pilot_InstrDrift);
    InstrDrift.SetTextForced((ioChars)"0.0");
    InstrDrift.SetDecimals(1);
    AddGraphics(&InstrCog, Puid_Ids_Pilot_InstrCog);
    InstrCog.SetTextForced((ioChars)"0.0");
    InstrCog.SetDecimals(1);
    AddGraphics(&InstrSog, Puid_Ids_Pilot_InstrSog);
    InstrSog.SetTextForced((ioChars)"0.0");
    InstrSog.SetDecimals(1);
    AddGraphics(&InstrHdg, Puid_Ids_Pilot_InstrHdg);
    InstrHdg.SetTextForced((ioChars)"000.0");
    InstrHdg.SetDecimals(1);
    AddGraphics(&LabelAwaHeader, Puid_Ids_Pilot_LabelAwaHeader);
    LabelAwaHeader.SetTextForced((ioChars)"AWA");
    AddGraphics(&LabelAwaHeaderUnit, Puid_Ids_Pilot_LabelAwaHeaderUnit);
    LabelAwaHeaderUnit.SetTextForced((ioChars)"°");
    AddGraphics(&IconAwaLeft, Puid_Ids_Pilot_IconAwaLeft);
    AddGraphics(&InstrAwa, Puid_Ids_Pilot_InstrAwa);
    InstrAwa.SetTextForced((ioChars)"0");
    InstrAwa.SetDecimals(1);
    AddGraphics(&IconAwaRight, Puid_Ids_Pilot_IconAwaRight);
}
