// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SETDRIFTINSTRPANEL_H)
#define __SETDRIFTINSTRPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
#include "ioSystem/Panels/ioIcon.h"
class SetDriftInstrPanel : public ioPanel
{
public:
    SetDriftInstrPanel();
    virtual ~SetDriftInstrPanel();
    virtual void InitializeData(void);
    ioLabel LabelWindCmdHeader;
    ioLabel LabelWindCmdHeaderUnit;
    ioLabel LabelSetAngleHeader;
    ioLabel LabelSetAngleHeaderUnit;
    ioLabel LabelDriftHeader;
    ioLabel LabelDriftHeaderUnit;
    ioLabel LabelCogHeader;
    ioLabel LabelCogHeaderUnit;
    ioLabel LabelSogHeader;
    ioLabel LabelSogHeaderUnit;
    ioLabel LabelHdgHeader;
    ioLabel LabelHdgHeaderUnit;
    ioIcon IconWcmdLeft;
    ioTextBlock InstrWindCmd;
    ioIcon IconWcmdRight;
    ioTextBlock InstrSetAngle;
    ioTextBlock InstrDrift;
    ioTextBlock InstrCog;
    ioTextBlock InstrSog;
    ioTextBlock InstrHdg;
    ioLabel LabelAwaHeader;
    ioLabel LabelAwaHeaderUnit;
    ioIcon IconAwaLeft;
    ioTextBlock InstrAwa;
    ioIcon IconAwaRight;
protected:
    ioGraphics* m_SetDriftInstrPanelGraphics[25];
};
#endif // __SETDRIFTINSTRPANEL_H
