// !!! This C++ file is generated by ioStudio !!!
#if !defined(__SPEEDANGLESPANEL_H)
#define __SPEEDANGLESPANEL_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class SpeedAnglesPanel : public ioPanel
{
public:
    SpeedAnglesPanel();
    virtual ~SpeedAnglesPanel();
    virtual void InitializeData(void);
    ioLabel LabelBtwHeader;
    ioLabel LabelBtwHeaderUnit;
    ioTextBlock InstrBtw;
    ioLabel LabelDtwHeader;
    ioLabel LabelDtwHeaderUnit;
    ioTextBlock InstrDtw;
    ioLabel LabelRollHeader;
    ioLabel LabelRollHeaderUnit;
    ioTextBlock InstrRoll;
    ioLabel LabelPitchHeader;
    ioLabel LabelPitchHeaderUnit;
    ioTextBlock InstPitch;
protected:
    ioGraphics* m_SpeedAnglesPanelGraphics[12];
};
#endif // __SPEEDANGLESPANEL_H
