// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWERINDICATORPANEL_H)
#define __POWERINDICATORPANEL_H
#include "ioSystem/Panels/ioPanel.h"
class PowerIndicatorPanel : public ioPanel
{
public:
    PowerIndicatorPanel();
    virtual ~PowerIndicatorPanel();
    virtual void InitializeData(void);
protected:
    ioGraphics* m_PowerIndicatorPanelGraphics[3];
};
#endif // __POWERINDICATORPANEL_H
