// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowerIndicatorPanelOut12V.h"
#include "Programs/ioSystemGraphics.h"
PowerIndicatorPanelOut12V::PowerIndicatorPanelOut12V()
{
    InitializeData();
}
PowerIndicatorPanelOut12V::~PowerIndicatorPanelOut12V()
{
}
void PowerIndicatorPanelOut12V::InitializeData(void)
{
    PowerIndicatorPanel::InitializeData();
}
