// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowerIndicatorPanelOut24V.h"
#include "Programs/ioSystemGraphics.h"
PowerIndicatorPanelOut24V::PowerIndicatorPanelOut24V()
{
    InitializeData();
}
PowerIndicatorPanelOut24V::~PowerIndicatorPanelOut24V()
{
}
void PowerIndicatorPanelOut24V::InitializeData(void)
{
    PowerIndicatorPanel::InitializeData();
}
