// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWERINDICATORPANELOUT12V_H)
#define __POWERINDICATORPANELOUT12V_H
#include "PowerIndicatorPanel.h"
class PowerIndicatorPanelOut12V : public PowerIndicatorPanel
{
public:
    PowerIndicatorPanelOut12V();
    virtual ~PowerIndicatorPanelOut12V();
    virtual void InitializeData(void);
};
#endif // __POWERINDICATORPANELOUT12V_H
