// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWERINDICATORPANELOUT220V_H)
#define __POWERINDICATORPANELOUT220V_H
#include "PowerIndicatorPanel.h"
class PowerIndicatorPanelOut220V : public PowerIndicatorPanel
{
public:
    PowerIndicatorPanelOut220V();
    virtual ~PowerIndicatorPanelOut220V();
    virtual void InitializeData(void);
};
#endif // __POWERINDICATORPANELOUT220V_H
