// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWERINDICATORPANELOUT24V_H)
#define __POWERINDICATORPANELOUT24V_H
#include "PowerIndicatorPanel.h"
class PowerIndicatorPanelOut24V : public PowerIndicatorPanel
{
public:
    PowerIndicatorPanelOut24V();
    virtual ~PowerIndicatorPanelOut24V();
    virtual void InitializeData(void);
};
#endif // __POWERINDICATORPANELOUT24V_H
