// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowerIndicatorPanel.h"
PowerIndicatorPanel::PowerIndicatorPanel()
{
}
PowerIndicatorPanel::~PowerIndicatorPanel()
{
}
void PowerIndicatorPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_PowerIndicatorPanelGraphics, 3);
}
