// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "OrionTrSmartIso12_24_10.h"
OrionTrSmartIso12_24_10::OrionTrSmartIso12_24_10()
{
}
OrionTrSmartIso12_24_10::~OrionTrSmartIso12_24_10()
{
}
void OrionTrSmartIso12_24_10::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&Data);
}
void OrionTrSmartIso12_24_10::DoSimulation_100ms(Int32 slotCounter_100ms)
{
    Float out0_Float;
    if ((slotCounter_100ms % 10) == 0)
    {
        SimulateVoltOutput(
                Data.VoltInput.GetValue(), 
                Data.IsOutputActive.GetValue(), 
                &out0_Float
        );
        Data.VoltOutput.SetValue(out0_Float);
    } // if
}
void OrionTrSmartIso12_24_10::SimulateVoltOutput(Float voltInput, Bool isOutputActive, Float* voltOutput)
{
}
