// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ConsumerModel.h"
ConsumerModel::ConsumerModel()
{
}
ConsumerModel::~ConsumerModel()
{
}
// Initialize simulation model
void ConsumerModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&DataModel);
    AddData((ioDataCollection*)&DataProgram);
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void ConsumerModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
