// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CONSUMERMODEL_H)
#define __CONSUMERMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ops/Consume/ConsumerModelData.h"
#include "Programs/Ids/Consume/SwitchboardData.h"
class ConsumerModel : public ioModel
{
public:
    ConsumerModel();
    virtual ~ConsumerModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    ConsumerModelData DataModel;
    SwitchboardData DataProgram;
};
#endif // __CONSUMERMODEL_H
