// !!! This C++ file is generated by ioStudio !!!
#if !defined(__JUNCTIONMODEL_H)
#define __JUNCTIONMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ops/Consume/ConsumeModelData.h"
#include "Programs/Ops/Consume/JunctionData.h"
#include "Programs/Ops/Consume/SwitchboardData.h"
class JunctionModel : public ioModel
{
public:
    JunctionModel();
    virtual ~JunctionModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    ConsumeModelData DataModel;
    JunctionData DataDevice;
    SwitchboardData DataOperation;
};
#endif // __JUNCTIONMODEL_H
