// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "JunctionModel.h"
JunctionModel::JunctionModel()
{
}
JunctionModel::~JunctionModel()
{
}
// Initialize simulation model
void JunctionModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&DataModel);
    AddData((ioDataCollection*)&DataDevice);
    AddData((ioDataCollection*)&DataOperation);
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void JunctionModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
