// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchBoardModel.h"
SwitchBoardModel::SwitchBoardModel()
{
}
SwitchBoardModel::~SwitchBoardModel()
{
}
// Initialize simulation model
void SwitchBoardModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&DataProgram);
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void SwitchBoardModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
