// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "SwitchboardModel.h"
SwitchboardModel::SwitchboardModel()
{
}
SwitchboardModel::~SwitchboardModel()
{
}
// Initialize simulation model
void SwitchboardModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&DataModel);
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void SwitchboardModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
