// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BattDcPanel.h"
BattDcPanel::BattDcPanel()
{
}
BattDcPanel::~BattDcPanel()
{
}
void BattDcPanel::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_BattDcPanelGraphics, 7);
}
