///////////////////////////////////////////////////////////
//  ObAppButton.cs
//  Implementation of the Class ObAppButton
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:46:35
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeAppLib.Components.Button 
{
    public enum ObAppButtonSize
    {
        Normal = 0,
        Small
    }

	public class ObAppButton 
    {
		public bool Checked;
		public string Label;
		public ObAppButtonSize Size;

		public ObAppButton()
        {
            Checked = false;
            Label = string.Empty;
            Size = ObAppButtonSize.Normal;
		}

		~ObAppButton()
        {
		}

	}//end ObAppButton
}//end namespace Button
