///////////////////////////////////////////////////////////
//  ObToggleButtonOption.cs
//  Implementation of the Class ObToggleButtonOption
//  Generated by Enterprise Architect
//  Created on:      25-Feb-2024 22:47:39
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeAppLib.Components.Button 
{
	public class ObToggleButtonOption 
    {
		public ObToggleButtonOption()
        {
		}

		~ObToggleButtonOption()
        {
		}

	}//end ObToggleButtonOption
}//end namespace Button
