///////////////////////////////////////////////////////////
//  ObInput.cs
//  Implementation of the Class ObInput
//  Generated by Enterprise Architect
//  Created on:      26-Feb-2024 20:52:17
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace OpenBridgeApp.Components.Input 
{
    public enum ObInputType
    {
        Text = 0,
        Password
    }

    public class ObInput 
    {
		public bool HasIcon;
		public string Placeholder;
		public ObInputType Type;
		public string Value;

		public ObInput()
        {
            HasIcon = false;
            Placeholder = string.Empty;
            Type = ObInputType.Text;
            Value = string.Empty;
        }

		~ObInput()
        {
		}

	}//end ObInput

}//end namespace Input
