///////////////////////////////////////////////////////////
//  ObSlider.cs
//  Implementation of the Class ObSlider
//  Generated by Enterprise Architect
//  Created on:      26-Feb-2024 20:54:49
//  Original author: ØyvindMisje
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace OpenBridgeApp.Components.Input 
{
	public class ObSlider 
    {
		public bool HugContainer;
		public string IconLeft;
		public string IconRight;

		public ObSlider()
        {
            IconLeft = string.Empty;
            IconRight = string.Empty;
            HugContainer = false;
		}

		~ObSlider()
        {
		}

	}//end ObSlider

}//end namespace Input
