// !!! This C++ file is generated by ioStudio !!!
#if !defined(__CHARGERMODEL_H)
#define __CHARGERMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Power/Convert/ChargerData.h"
class ChargerModel : public ioModel
{
public:
    ChargerModel();
    virtual ~ChargerModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    virtual void SimulateVoltOutput(Float voltInputAc, Bool isOutputActive, Float* voltOutputDc);
    ChargerData ModelData;
};
#endif // __CHARGERMODEL_H
