// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "ConvDcDcModel.h"
ConvDcDcModel::ConvDcDcModel()
{
}
ConvDcDcModel::~ConvDcDcModel()
{
}
// Initialize simulation model
void ConvDcDcModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&ModelData);
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void ConvDcDcModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
