// !!! This C++ file is generated by ioStudio !!!
#if !defined(__BATTERYMODEL_H)
#define __BATTERYMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ids/Source/DataBattery.h"
#include "Programs/Ops/Source/DataBatteryModel.h"
class BatteryModel : public ioModel
{
public:
    BatteryModel();
    virtual ~BatteryModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    DataBattery BatteryData;
    DataBatteryModel ModelData;
};
#endif // __BATTERYMODEL_H
