// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "BatteryModel.h"
BatteryModel::BatteryModel()
{
}
BatteryModel::~BatteryModel()
{
}
// Initialize simulation model
void BatteryModel::InitializeItem(void)
{
    ioModel::InitializeItem();
    AddData((ioDataCollection*)&BatteryData);
    AddData((ioDataCollection*)&ModelData);
}
// Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
void BatteryModel::DoSimulation_100ms(Int32 slotCounter_100ms)
{
}
