// !!! This C++ file is generated by ioStudio !!!
#if !defined(__GENERATORMODEL_H)
#define __GENERATORMODEL_H
#include "ioSystem/Simulation/ioModel.h"
#include "Programs/Ops/Source/DataGenerator.h"
class GeneratorModel : public ioModel
{
public:
    GeneratorModel();
    virtual ~GeneratorModel();
    // Initialize simulation model
    virtual void InitializeItem(void);
    // Do simulation every 100ms (slotCounter_100ms: Slot ID for simulation task)
    virtual void DoSimulation_100ms(Int32 slotCounter_100ms);
    DataGenerator GeneratorData;
};
#endif // __GENERATORMODEL_H
