// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "DataDcDc.h"
DataDcDc::DataDcDc()
{
    InitializeData();
}
DataDcDc::~DataDcDc()
{
}
void DataDcDc::InitializeData(void)
{
    SetListData(m_ListData, 6);
    ResetItem();
    VoltageInputDcDc.SetValue((Float)12.00);
    AddData((ioData*)&VoltageInputDcDc, Duid_Ids_Convert_VoltageInputDcDc);
    VoltageOutputDcDc.SetValue((Float)24);
    AddData((ioData*)&VoltageOutputDcDc, Duid_Ids_Convert_VoltageOutputDcDc);
    IsDcDcOutputActive.SetValue(TRUE);
    AddData((ioData*)&IsDcDcOutputActive, Duid_Ids_Convert_IsDcDcOutputActive);
    MaxOutCurrentDcDc.SetValue((Float)20);
    AddData((ioData*)&MaxOutCurrentDcDc, Duid_Ids_Convert_MaxOutCurrentDcDc);
    CurrentInputDcDc.SetValue((Float)0.0);
    AddData((ioData*)&CurrentInputDcDc, Duid_Ids_Convert_CurrentInputDcDc);
    CurrentOutputDcDc.SetValue((Float)0.0);
    AddData((ioData*)&CurrentOutputDcDc, Duid_Ids_Convert_CurrentOutputDcDc);
}
