// !!! This C++ file is generated by ioStudio !!!
#if !defined(__DATACHARGE_H)
#define __DATACHARGE_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
#include "ioSystem/Data/ioArray.h"
class DataCharge : public ioDataCollection
{
public:
    DataCharge();
    virtual ~DataCharge();
    void InitializeData(void);
    ioVarFloat VoltageInputAc;
    ioVarBool IsChargingActive;
    ioArray CurrentOutputDc;
    ioArray VoltageOutputDc;
    ioVarFloat CurrentInputAc;
    ioArray MaxOutCurrentDc;
protected:
    ioData* m_ListData[6];
    ioNum* m_CurrentOutputDcNumbers[3];
    ioNumFloat m_CurrentOutputDcValues[3];
    ioNum* m_VoltageOutputDcNumbers[3];
    ioNumFloat m_VoltageOutputDcValues[3];
    ioNum* m_MaxOutCurrentDcNumbers[3];
    ioNumFloat m_MaxOutCurrentDcValues[3];
};
#endif // __DATACHARGE_H
