// !!! This C++ file is generated by ioStudio !!!
#if !defined(__DATADCDC_H)
#define __DATADCDC_H
#include "ioSystem/Data/ioDataCollection.h"
#include "ioSystem/Data/ioVar.h"
#include "Programs/ioSystemData.h"
class DataDcDc : public ioDataCollection
{
public:
    DataDcDc();
    virtual ~DataDcDc();
    void InitializeData(void);
    ioVarFloat VoltageInputDcDc;
    ioVarFloat VoltageOutputDcDc;
    ioVarBool IsDcDcOutputActive;
    ioVarFloat MaxOutCurrentDcDc;
protected:
    ioData* m_ListData[4];
};
#endif // __DATADCDC_H
