// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PanelDcDc.h"
#include "Programs/ioSystemGraphics.h"
PanelDcDc::PanelDcDc()
{
}
PanelDcDc::~PanelDcDc()
{
}
void PanelDcDc::InitializeData(void)
{
    m_PanelGraphics.SetListData((ioItem**)m_PanelDcDcGraphics, 5);
//    AddGraphics(&SelectDcDc, Puid_Ids_Convert_SelectDcDc);
    AddGraphics(&LabelHeaderDcDcInput, Puid_Ids_Convert_LabelHeaderDcDcInput);
    LabelHeaderDcDcInput.SetTextForced((ioChars)"DC-DC INPUT [VDC]");
    AddGraphics(&LabelHeaderDcDcOutput, Puid_Ids_Convert_LabelHeaderDcDcOutput);
    LabelHeaderDcDcOutput.SetTextForced((ioChars)"DC-DC OUTPUT [VDC]");
    AddGraphics(&InstrVoltInputDcDc, Puid_Ids_Convert_InstrVoltInputDcDc);
    InstrVoltInputDcDc.SetTextForced((ioChars)"12.1");
    InstrVoltInputDcDc.SetDecimals(1);
    AddGraphics(&InstrVoltOutputDcDc, Puid_Ids_Convert_InstrVoltOutputDcDc);
    InstrVoltOutputDcDc.SetTextForced((ioChars)"24.2");
    InstrVoltOutputDcDc.SetDecimals(1);
}
