// !!! This C++ file is generated by ioStudio !!!
#if !defined(__PANELCHARGE_H)
#define __PANELCHARGE_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioComboBox.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class PanelCharge : public ioPanel
{
public:
    PanelCharge();
    virtual ~PanelCharge();
    virtual void InitializeData(void);
    ioComboBox SelectCharger;
    ioTextBlock InstrVoltOutputDc;
    ioLabel LabelHeaderChargeInput;
    ioLabel LabelHeaderChargeOutput;
    ioTextBlock InstrVoltInputAc;
    ioTextBlock InstVoltOutputDc;
protected:
    ioGraphics* m_PanelChargeGraphics[6];
};
#endif // __PANELCHARGE_H
