// !!! This C++ file is generated by ioStudio !!!
#if !defined(__PANELDCDC_H)
#define __PANELDCDC_H
#include "ioSystem/Panels/ioPanel.h"
#include "ioSystem/Panels/ioComboBox.h"
#include "ioSystem/Panels/ioGraphicsText.h"
class PanelDcDc : public ioPanel
{
public:
    PanelDcDc();
    virtual ~PanelDcDc();
    virtual void InitializeData(void);
    ioComboBox SelectDcDc;
    ioLabel LabelHeaderDcDcInput;
    ioLabel LabelHeaderDcDcOutput;
    ioTextBlock InstrVoltInputDcDc;
    ioTextBlock InstrVoltOutputDcDc;
protected:
    ioGraphics* m_PanelDcDcGraphics[5];
};
#endif // __PANELDCDC_H
