// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowModes.h"
PowModes::PowModes()
{
    InitializeData();
}
PowModes::~PowModes()
{
}
void PowModes::InitializeData(void)
{
}
