// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWMODES_H)
#define __POWMODES_H
#include "ioSystem/Panels/ioPanel.h"
class PowModes : public ioPanel
{
public:
    PowModes();
    virtual ~PowModes();
    void InitializeData(void);
};
#endif // __POWMODES_H
