// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWOPERATIONMODE_H)
#define __POWOPERATIONMODE_H
#include "ioSystem/Panels/ioPanel.h"
class PowOperationMode : public ioPanel
{
public:
    PowOperationMode();
    virtual ~PowOperationMode();
    void InitializeData(void);
};
#endif // __POWOPERATIONMODE_H
