// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWOPERATION_H)
#define __POWOPERATION_H
#include "ioSystem/Panels/ioPanel.h"
class PowOperation : public ioPanel
{
public:
    PowOperation();
    virtual ~PowOperation();
    void InitializeData(void);
};
#endif // __POWOPERATION_H
