// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowOperation.h"
PowOperation::PowOperation()
{
    InitializeData();
}
PowOperation::~PowOperation()
{
}
void PowOperation::InitializeData(void)
{
}
