// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowProgControl12V.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
PowProgControl12V::PowProgControl12V()
{
}
PowProgControl12V::~PowProgControl12V()
{
}
void PowProgControl12V::InitializeTask(void)
{
    ioProgram::InitializeTask();
}
void PowProgControl12V::ReceiveData(ioDataCollection* listData, ioData* data)
{
    ioVarInt32 in1_Int32;
    ioVarInt32 in2_Int32;
    ioVarBool in3_Bool;
    if (listData == NULL) {}
    if (data == NULL) {}
    else
    {
        ioSystemDataType duid = ioSystemData::GetDataType(data->GetDataID());
        switch (duid)
        {
        case Duid_Pow_Out12A_SwitchOn:
            in1_Int32.SetValue(0);
            in2_Int32.SetValueVar(&PortOut12A.OnOffCh);
            in3_Bool.SetValue(TRUE);
            OnRecvSwitchOnOff(&in1_Int32, &in2_Int32, &in3_Bool);
            SendData(&PortOut12A.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpM_12);
            SendData(&PortOut12A.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpA_13);
            break;
        case Duid_Pow_Out12A_SwitchOff:
            in1_Int32.SetValue(0);
            in2_Int32.SetValueVar(&PortOut12A.OnOffCh);
            in3_Bool.SetValue(FALSE);
            OnRecvSwitchOnOff(&in1_Int32, &in2_Int32, &in3_Bool);
            SendData(&PortOut12A.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpM_12);
            SendData(&PortOut12A.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpA_13);
            break;
        case Duid_Pow_Out12F_SwitchOn:
            in1_Int32.SetValue(2);
            in2_Int32.SetValueVar(&PortOut12F.OnOffCh);
            in3_Bool.SetValue(TRUE);
            OnRecvSwitchOnOff(&in1_Int32, &in2_Int32, &in3_Bool);
            SendData(&PortOut12F.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpM_12);
            SendData(&PortOut12F.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpA_13);
            break;
        case Duid_Pow_Out12F_SwitchOff:
            in1_Int32.SetValue(2);
            in2_Int32.SetValueVar(&PortOut12F.OnOffCh);
            in3_Bool.SetValue(FALSE);
            OnRecvSwitchOnOff(&in1_Int32, &in2_Int32, &in3_Bool);
            SendData(&PortOut12F.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpM_12);
            SendData(&PortOut12F.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpA_13);
            break;
        case Duid_Pow_Out12M_SwitchOn:
            in1_Int32.SetValue(1);
            in2_Int32.SetValueVar(&PortOut12M.OnOffCh);
            in3_Bool.SetValue(TRUE);
            OnRecvSwitchOnOff(&in1_Int32, &in2_Int32, &in3_Bool);
            SendData(&PortOut12M.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpM_12);
            SendData(&PortOut12M.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpA_13);
            break;
        case Duid_Pow_Out12M_SwitchOff:
            in1_Int32.SetValue(1);
            in2_Int32.SetValueVar(&PortOut12M.OnOffCh);
            in3_Bool.SetValue(FALSE);
            OnRecvSwitchOnOff(&in1_Int32, &in2_Int32, &in3_Bool);
            SendData(&PortOut12M.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpM_12);
            SendData(&PortOut12M.OutStatus, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_OpA_13);
            break;
        } // switch
    } // else
}
void PowProgControl12V::OnRecvSwitchOnOff(ioVarInt32* device, ioVarInt32* channel, ioVarBool* isOn)
{
    if (device == NULL) {};
    if (channel == NULL) {};
    if (isOn == NULL) {};
}
