// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWPROGOPERATEM_H)
#define __POWPROGOPERATEM_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Pow/Cp/PowCpDataCpM.h"
#include "Programs/Pow/Out/PowOutDataOut24M.h"
#include "Programs/Pow/Out/PowOutDataOut24F.h"
#include "Programs/Pow/Out/PowOutDataOut24A.h"
#include "Programs/Pow/Out/PowOutDataOut220M.h"
#include "Programs/Pow/Out/PowOutDataOut220F.h"
#include "Programs/Pow/Out/PowOutDataOut220A.h"
#include "Programs/Pow/Cp/PowCommandPanelCpM.h"
#include "Programs/Pow/Out/PowOutPanelOut24M.h"
#include "Programs/Pow/Out/PowOutPanelOut24F.h"
#include "Programs/Pow/Out/PowOutPanelOut24A.h"
#include "Programs/Pow/Out/PowOutPanelOut220M.h"
#include "Programs/Pow/Out/PowOutPanelOut220F.h"
#include "Programs/Pow/Out/PowOutPanelOut220A.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut24M.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut24F.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut24A.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut220M.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut220F.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut220A.h"
#include "Programs/Pow/Cp/PowModePanelCpM.h"
class PowProgOperateM : public ioProgram
{
public:
    PowProgOperateM();
    virtual ~PowProgOperateM();
    virtual void InitializeTask(void);
    virtual void Run(Int32 activeSlot);
    virtual void ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    virtual void ReceiveOnChangeCommandPow(ioVarInt32* activeStation);
    PowCpDataCpM DataCmdCpM;
    PowOutDataOut24M PortOut24M;
    PowOutDataOut24F PortOut24F;
    PowOutDataOut24A PortOut24A;
    PowOutDataOut220M PortOut220M;
    PowOutDataOut220F PortOut220F;
    PowOutDataOut220A PortOut220A;
    PowCommandPanelCpM PanelCmdCpM;
    PowOutPanelOut24M PanelOut24M;
    PowOutPanelOut24F PanelOut24F;
    PowOutPanelOut24A PanelOut24A;
    PowOutPanelOut220M PanelOut220M;
    PowOutPanelOut220F PanelOut220F;
    PowOutPanelOut220A PanelOut220A;
    PowIndicatorPanelOut24M PanelIndOut24M;
    PowIndicatorPanelOut24F PanelIndOut24F;
    PowIndicatorPanelOut24A PanelIndOut24A;
    PowIndicatorPanelOut220M PanelIndOut220M;
    PowIndicatorPanelOut220F PanelIndOut220F;
    PowIndicatorPanelOut220A PanelIndOut220A;
    PowModePanelCpM PanelModeCpM;
};
#endif // __POWPROGOPERATEM_H
