// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWPROGOPERATEM12V_H)
#define __POWPROGOPERATEM12V_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Pow/Out/PowOutDataOut12M.h"
#include "Programs/Pow/Out/PowOutDataOut12F.h"
#include "Programs/Pow/Out/PowOutDataOut12A.h"
#include "Programs/Pow/Out/PowOutPanelOut12M.h"
#include "Programs/Pow/Out/PowOutPanelOut12F.h"
#include "Programs/Pow/Out/PowOutPanelOut12A.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut12M.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut12F.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut12A.h"
class PowProgOperateM12V : public ioProgram
{
public:
    PowProgOperateM12V();
    virtual ~PowProgOperateM12V();
    virtual void InitializeTask(void);
    virtual void ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    PowOutDataOut12M PortOut12M;
    PowOutDataOut12F PortOut12F;
    PowOutDataOut12A PortOut12A;
    PowOutPanelOut12M PanelOut12M;
    PowOutPanelOut12F PanelOut12F;
    PowOutPanelOut12A PanelOut12A;
    PowIndicatorPanelOut12M PanelIndOut12M;
    PowIndicatorPanelOut12F PanelIndOut12F;
    PowIndicatorPanelOut12A PanelIndOut12A;
};
#endif // __POWPROGOPERATEM12V_H
