// !!! This file is generated by ioStudio !!!
#if !defined(__POWPROGCONTROL_H)
#define __POWPROGCONTROL_H
#include "ioSystem/Threading/ioTask.h"
#include "Programs/Pow/Out/PowOutDataOut12M.h"
#include "Programs/Pow/Out/PowOutDataOut12F.h"
#include "Programs/Pow/Out/PowOutDataOut12A.h"
#include "Programs/Pow/Out/PowOutDataOut24M.h"
#include "Programs/Pow/Out/PowOutDataOut24F.h"
#include "Programs/Pow/Out/PowOutDataOut24A.h"
#include "Programs/Pow/Out/PowOutDataOut220M.h"
#include "Programs/Pow/Out/PowOutDataOut220F.h"
#include "Programs/Pow/Out/PowOutDataOut220A.h"
class PowProgControl : public ioTask
{
public:
    PowProgControl();
    virtual ~PowProgControl();
    virtual void ReadInput(Int32 activeSlot);
    virtual void Run(Int32 activeSlot);
    virtual void WriteOutput(Int32 activeSlot);
    PowOutDataOut12M PortOut12M;
    PowOutDataOut12F PortOut12F;
    PowOutDataOut12A PortOut12A;
    PowOutDataOut24M PortOut24M;
    PowOutDataOut24F PortOut24F;
    PowOutDataOut24A PortOut24A;
    PowOutDataOut220M PortOut220M;
    PowOutDataOut220F PortOut220F;
    PowOutDataOut220A PortOut220A;
};
#endif // __POWPROGCONTROL_H
