// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowProgOperateA.h"
#include "Programs/ioSystemGraphics.h"
#include "Programs/ioSystemPorts.h"
PowProgOperateA::PowProgOperateA()
{
}
PowProgOperateA::~PowProgOperateA()
{
}
void PowProgOperateA::InitializeTask(void)
{
    ioProgram::InitializeTask();
    AddPanel((ioPanel*)&PanelCmdCpA);
    AddPanel((ioPanel*)&PanelOut12M);
    AddPanel((ioPanel*)&PanelOut12F);
    AddPanel((ioPanel*)&PanelOut12A);
    AddPanel((ioPanel*)&PanelOut24M);
    AddPanel((ioPanel*)&PanelOut24F);
    AddPanel((ioPanel*)&PanelOut24A);
    AddPanel((ioPanel*)&PanelOut220M);
    AddPanel((ioPanel*)&PanelOut220F);
    AddPanel((ioPanel*)&PanelOut220A);
    AddPanel((ioPanel*)&PanelIndOut12M);
    AddPanel((ioPanel*)&PanelIndOut12F);
    AddPanel((ioPanel*)&PanelIndOut12A);
    AddPanel((ioPanel*)&PanelIndOut24M);
    AddPanel((ioPanel*)&PanelIndOut24F);
    AddPanel((ioPanel*)&PanelIndOut24A);
    AddPanel((ioPanel*)&PanelIndOut220M);
    AddPanel((ioPanel*)&PanelIndOut220F);
    AddPanel((ioPanel*)&PanelIndOut220A);
}
void PowProgOperateA::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {}
}
void PowProgOperateA::ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent)
{
    ioSystemGraphicsType puid = ioSystemGraphics::GetGraphicsType(puidValue);
    if (puidValue == 0) {}
    if (typeEvent == ioProgramGraphicsEvent_NotDefined) {}
    switch (puid)
    {
    case Puid_Pow_CpA_ButtTakeRequestPow:
        if (typeEvent == ioProgramGraphicsEvent_Clicked)
            SendData(&DataCmdCpA.TakeCommandPow, ioPortProgramProtocol_System, (Int32)Nuid_NetEthernet_192_168_10_Ids_CcM_C6015_11);
        break;
    } // switch
}
void PowProgOperateA::ReceiveData(ioDataCollection* listData, ioData* data)
{
    if (listData == NULL) {}
    if (data == NULL) {}
    else
    {
        ioSystemDataType duid = ioSystemData::GetDataType(data->GetDataID());
        switch (duid)
        {
        case Duid_Pow_CpA_OnChangeCommandPow:
            PanelCmdCpA.TextCommandStatusPow.SetValueVar(&DataCmdCpA.ActiveStationPow);
            break;
        } // switch
    } // else
}
