// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowProgOperate.h"
PowProgOperate::PowProgOperate()
{
}
PowProgOperate::~PowProgOperate()
{
}
void PowProgOperate::ReadInput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void PowProgOperate::Run(Int32 activeSlot)
{
    Int64 retInt64;
    Bool in1_Bool;
    ioStringL out1_String;
    if (activeSlot == 0) {};
    in1_Bool = PortOut12M.OnCh1.GetValue();
    retInt64 = SetPanelPowIcon(in1_Bool, &out1_String);
    PanelOut12M.IconCh1.SetIconID(retInt64);
    PanelOut12M.ButtOnCh1.SetText(&out1_String);
}
void PowProgOperate::WriteOutput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
Int64 PowProgOperate::SetPanelPowIcon(Bool isPowChOn, ioString* iconId)
{
    if (isPowChOn == 0) {};
    if (iconId == NULL) {};
    return 0;
}
