// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWPROGCONTROL12V_H)
#define __POWPROGCONTROL12V_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Pow/Out/PowOutDataOut12M.h"
#include "Programs/Pow/Out/PowOutDataOut12F.h"
#include "Programs/Pow/Out/PowOutDataOut12A.h"
class PowProgControl12V : public ioProgram
{
public:
    PowProgControl12V();
    virtual ~PowProgControl12V();
    virtual void InitializeTask(void);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    virtual void OnRecvSwitchOnOff(ioVarInt32* device, ioVarInt32* channel, ioVarBool* isOn);
    PowOutDataOut12M PortOut12M;
    PowOutDataOut12F PortOut12F;
    PowOutDataOut12A PortOut12A;
};
#endif // __POWPROGCONTROL12V_H
