// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowProgOperate.h"
PowProgOperate::PowProgOperate()
{
}
PowProgOperate::~PowProgOperate()
{
}
void PowProgOperate::Run(Int32 activeSlot)
{
    ioVarBool in1_Bool;
    ioString out1_String;
    if (activeSlot == 0) {}
    in1_Bool.SetValueVar(&PortOut12M.OnCh1);
    SetPanelPowIcon(&in1_Bool, &out1_String);
//    PanelOut12M.ButtOnCh1.SetValueVar(&out1_String);
}
void PowProgOperate::SetPanelPowIcon(ioVarBool* isPowChOn, ioString* iconId)
{
    if (isPowChOn == NULL) {};
    if (iconId == NULL) {};
}
