// !!! This C++ file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowPanel.h"
#include "Programs/ioSystemGraphics.h"
PowPanel::PowPanel()
{
}
PowPanel::~PowPanel()
{
}
void PowPanel::InitializeData(void)
{
}
