// !!! This file is generated by ioStudio !!!
#include "pch.h"
#pragma hdrstop
#include "PowProgControl.h"
PowProgControl::PowProgControl()
{
}
PowProgControl::~PowProgControl()
{
}
void PowProgControl::ReadInput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void PowProgControl::Run(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void PowProgControl::WriteOutput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
