// !!! This file is generated by ioStudio !!!
// Generation date and time: 22.FEB.2024 06:51:01
#include "pch.h"
#pragma hdrstop
#include "PowProg.h"
PowProg::PowProg()
{
}
PowProg::~PowProg()
{
}
void PowProg::ReadInput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
void PowProg::Run(Int32 activeSlot)
{
    Int64 retInt64;
    Bool in1_Bool;
    ioStringL out1_String;
    if (activeSlot == 0) {};
    in1_Bool = PortOut12M.OnCh1.GetValue();
    retInt64 = SetPanelPowIcon(in1_Bool, &out1_String);
    PanelOut12M.IconCh1.SetIconID(retInt64);
    PanelOut12M.ButtOnCh1.SetText(&out1_String);
}
void PowProg::WriteOutput(Int32 activeSlot)
{
    if (activeSlot == 0) {};
}
Int64 PowProg::SetPanelPowIcon(Bool isPowChOn, ioString* iconId)
{
    if (isPowChOn == 0) {};
    if (iconId == NULL) {};
    return 0;
}
