// !!! This C++ file is generated by ioStudio !!!
#if !defined(__POWPROGOPERATEA_H)
#define __POWPROGOPERATEA_H
#include "ioSystem/Program/Core/ioProgram.h"
#include "Programs/Pow/Cp/PowCpDataCpA.h"
#include "Programs/Pow/Out/PowOutDataOut12M.h"
#include "Programs/Pow/Out/PowOutDataOut12F.h"
#include "Programs/Pow/Out/PowOutDataOut12A.h"
#include "Programs/Pow/Out/PowOutDataOut24M.h"
#include "Programs/Pow/Out/PowOutDataOut24F.h"
#include "Programs/Pow/Out/PowOutDataOut24A.h"
#include "Programs/Pow/Out/PowOutDataOut220M.h"
#include "Programs/Pow/Out/PowOutDataOut220F.h"
#include "Programs/Pow/Out/PowOutDataOut220A.h"
#include "Programs/Pow/Cp/PowCommandPanelCpA.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut12M.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut12F.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut12A.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut24M.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut24F.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut24A.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut220M.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut220F.h"
#include "Programs/Pow/Out/PowIndicatorPanelOut220A.h"
class PowProgOperateA : public ioProgram
{
public:
    PowProgOperateA();
    virtual ~PowProgOperateA();
    virtual void InitializeTask(void);
    virtual void Run(Int32 activeSlot);
    virtual void ReceiveGraphicsEvent(Int32 puidValue, ioProgramGraphicsEvent typeEvent);
    virtual void ReceiveData(ioDataCollection* listData, ioData* data);
    virtual void ReceiveOnChangeCommandPow(ioVarInt32* activeStation);
    PowCpDataCpA DataCmdCpA;
    PowOutDataOut12M PortOut12M;
    PowOutDataOut12F PortOut12F;
    PowOutDataOut12A PortOut12A;
    PowOutDataOut24M PortOut24M;
    PowOutDataOut24F PortOut24F;
    PowOutDataOut24A PortOut24A;
    PowOutDataOut220M PortOut220M;
    PowOutDataOut220F PortOut220F;
    PowOutDataOut220A PortOut220A;
    PowCommandPanelCpA PanelCmdCpA;
    PowIndicatorPanelOut12M PanelIndOut12M;
    PowIndicatorPanelOut12F PanelIndOut12F;
    PowIndicatorPanelOut12A PanelIndOut12A;
    PowIndicatorPanelOut24M PanelIndOut24M;
    PowIndicatorPanelOut24F PanelIndOut24F;
    PowIndicatorPanelOut24A PanelIndOut24A;
    PowIndicatorPanelOut220M PanelIndOut220M;
    PowIndicatorPanelOut220F PanelIndOut220F;
    PowIndicatorPanelOut220A PanelIndOut220A;
};
#endif // __POWPROGOPERATEA_H
