// !!! This file is generated by ioStudio !!!
#if !defined(__POWPROGOPERATE_H)
#define __POWPROGOPERATE_H
#include "ioSystem/Threading/ioTask.h"
#include "Programs/Pow/Out/PowOutDataOut12M.h"
#include "Programs/Pow/Out/PowOutDataOut12F.h"
#include "Programs/Pow/Out/PowOutDataOut12A.h"
#include "Programs/Pow/Out/PowOutDataOut24M.h"
#include "Programs/Pow/Out/PowOutDataOut24F.h"
#include "Programs/Pow/Out/PowOutDataOut24A.h"
#include "Programs/Pow/Out/PowOutDataOut220M.h"
#include "Programs/Pow/Out/PowOutDataOut220F.h"
#include "Programs/Pow/Out/PowOutDataOut220A.h"
#include "Programs/Pow/Out/PowOutPanelOut12M.h"
#include "Programs/Pow/Out/PowOutPanelOut12F.h"
#include "Programs/Pow/Out/PowOutPanelOut12A.h"
#include "Programs/Pow/Out/PowOutPanelOut24M.h"
#include "Programs/Pow/Out/PowOutPanelOut24F.h"
#include "Programs/Pow/Out/PowOutPanelOut24A.h"
#include "Programs/Pow/Out/PowOutPanelOut220M.h"
#include "Programs/Pow/Out/PowOutPanelOut220F.h"
#include "Programs/Pow/Out/PowOutPanelOut220A.h"
class PowProgOperate : public ioTask
{
public:
    PowProgOperate();
    virtual ~PowProgOperate();
    virtual void ReadInput(Int32 activeSlot);
    virtual void Run(Int32 activeSlot);
    virtual void WriteOutput(Int32 activeSlot);
    virtual Int64 SetPanelPowIcon(Bool isPowChOn, ioString* iconId);
    PowOutDataOut12M PortOut12M;
    PowOutDataOut12F PortOut12F;
    PowOutDataOut12A PortOut12A;
    PowOutDataOut24M PortOut24M;
    PowOutDataOut24F PortOut24F;
    PowOutDataOut24A PortOut24A;
    PowOutDataOut220M PortOut220M;
    PowOutDataOut220F PortOut220F;
    PowOutDataOut220A PortOut220A;
    PowOutPanelOut12M PanelOut12M;
    PowOutPanelOut12F PanelOut12F;
    PowOutPanelOut12A PanelOut12A;
    PowOutPanelOut24M PanelOut24M;
    PowOutPanelOut24F PanelOut24F;
    PowOutPanelOut24A PanelOut24A;
    PowOutPanelOut220M PanelOut220M;
    PowOutPanelOut220F PanelOut220F;
    PowOutPanelOut220A PanelOut220A;
};
#endif // __POWPROGOPERATE_H
